### ISSUE TITLE
ios 连接 连接不上 

### ISSUE THREAD

**Issue by HLYDSR** [wildfirechat/ios-chat#100]
连接状态一直在  Connection status changed to (0)和Connection status changed to (-1)之间跳动  服务器版本0.34  ios版本1.0.17
03/12/2019 15:10:29,509 [nioEventLoopGroup-5-13] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:29,510 [pool-2-thread-23] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=66CBBEE8-5ED8-4432-ABF4-DAC8302CA1E8, topic=ROUTE
03/12/2019 15:10:29,514 [pool-1-thread-23] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:32,688 [nioEventLoopGroup-5-14] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:32,689 [pool-2-thread-12] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=B2E8CDE0-09AA-4D2E-9146-9D0C951320A3, topic=ROUTE
03/12/2019 15:10:32,693 [pool-1-thread-12] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:32,773 [nioEventLoopGroup-5-15] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:32,774 [pool-2-thread-24] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=B2E8CDE0-09AA-4D2E-9146-9D0C951320A3, topic=ROUTE
03/12/2019 15:10:32,779 [pool-1-thread-24] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:33,523 [nioEventLoopGroup-5-16] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:33,524 [pool-2-thread-2] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=66CBBEE8-5ED8-4432-ABF4-DAC8302CA1E8, topic=ROUTE
03/12/2019 15:10:33,529 [pool-1-thread-2] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:33,616 [nioEventLoopGroup-5-17] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:33,616 [pool-2-thread-25] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=66CBBEE8-5ED8-4432-ABF4-DAC8302CA1E8, topic=ROUTE
03/12/2019 15:10:33,621 [pool-1-thread-25] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:36,979 [nioEventLoopGroup-5-18] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:36,980 [pool-2-thread-13] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=B2E8CDE0-09AA-4D2E-9146-9D0C951320A3, topic=ROUTE
03/12/2019 15:10:36,987 [pool-1-thread-13] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:37,071 [nioEventLoopGroup-5-19] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:37,071 [pool-2-thread-26] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=B2E8CDE0-09AA-4D2E-9146-9D0C951320A3, topic=ROUTE
03/12/2019 15:10:37,078 [pool-1-thread-26] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:37,630 [nioEventLoopGroup-5-20] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:37,631 [pool-2-thread-7] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=66CBBEE8-5ED8-4432-ABF4-DAC8302CA1E8, topic=ROUTE
03/12/2019 15:10:37,635 [pool-1-thread-7] INFO  DatabaseStore 1405  - Update rows 1
03/12/2019 15:10:37,716 [nioEventLoopGroup-5-21] INFO  Qos1PublishHandler 152  - imHandler fromUser=100490, topic=ROUTE
03/12/2019 15:10:37,717 [pool-2-thread-27] INFO  IMHandler 156  - imHandler fromUser=100490, clientId=66CBBEE8-5ED8-4432-ABF4-DAC8302CA1E8, topic=ROUTE
03/12/2019 15:10:37,722 [pool-1-thread-27] INFO  DatabaseStore 1405  - Update rows 1

**Comment by heavyrain2012** [comment]
贴一下客户端的日志

**Comment by heavyrain2012** [comment]
由于没有补充信息，issue关闭，如果有补充信息，请新提个issue
