### ISSUE TITLE
iOS 我被踢出群聊之前如果将群聊置顶或者设置免打扰，我被踢出群聊之后，这些会话就再也删除不掉了，神烦

### ISSUE THREAD

**Issue by iOS-Kel** [wildfirechat/ios-chat#102]
iOS 为啥有些会话怎么删都删不掉，重装APP就又出来了，求大佬解决bug

**Comment by heavyrain2012** [comment]
服务器端什么版本？

**Comment by heavyrain2012** [comment]
参考微信的使用习惯，把人从群里踢出后要保留群消息的，重装app后会同步到这些消息，会话是根据消息生成，所有就生成了会话。

没有直接的解决办法，这是设计的问题。有个曲线的解决办法，在服务的配置中，关掉历史消息同步开关，重装之后不再同步历史消息。

**Comment by iOS-Kel** [comment]
谢谢
