### ISSUE TITLE
IOS端聊天界面，文件发送功能

### ISSUE THREAD

**Issue by dilenzhu** [wildfirechat/ios-chat#103]
1、文件发送功能目前调用文件选择器时，无法进行分类查询或搜索(文件只能一个个目录中寻找)
2、聊天窗口中点击文件打开后是空白页面，需要点击右上角...，选择使用什么方式打开

谢谢！

**Comment by heavyrain2012** [comment]
你好，这些是UI层的事情，请你们自己处理
