### ISSUE TITLE
编译后在真机上测试只能登录，不能聊天，聊天界面一直显示连接中

### ISSUE THREAD

**Issue by LaeChange** [wildfirechat/ios-chat#104]
编译后在真机上测试只能登录，不能聊天，聊天界面一直显示连接中。安卓端功能正常，但是IOS端只能登录，无法发送和接收消息。

**Comment by imndx** [comment]
你好，请提供日志，不然没法分析。

**Comment by LaeChange** [comment]
![微信图片_20191210153645](https://user-images.githubusercontent.com/46321649/70513905-7b2aa900-1b6d-11ea-8b2a-304efbcffdcb.jpg)

**Comment by heavyrain2012** [comment]
日志太少了，抓个从启动开始，10秒钟长度的日志，以文本形式附上来

**Comment by heavyrain2012** [comment]
可能跟我们最近服务器的bug有关，请把服务器升级到最新版测试一下
