### ISSUE TITLE
Moments*.framework和bugly.framework没有开源

### ISSUE THREAD

**Issue by xujingzhou** [wildfirechat/ios-chat#108]
你好，我看到其中Moments*.framework和bugly.framework都没有开源。想知道这2个分别具体是做什么的？ 没源码会影响到什么如果想修改的话？

**Comment by heavyrain2012** [comment]
Moments是朋友圈的SDK，朋友圈是收费的，当前还没有完成，客户使用时可以忽略或者直接删除掉。

bugly是bug收集工具，请参考 https://bugly.qq.com，客户可以替换为自己的账户，或者去掉库和相关代码
