### ISSUE TITLE
更新WFChatClient工程后，Archive时提示找不到<WFChatClient/WFCChatClient.h>

### ISSUE THREAD

**Issue by liang21c** [wildfirechat/ios-chat#110]
之前的工程是1.0.9，更新了1.0.17版本的WFChatClient工程后可以正常调试运行。但在Archive时会提示找不到<WFChatClient/WFCChatClient.h>头文件。

**Comment by heavyrain2012** [comment]
请使用demo验证，如果demo能够复现，请写明demo复现的步骤，谢谢

**Comment by liang21c** [comment]
已用demo验证，可以复现。步骤如下：
用1.0.9版本下的wfclient文件夹整体替换为，1.0.16版本下的wfclient件夹。
可运行，但不能通过Archive生成版本。

**Comment by liang21c** [comment]
找到原因了，是因为1.0.16的client不再支持armv7版本的指令集，把uichat的armv7指令集也去掉就可以。
可以问下是什么原因不再支持armv7的指令集吗？是因为mars不再支持armv7的指令集吗？

**Comment by heavyrain2012** [comment]
需要armv7架构的手机是iphone5及之前的手机，基本上没有这个需求了，去掉armv7架构能减少包的大小
