### ISSUE TITLE
编译WildFireChat时，提示在AppDelegate.m中找不到<WFAVEngineKit/WFAVEngineKit.h>

### ISSUE THREAD

**Issue by LaeChange** [wildfirechat/ios-chat#115]
编译WildFireChat时，提示在AppDelegate.m中找不到<WFAVEngineKit/WFAVEngineKit.h>

**Comment by heavyrain2012** [comment]
需要先编译wfclient和wfuikit两个项目，然后再编译wildfirechat项目

**Comment by LaeChange** [comment]
> 需要先编译wfclient和wfuikit两个项目，然后再编译wildfirechat项目

我知道编译顺序，我先编译的client再编译的uikit，前两个都是编译成功的，只是到chat的时候就编译失败，原因就是找不到这个文件了

**Comment by heavyrain2012** [comment]
你们是不是修改什么文件了，可以尝试重新下载代码，编译看看能不能行，如果重新编译代码成功的话，可以对比一下你们改动什么了

**Comment by LaeChange** [comment]
> 你们是不是修改什么文件了，可以尝试重新下载代码，编译看看能不能行，如果重新编译代码成功的话，可以对比一下你们改动什么了

没有，除了config.m里面的server_host和server_address我修改为自己的服务器以外，什么东西都没有动过。当然，我也重新clone了一次代码，结果还是一样的问题，我现在怀疑可能是最新版Xcode的问题，我正在下载老版本的Xcode，你们用的哪个版本呢？我这边用同样版本的Xoce试试

**Comment by heavyrain2012** [comment]
我们就是用的最新版本的xcode啊，代码下载下来后什么都不改能编译过去吗

**Comment by heavyrain2012** [comment]
对wfclient和wfuikit分别点运行，运行时有个脚本会把wfuikit工程的音视频库copy到wfchat工程下

**Comment by LaeChange** [comment]
> 对wfclient和wfuikit分别点运行，运行时有个脚本会把wfuikit Engineering的音视频库复制到wfchat工程下

还是不行  我什么配置都没有改动的情况下，编译顺序是client->uikit->chat,但是不管是用build还是用build for running到了chat这里就会报这个错误。

**Comment by LaeChange** [comment]
> 对wfclient和wfuikit分别点运行，运行时有个脚本会把wfuikit Engineering的音视频库复制到wfchat工程下
![image](https://user-images.githubusercontent.com/46321649/71790839-8211e200-306d-11ea-958f-bbc6f32833f3.png)

**Comment by LaeChange** [comment]
> 我们就是用的最新版本的xcode啊，代码下载下来后什么都不改能编译过去吗

**Comment by LaeChange** [comment]
> > 对wfclient和wfuikit分别点运行，运行时有个脚本会把wfuikit Engineering的音视频库复制到wfchat工程下
> 
> 还是不行我什么配置都没有介入的情况下，编译顺序是client-> uikit->聊天，但是无论是用build还是用build运行都到了聊天这里就会报这个错误。

**Comment by LaeChange** [comment]
> 我们就是用的最新版本的xcode啊，代码下载下来后什么都不改能编译过去吗

![06bd373474663aaa981b68a95281737](https://user-images.githubusercontent.com/46321649/71863877-3c225000-3139-11ea-912f-268ca592ff5f.jpg)

**Comment by heavyrain2012** [comment]
能的

**Comment by heavyrain2012** [comment]
由于没有新信息补充，issue关闭，如果有信息补充，请reopen或新提一个issue，谢谢
