### ISSUE TITLE
ios 13.3 iphone 8P, 运行时崩溃，怎么解决？

### ISSUE THREAD

**Issue by BBS-SuperStar** [wildfirechat/ios-chat#117]
<img width="488" alt="2E675654-0D27-4484-91EE-FF7190F3B978" src="https://user-images.githubusercontent.com/45873189/72229776-2b1b8800-35ec-11ea-8e28-57f86a4ffc80.png">
<img width="948" alt="573F21D4-0DEB-421A-85EF-8AC1145313CF" src="https://user-images.githubusercontent.com/45873189/72229777-2b1b8800-35ec-11ea-977f-02be93be4002.png">

**Comment by heavyrain2012** [comment]
这个调用栈没有跟野火IM相关的，可能跟野火IM没有什么关系，可以看一下应用上是不是还装有别的sdk，是不是他们造成的问题
