### ISSUE TITLE
ios聊天界面，点击隐藏键盘，键盘隐藏后再次自动弹出，非常影响体验

### ISSUE THREAD

**Issue by xiedeacc** [wildfirechat/ios-chat#123]

**Comment by heavyrain2012** [comment]
我們無法復現，請提供視頻錄像

**Comment by xiedeacc** [comment]
怎么发视频给你们

**Comment by xiedeacc** [comment]
![641581063729_ pic_hd](https://user-images.githubusercontent.com/8072296/74012806-156c6900-49c6-11ea-8dbf-8ebf0602de08.jpg)

**Comment by xiedeacc** [comment]
![631581063727_ pic_hd](https://user-images.githubusercontent.com/8072296/74012979-6e3c0180-49c6-11ea-8d97-d7281ccf3ef0.jpg)

**Comment by xiedeacc** [comment]
点红色隐藏后， 又自动弹出

**Comment by lilong7676** [comment]
> 点红色隐藏后， 又自动弹出

同样的问题，请问怎么解决的？

**Comment by heavyrain2012** [comment]
第三方键盘触发的问题，已经适配，请参考 https://github.com/wildfirechat/ios-chat/commit/e83d3a23e58d07ee0b779d4aec14e564a1387089
