### ISSUE TITLE
iOS 在聊天控制器中调用updateMessage方法，UI不会立即刷新

### ISSUE THREAD

**Issue by heyode** [wildfirechat/ios-chat#125]
iOS 在聊天控制器中调用[WFCCIMService.sharedWFCIMService updateMessage:model.message.messageId content:redBagMsg];方法，UI不会立即刷新。
一定要退出当前控制器，重新进，才能看到新UI.

**Comment by heyode** [comment]
如果修复，请单独发一个版本，告诉我改了哪些类。我本地已经改了很多代码，这样方便替换，灰常感谢。

**Comment by heavyrain2012** [comment]
因为你只改了数据库里的数据，内存中的数据不知道没有修改，UI也没有刷新，所以就无法更新。
解决办法，更新完数据库后，修改model里的message，然后刷新对应的cell

**Comment by heyode** [comment]
好的，感谢
