### ISSUE TITLE
mars::stn::setAuthInfo

### ISSUE THREAD

**Issue by qhd** [wildfirechat/ios-chat#126]
<img width="1408" alt="屏幕快照 2020-02-08 下午3 01 44" src="https://user-images.githubusercontent.com/1835538/75109807-f75b6580-5661-11ea-9b2e-7197dcd4f789.png">

**Comment by heavyrain2012** [comment]
sqlite有一定概率会损坏，很难避免，需要看问题出现的概率。请问能统计处崩溃的概率吗

**Comment by heavyrain2012** [comment]
看错误发生在连接的时候，有没有可能多次调用connect，或者切换用户的时候没有先disconnect

**Comment by qhd** [comment]
> 看错误发生在连接的时候，有没有可能多次调用connect，或者切换用户的时候没有先disconnect

有可能两次调用了 connect，这个会造成闪退吗

**Comment by heavyrain2012** [comment]
有可能，connect时会打开数据库，并保存这个连接，后续的所有数据库操作都会通过这个连接进行。如果两次connect，第二次打开数据库时，有可能有线程正在执行数据库操作，可能会出现问题。

最近的代码提交了保护代码，wfclient中在connect时如果发现已经connect过了会直接返回。请避免没有disconnect的情况下再次调用connect

**Comment by heavyrain2012** [comment]
如果新情况补充，请重新打开本issue，或者新提个issue，本issue关闭
