### ISSUE TITLE
接入iCloud driver

### ISSUE THREAD

**Issue by heavyrain2012** [wildfirechat/ios-chat#127]
![WechatIMG17](https://user-images.githubusercontent.com/34463389/75212022-a2823100-57c0-11ea-9fbe-b32ad47c07fb.jpeg)

**Comment by ManBuTianYa** [comment]
这个功能是已经完善了吗?

**Comment by ManBuTianYa** [comment]
> 还没有，我们太忙顾不上，如果你们要是已经添加了，可以给我们提个PR

我在模拟器的时候发送文件能正常发送， 但是在手机上的时候就崩溃了。 是因为文件地址不对吗？

**Comment by heavyrain2012** [comment]
可以提个pr给我们，我们抽空调一下

**Comment by ManBuTianYa** [comment]
> 可以提个pr给我们，我们抽空调一下

已提交！

**Comment by heavyrain2012** [comment]
已更新，请更新最新代码验证

**Comment by ManBuTianYa** [comment]
> 已更新，请更新最新代码验证

好的  非常感谢
