### ISSUE TITLE
iOS 个人和群聊的聊天记录会被清空

### ISSUE THREAD

**Issue by iOS-Kel** [wildfirechat/ios-chat#128]
iOS 据我们的应用的用户反应，他们使用聊天功能存在聊天记录莫名清空的问题，请问你们有发现这个问题吗？如何解决？
![261582681549_ pic](https://user-images.githubusercontent.com/22427032/75336358-f296eb80-58c5-11ea-81b2-b764a2283ae8.jpg)

**Comment by heavyrain2012** [comment]
导致问题被清空可能有以下原因：
1，clientId发生变更，一般是Xcode运行和appstore上版本覆盖安装时发生，客户端重建了数据库，导致表现消息被清空。
2，用户logout再次登录，logout时disconnect传true，这样会清除掉session，再登录时就表现消息被清空。
3，数据库损坏，在某些条件下，sqlite数据库会损坏，协议栈会重建数据库导致消息被清空。
4，半年以前的有过一段版本服务器session保存不成功，当IM服务重启后用户被踢下线，重新登录导致数据为空。

对策：
1. 请跟客户核实情况并推测是那种原因，想办法抓到用户日志。
2. 升级服务器到最新，升级客户端到最新。
3. 服务器配置有同步历史消息功能，打开这个功能，当用户数据被清空时能够同步最近1000条消息

**Comment by heavyrain2012** [comment]
由於沒有信息補充，問題關閉。如果有問題需要補充請reopen或者重新提個issue
