### ISSUE TITLE
可否提供React-native相关的原生sdk桥接配置.m以及.h文件?

### ISSUE THREAD

**Issue by wlfcss** [wildfirechat/ios-chat#129]
如题，作为rn开发者对接口有些头痛
可否提供React-native相关的原生sdk桥接配置.m以及.h文件?

**Comment by heavyrain2012** [comment]
我们只提供原生应用的程序，在iOS平台上就是Objective C语言的代码。
如果需要进行跨平台方案的封装，请在wfclient功能库上层进行封装，wfclient功能库源码是开放的。理论上封装wfclient应该没有阻碍
