### ISSUE TITLE
为什么下载这么慢

### ISSUE THREAD

**Issue by YXYCareFree** [wildfirechat/ios-chat#130]
一直clone不下来，下载很慢然后失败

**Comment by imndx** [comment]
你好，我们在码云上也有同步库，可选择从码云下载，但是码云上的更新会稍微慢一些。
[码云ios-chat](https://gitee.com/wildfirechat/ios-chat)。

**Comment by YXYCareFree** [comment]
> 你好，我们在码云上也有同步库，可选择从码云下载，但是码云上的更新会稍微慢一些。
> [码云ios-chat](https://gitee.com/wildfirechat/ios-chat)。

码云上的也不行... 
yangxiaoyudeMacBook-Pro% git clone https://gitee.com/wildfirechat/ios-chat.git
Cloning into 'ios-chat'...
remote: Enumerating objects: 5024, done.
remote: Counting objects: 100% (5024/5024), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: protocol error: bad pack header

设置了http.postBuffer也不行。 直接在码云下载zip也不行。
