### ISSUE TITLE
码云也无法下载

### ISSUE THREAD

**Issue by YXYCareFree** [wildfirechat/ios-chat#131]
你好，我们在码云上也有同步库，可选择从码云下载，但是码云上的更新会稍微慢一些。
[码云ios-chat](https://gitee.com/wildfirechat/ios-chat)。

_Originally posted by @imndx in https://github.com/wildfirechat/ios-chat/issues/130#issuecomment-593247371_

码云上的也不行...
yangxiaoyudeMacBook-Pro% git clone https://gitee.com/wildfirechat/ios-chat.git
Cloning into 'ios-chat'...
remote: Enumerating objects: 5024, done.
remote: Counting objects: 100% (5024/5024), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: protocol error: bad pack header

设置了http.postBuffer也不行。 直接在码云下载zip也不行。

**Comment by heavyrain2012** [comment]
码云在国内，如果一直不行真得考虑换个宽带了。
一般情况下早上与github的网络比较好，可以试试在早上试用git clone的方法下载代码试试
