### ISSUE TITLE
多人音视频的几个问题

### ISSUE THREAD

**Issue by heavyrain2012** [wildfirechat/ios-chat#133]
1、语音通话时静音功能不稳定，暂不清楚是底层问题还是我们的处理有问题
2、发起群聊通话后，对方未接通的几个状态：对方正忙（对方拒绝接听），对方忙线中（对方正在通话中），对方无应答（对方在收到提醒的时间内未接听）
3、群聊通话时，在讲话的成员，其对应图标内有“正在说话”的状态显示

**Comment by heavyrain2012** [comment]
1、语音通话时静音功能不稳定，暂不清楚是底层问题还是我们的处理有问题

iOS 端在通话接通前，麦克风和扬声器的操作都是无效的，在最新代码中当未接通时屏蔽掉这两个按钮

2、发起群聊通话后，对方未接通的几个状态：对方正忙（对方拒绝接听），对方忙线中（对方正在通话中），对方无应答（对方在收到提醒的时间内未接听）

在callsession的回调中，有如下方法，带有通话结束原因
```
- (void)didParticipantLeft:(NSString *)userId withReason:(WFAVCallEndReason)reason;
```

3、群聊通话时，在讲话的成员，其对应图标内有“正在说话”的状态显示

在最新代码上已经加上了对应回调
```
- (void)didReportAudioVolume:(NSInteger)volumn ofUser:(NSString *_Nonnull)userId;
```

**Comment by heavyrain2012** [comment]
最新代码已经加上了“谁在说话”功能

**Comment by yeshengwu** [comment]
视频或者语音通话时静音按钮点击后进入小窗口，然后返回通话界面静音按钮状态丢失。
代码上看是 小窗口重新拉起通话界面是新的通话界面，在点击缩小到小窗口时没有把 audioMuted状态带入导致返回新的通话界面 audioMuted状态丢失。

**Comment by heavyrain2012** [comment]
最新版本已解决，请验证

**Comment by yeshengwu** [comment]
> 最新版本已解决，请验证

已经验证，没问题。你们是通过session中，库中改的，我们只能ui层动动手脚，哈哈。

**Comment by yeshengwu** [comment]
iOS端打给Android端，对方未接听。

**Comment by heavyrain2012** [comment]
问题都应该已经解决了，此issue先关了吧，如果还有问题，请reopen或者新提一个issue
