### ISSUE TITLE
多人音频通话，ios设备接通状态下，可能会出现没有声音的情况

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/ios-chat#135]
2个android3个ios设备进行语音通话，所有人都已接通，但是通话过程中某个ios设备始终没有声音（非必现，每次没有声音的不是同一个ios设备）

请WF的朋友修复
来自TFD 产品 Charlie

**Comment by heavyrain2012** [comment]
是说这个ios的声音别人端听不到？还是说这个iOS听不到别人的？

**Comment by Charlie191011** [comment]
接通后，这个IOS连接显示正常，正常计时，但是听不见别人的声音，他说话别人能听到。

**Comment by heavyrain2012** [comment]
多人音视频是p2p的，每个人之间互相连接的，如果别人能听到他的声音，那就是连接建立没有问题，只可能出现在声音播放上了，请切换扬声器试试是不是能够恢复，另外想办法帮我们抓一下日志，我们来分析一下。我们用了几台手机测试了多次，都没有能够复现问题。。。

**Comment by Charlie191011** [comment]
更正一下，场景是人多语音群聊中（有安卓也有ios加入），某个手机没有声音，听不见别人，别人也听不见他。但是连接页面显示正常，计时正常。（出现问题的设备不是固定某个设备）
该问题安卓和iOS都出现过（非必现）

**Comment by heavyrain2012** [comment]
可以给想办法给我们抓个日志吗

**Comment by yeshengwu** [comment]
现在demo好像不支持多人通话哦。哪里有入口？

**Comment by Charlie191011** [comment]
> 现在demo好像不支持多人通话哦。哪里有入口？

不是demo，表述错了。
是之前你们多人音视频的一个**试用包**，这个问题一直都存在，包括现在我们接入的最新的试用包

**Comment by heavyrain2012** [comment]
多人音视频是收费的，可以看一下文档首页

**Comment by heavyrain2012** [comment]
这个最近再帮我们测试测试吧，只用iOS的手机，看看出现的概率有多大@Charlie191011
