### ISSUE TITLE
多人语音通话，通话用户陆续退出通话，最后剩一人时，该用户还处于通话转态，通话界面没有自动关闭

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/ios-chat#136]
【偶发】多人语音通话时，通话成员退出只一个人时，该用户还保持通话转态，通话界面没有自动关闭

**Comment by heavyrain2012** [comment]
请确认是那个平台的问题，可以使用只有iOS，或只有android的手机进行测试

**Comment by Charlie191011** [comment]
经过测试验证，我们的产品在iOS端测试时出现过（偶发），安卓暂未复现。但是用你们之前的安卓demo在测试的时候也出现过同样问题。

**Comment by Charlie191011** [comment]
待验证

**Comment by Charlie191011** [comment]
未复现，关闭
