### ISSUE TITLE
ios端，特定情况下添加好友，发送的好友申请内容昵称显示null

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/ios-chat#137]
1、新注册的用户，向其他用户发送好友请求时，发送的申请内容中昵称为null
2、非新用户，更换其他设备登录（设备没有该账号的登录历史），向其他用户发送好友请求时，发送的申请内容中昵称为null

**Comment by heavyrain2012** [comment]
请查看最新提交代码

**Comment by Charlie191011** [comment]
已修复，关闭
