### ISSUE TITLE
ios的视频通话无切换屏幕功能

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/ios-chat#138]
ios视频通话，缺失切换我方或对方画面为主画面的功能按钮。

**Comment by heavyrain2012** [comment]
点击视频小窗口即可切换为主画面

**Comment by Charlie191011** [comment]
> 点击视频小窗口即可切换为主画面
iOS的点击没有反应，安卓的可以正常切换对方和自己的画面

**Comment by heavyrain2012** [comment]
UI问题，代码已更新

**Comment by yeshengwu** [comment]
已经同步最新代码。但是 ios 11 pro 上 发起方接通视频后点击切换屏幕，本地小窗口画面切换成对方视频正常，但是本地画面全屏后内容只在左上角了。截图如下：[http://prnt.sc/rjehhp](url)

**Comment by heavyrain2012** [comment]
是不是跟手机有关，我这边有iphone8，iphone6s都是正常的，你们试试

**Comment by heavyrain2012** [comment]
在单人音视频发现了这个问题，当呼出方切换大小窗会出现这个问题。这个问题已经修改提交。
请问多人音视频也有这个问题吗？

**Comment by heavyrain2012** [comment]
如果有，请给我们录个录像，谢谢

**Comment by Charlie191011** [comment]
单人视频通话，主叫和被叫方的主次画面切换功能都不能生效

**Comment by yeshengwu** [comment]
> 单人视频通话，主叫和被叫方的主次画面切换功能都不能生效

我更新了最新代码，单人视频切换通话，切换画面没有问题。在iphone 7 sdk 10.0 上。
