### ISSUE TITLE
关于ipv6支持以及上架appstore问题

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#142]
请问 要支持ipv6上架，客户端需要做什么？服务端需要做什么？
目前客户端im服务器地址我们采用的是域名。

**Comment by heavyrain2012** [comment]
我们已经支持ipv6，可以上架苹果商店。服务器端可以只用ipv4，苹果对此并没有要求。

**Comment by yeshengwu** [comment]
> 我们已经支持ipv6，可以上架苹果商店。服务器端可以只用ipv4，苹果对此并没有要求。

我看苹果官网 https://developer.apple.com/cn/support/ipv6/ 服务器更新 注：当然，最终还需更新您的服务器以支持 IPv6。

**Comment by heavyrain2012** [comment]
如果您的服务器在更广的互联网上运行，无需立刻更新服务器。纯 IPv6 设备可以通过 DNS64/NAT64 访问服务器。

服务器可以只提供ipv4的服务，因为纯 IPv6 设备的请求会经过IPv6/IPv4网关转换为ipv4请求。已经很多人上线了，这里不用担心
