### ISSUE TITLE
语音电话按缩小按钮后，显示的是一个黑块。 

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#145]
看代码是未实现该功能，相关音频判断逻辑和ui展示的都被注释了，android版有做相关判断和处理。

**Comment by yeshengwu** [comment]
FloatWindow 415行。  didChangeMode 根据是否 isAudioOnly重新设置 floatButton的 image可以显示不同icon

**Comment by heavyrain2012** [comment]
已修改，请参考
