### ISSUE TITLE
在聊天窗口拉起软键盘的情况下，收到视频通话邀请后，在视频通话邀请窗口中也会显示软键盘

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#147]
[结果]

1. 在视频通话邀请窗口中也会显示软键盘，导致处理不了视频通话请求（接受/拒绝）

**Comment by yeshengwu** [comment]
初步解决方案是：AppDelegate收到来电回调时，发送通知，然后在消息聊天窗口处理这个通知。将输入框收起，不管是显示表情还是选位置的地方，都统一收起输入框（ChatInputBar）

**Comment by heavyrain2012** [comment]
这个在demo上没有问题吧，我测试了一下没有复现

**Comment by yeshengwu** [comment]
> 这个在demo上没有问题吧，我测试了一下没有复现

我在iPhone 7上 iOS sdk 10. 必现

**Comment by heavyrain2012** [comment]
使用我们提供的demo，然后给我们录像看一下，谢谢

**Comment by yeshengwu** [comment]
> 使用我们提供的demo，然后给我们录像看一下，谢谢

http://bbs.wildfirechat.cn/attach-download-67.htm   请查看。

**Comment by heavyrain2012** [comment]
> > 这个在demo上没有问题吧，我测试了一下没有复现
> 
> 我在iPhone 7上 iOS sdk 10. 必现

是系统版本是iOS 10吗，最新版的iOS版本上有这个问题吗

**Comment by yeshengwu** [comment]
iPhone 7 。系统版本 10.3.3。最新13手机没测试，估计同样有问题。
我已经按照我自己上面方案先处理了聊天窗口的 （ChatInputBar） 收到通话请求调用 onResetKeyboard

**Comment by heavyrain2012** [comment]
iOS10的问题， WFCUMessageListViewController.mm viewWillDisappear函数，在弹出通话界面的时候居然没有被调用。。。

我们还是针对iOS10做了兼融，请更新最新代码
