### ISSUE TITLE
关于项目中的Callkit framework. PushKit framework问题

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#149]
看推送文档：
 https://github.com/wildfirechat/push_server/blob/master/config/apns.properties 
”苹果要求使用voip推送必须使用callkit，不然会停掉voip推送。由于大陆政策，callkit被禁止，所以在大陆无法使用voip推送。“

那么是否可以移除项目中的 Callkit framework. PushKit framework.。 当我移除CallKit 整个工程报错了：
PushKit apps that use VoIP push must link either CallKit or IncomingCallNotifications frameworks.

- 是否要移除 CallKit加 PushKit而不会影响推送功能？

- 还是保留去上架是否会被打回说使用了CallKit? 我理解是应该不被打回因为推送服务是关闭了VoIP推送走的普通文本消息推送，理解是否正确？

- 还是移除CallKit加 PushKit 并且去掉 Background Mode 中的 Voice Over IP？

目前我需要语音视频支持开关是开的，移除 CallKit加 PushKit后工程无法启动，报上面的错误。 @ @heavyrain2012

**Comment by heavyrain2012** [comment]
请查看常见问题iOS部分

**Comment by yeshengwu** [comment]
http://docs.wildfirechat.cn/faq/ios.html  
“0.0.9. Q. 国内不允许使用CallKit功能怎么办？
A. 苹果不允许不使用CallKit功能的应用使用Voip推送，针对这个问题的处理很简单，那就是使用普通推送呗。由于SDK中对CallKit.framework有依赖，所以打包必须带上这个依赖。Appstore上架是没有问题的。” 
谢谢你们快速回复，我之前看了这个部分但是又忘了。
