### ISSUE TITLE
查找聊天记录无效果

### ISSUE THREAD

**Issue by 794341379** [wildfirechat/ios-chat#15]
在最新的iOS的代码中，查找聊天记录搜索无效，而AppStore上的版本有搜索消息

**Comment by 794341379** [comment]
经回滚版本，测试搜索功能，在最新的一次update proto后，现在的搜索聊天内容功能失效，希望大佬修复一下😝

**Comment by heavyrain2012** [comment]
协议栈内部处理错误，已经修复，请更新到最新代码验证

**Comment by 794341379** [comment]
谢谢大佬百忙之中的反馈，新版的协议栈已经拉去到最新的，searchMessage也能查询到搜索的内容，但是又发现一个新的问题：
在搜索出的每个message对象中，每个message的conversation.target 均为0，在后续的操作中，无法使用target。
![F8E763D7-728B-4D2A-9A6B-2C1C3609675E](https://user-images.githubusercontent.com/13906299/59825350-614e9d00-9366-11e9-900a-129a7ec624e5.png)

**Comment by 794341379** [comment]
已处理
