### ISSUE TITLE
您好，请问可以出一个自定义消息的示例吗？

### ISSUE THREAD

**Issue by LYluyu** [wildfirechat/ios-chat#152]
您好，请问可以出一个自定义消息的示例吗？

**Comment by heavyrain2012** [comment]
所有关于消息的代码都是开源的，你只需要找到一种类似消息，然后搜索所有的代码，看看在哪里试用的就可以，比如搜索文本消息或者搜索图片消息

**Comment by LYluyu** [comment]
您好，我参照了发送图片消息的，首先自定义继承于WFCCMessagePayload的类，添加了我需要的属性；然后自定义继承于WFCCMessageContent的自定义消息类。重写了encode和decode方法。但是发现消息能够发送成功了，从会话列表点击进去发现信息无法回显我需要的数据。如图所示：

![image](https://user-images.githubusercontent.com/16254669/77866045-e2c34c00-7263-11ea-8a64-87290b6a44b5.png)
![image](https://user-images.githubusercontent.com/16254669/77866041-de972e80-7263-11ea-8367-8183e36fc20a.png)
![image](https://user-images.githubusercontent.com/16254669/77866062-f4a4ef00-7263-11ea-9746-1157dd1174ec.png)
