### ISSUE TITLE
视频通话时候蓝牙耳机导致的问题

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#154]
连接蓝牙耳机时，拨打视频电话，蓝牙耳机中有拨号音，对方接听后声音被切到外放，重新连接蓝牙耳机声音切换至蓝牙耳机。点击缩放视频缩小窗口，再次点击视频窗口进入视频聊天界面，声音会被再次从蓝牙耳机切至外放。语音通话没问题

**Comment by heavyrain2012** [comment]
最新音视频库已经解决，请用最新代码验证
