### ISSUE TITLE
iphonex下聊天界面显示问题

### ISSUE THREAD

**Issue by YonYou20** [wildfirechat/ios-chat#155]
iphonex下，如果聊天记录超过一屏，进入聊天页面点击输入框时，键盘会覆盖聊天记录，而不是将聊天记录往上顶。
![3935A656DFBF233FF8CB91CA9E0032C5](https://user-images.githubusercontent.com/31881642/78095317-3327de80-7409-11ea-9f50-b1a51af79098.png)

**Comment by heavyrain2012** [comment]
其它手机怎么，只有这个手机会这样吗

**Comment by heavyrain2012** [comment]
由于手上没有iphonex手机，用模拟器测试没有发现问题！
请确认，用我们提供的demo不做任何修改看看是不是有同样的问题？

**Comment by uft-yonyou** [comment]
使用的是你们提供的体验版本，目前只在iphonex下发现这个问题。

**Comment by heavyrain2012** [comment]
请提供如下信息：
1，把代码更新到最新，测试是否还有该问题？
2，是模拟器还是真机？
3，手机的系统版本？

**Comment by YYT-YONYOU** [comment]
最新代码还是会有这个问题。使用的是真机，系统是13.4.1 iphonex

**Comment by heavyrain2012** [comment]
这种问题是UI的问题，如果还有的话你们可以自己修改一下给我们提个PR，问题先关了吧
