### ISSUE TITLE
WFChatClient 依赖的 mars 不支持arm7

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#156]
是否能够重新编译新的mars 支持arm7 arm7s

**Comment by yeshengwu** [comment]
https://docs.wildfirechat.cn/faq/ios.html  0.0.8. Q. 为什么SDK不支持armv7架构了？
A. 从iphone5s起，架构已经是arm64了。目前iphone5及之前的设备基本上没有了，可以不用再支持armv7架构了。省去armv7架构可以有效的减少sdk及软件包的大小，请移除armv7架构的支持。

**Comment by LengYi** [comment]
mars 你们在开源的基础上自己做了修改，能提供支持armv7，arm7s的支持吗

**Comment by heavyrain2012** [comment]
自己修改的我们就不做技术支持了
