### ISSUE TITLE
最新版本不支持arm64吗？

### ISSUE THREAD

**Issue by liwyan** [wildfirechat/ios-chat#157]
最新版本build的时候会提示arm64不支持。
另外把arm64暂时去掉的话，最后好像打不开项目，不知道是我这边的问题，还是项目的问题。
提示这个You don’t have permission.
To view or change permissions, select the item in the Finder and choose File > Get Info.

**Comment by liwyan** [comment]
我又下载了1.0.16的release使用是正常的。如果是从最新的里面下载出来是有问题的

**Comment by heavyrain2012** [comment]
我用最新的代码是可以编译过的，你清理下编译缓存再试试？另外需要使用最新的xcode，检查一下您的xcode版本是不是最新的

**Comment by liwyan** [comment]
xcode不是最新版本，我升级下试试。
