### ISSUE TITLE
channel接收到消息后 unreadcount.unread为0

### ISSUE THREAD

**Issue by myhighland** [wildfirechat/ios-chat#158]

**Comment by heavyrain2012** [comment]
在demo上没有测试出来，请确认问题复现步骤
我们的测试方法如下：
账户A创建一个频道，账户B订阅这个频道，1 A在频道内发送消息，B在会话列表界面看到新消息，并有未读数。A在会话列表界面时，B回复消息，A能看到新消息和未读数。

**Comment by myhighland** [comment]
从服务端发出的频道消息收到后 状态直接置为了readed 但是通过客户端发出的消息收到后还是unread状态

**Comment by heavyrain2012** [comment]
还是不明白什么问题，请详细描述操作步骤，修改的内容，预期的结果和实际的表现
