### ISSUE TITLE
iOS 聊天消息时间错误问题

### ISSUE THREAD

**Issue by iOS-Kel** [wildfirechat/ios-chat#160]
想问下，你们拉取历史消失到底有没有限制呀？难道全部都能拉回来？
我拉着拉着就发现你们一个bug了，2019年11月11日的消息，再拉取旧数据就变成昨天了，看图片
![IMG_2133](https://user-images.githubusercontent.com/22427032/78970728-9669ed00-7b3c-11ea-82fb-9a00361c8bbf.PNG)

**Comment by heavyrain2012** [comment]
时间计算错误，已修正，请更新最新代码验证
