### ISSUE TITLE
ios 清除会话消息问题

### ISSUE THREAD

**Issue by iOS-Kel** [wildfirechat/ios-chat#161]
iOS 清空聊天记录之后，返回聊天界面，下拉加载又加载出来了，这清空聊天记录的功能没作用呀

**Comment by heavyrain2012** [comment]
请参考 https://docs.wildfirechat.cn/faq/general.html 问题21

**Comment by helcyonfu** [comment]
配置文件中找到message.roaming和message.remote_history_message
这两个参数在ios配置文件中没看到
