### ISSUE TITLE
mars 内存泄漏

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#163]
SDK使用的还是旧版的mars，有内存泄漏，你们考虑升级到最新的吗？最新的有修复了 
https://github.com/Tencent/mars/issues/730
https://github.com/Tencent/mars/commit/e5fd05b032b26b4a2b7007d0d5aad63fe69acf8c

**Comment by heavyrain2012** [comment]
最近微信更新有些多，等他们稳定一些我们再进行升级

**Comment by heavyrain2012** [comment]
这个问题在今天的提交的版本中已经修复，谢谢您的信息

**Comment by lengqingfeng** [comment]
void mars_boost::signals2::detail::signal1_impl<void, bool, mars_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, mars_boost::function<void (bool)>, mars_boost::function<void (mars_boost::signals2::connection const&, bool)>, mars_boost::signals2::mutex>::do_disconnect<mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > >(mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > const&, mpl_::bool_<false>) + 80
--
1 WFChatClient | void mars_boost::signals2::detail::signal1_impl<void, bool, mars_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, mars_boost::function<void (bool)>, mars_boost::function<void (mars_boost::signals2::connection const&, bool)>, mars_boost::signals2::mutex>::do_disconnect<mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > >(mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > const&, mpl_::bool_<false>) + 68
2 WFChatClient | mars::stn::NetCore::~NetCore() + 344
3 WFChatClient | mars::stn::NetCore::~NetCore() + 12
4 WFChatClient | MessageQueue::__AsyncInvokeHandler(MessageQueue::MessagePost_t const&, MessageQueue::Message&) + 128
5 WFChatClient | MessageQueue::RunLoop::Run() + 2584
6 WFChatClient | MessageQueue::MessageQueueCreater::__ThreadRunloop() + 124
7 WFChatClient | Thread::start_routine(void*) + 76
8 libsystem_pthread.dylib | _pthread_start + 124
