### ISSUE TITLE
编译WFChatClient出现Undefined symbol: ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by LYluyu** [wildfirechat/ios-chat#166]
![image](https://user-images.githubusercontent.com/16254669/79557962-07c61480-80d6-11ea-946c-5b3b1ea0582a.png)

**Comment by heavyrain2012** [comment]
xcode升级到最新就好了

**Comment by zhao520wei** [comment]
请问一下，你们只支持Xcode11.5版本吗？如果其他Xcode版本,我这边怎么修改才能够编译了？我目前Xcode11.3和10.1都报这个错。  @heavyrain2012

**Comment by heavyrain2012** [comment]
是的，只支持最新版本的xcode，请升级xcode

**Comment by zhao520wei** [comment]
> 是的，只支持最新版本的xcode，请升级xcode

再问一下，我看上周最新版本11.5了，你指的最新版本是这个吗还是11.4.1呢？还是那个Xcode版本以上就可以不报这个错误了？

**Comment by heavyrain2012** [comment]
我们本地的是11.5了，旧的没有办法验证

**Comment by zhao520wei** [comment]
好的，谢谢您

**Comment by AlleniCode** [comment]
@heavyrain2012 Xcode 12.4 和 12.5 编译都报这个错，怎么解决啊？Thanks♪(･ω･)ﾉ
