### ISSUE TITLE
关于长短链接和本地数据库加密

### ISSUE THREAD

**Issue by LiuGanQQQ** [wildfirechat/ios-chat#169]
请教一下咱们的长短链接和本地数据库的加密方式~

**Comment by heavyrain2012** [comment]
长短链接是微信mars的特性，关于这方面的内容请参考微信mars的介绍。
数据库加密使用的sqlcipher，请参考微信开源项目WCDB

**Comment by LiuGanQQQ** [comment]
感谢回复
