### ISSUE TITLE
连接蓝牙耳机后，语音信息还是外放

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#170]
连接蓝牙耳机后，所有的应用声音应该都转接入到耳机上

**Comment by hanyh2004** [comment]
我也碰到了

**Comment by yeshengwu** [comment]
MessageListViewController.m 解决如下：      @hanyh2004 @heavyrain2012 
 AVAudioSession *session = [AVAudioSession sharedInstance];
       [session setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionAllowBluetooth | AVAudioSessionCategoryOptionDefaultToSpeaker error:nil];

**Comment by heavyrain2012** [comment]
感谢您提供的信息，已经提交到主干

**Comment by yeshengwu** [comment]
不好意思，提交漏了一行。
