### ISSUE TITLE
App Store发布上架报错

### ISSUE THREAD

**Issue by kirishimamoe** [wildfirechat/ios-chat#172]
编译上传到App Store後收到报错电邮

> ITMS-90338: Non-public API usage - The app references non-public selectors in AppName: hideAnimated:, initWithParentView:, serializer, showAnimated:, themeType. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Xcode 版本11.4.1

**Comment by yeshengwu** [comment]
最新代码我看有 提交： 1, 添加pc下线功能。2，修改themeType为colorType，避免上架问题  是不是最新代码？

**Comment by kirishimamoe** [comment]
最新代码WFChatClient PC下线功能部分出错无法编译，我先再尝试一下稍後再发issue。

**Comment by kirishimamoe** [comment]
用新的代码编译成功了但再次发布後收到相同的错误，相关selectors是以下几个：
> colorType, hideAnimated:, initWithParentView:, serializer, setColorType:, showAnimated:

**Comment by heavyrain2012** [comment]
colorType, initWithParentView:是我们代码中的，其它几个有 MBProgressHUD AFNetworking 的，这些都在源代码中，暂时可以逐个找到并修改，然后提交AppStore

我们需要等一下，等这两个库官方修改后再修改

**Comment by yeshengwu** [comment]
https://github.com/wildfirechat/ios-chat/commit/05a51bf1a4b048dafdbb524ddc2604e24d1b985b  更新音视频SDK，解决视频发起方切换大小屏错误的问题 committed on 25 Mar 

我基于上面提交的版本上架成功了，这个版本中也应该是有 MBProgressHUD AFNetworking 的，为何能上架成功？所以有 MBProgressHUD AFNetworking 的我认为不用改。

**Comment by kirishimamoe** [comment]
刚刚修改colorType及initWithParentView後再提交就没有出现Non-public API usage的问题，目前正等待处理中，谢谢两位。

**Comment by yeshengwu** [comment]
你很有礼貌，不客气。

**Comment by heavyrain2012** [comment]
@kirishimamoe 多谢提供的信息，最新版本改了这两个函数名，希望这次能避免私有api的问题。。。
