### ISSUE TITLE
iOS端打给Android端，Android未接听，iOS端显示状态不对

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#174]
环境：
iOS代码版本：https://github.com/wildfirechat/ios-chat/tree/2d86f5061ee38e93bdf684af12d92bb82b0d755c update av engine

@heavyrain2012
heavyrain2012 committed 25 days ago

Android版本：https://github.com/wildfirechat/android-chat/tree/4bf71b9b3589a716673fe3d5b1ae01a810284c5d 单人会话已读回执
@siqiii
siqiii committed on 27 Mar

iOS端打给Android端，对方未接听。iOS端我看 消息列表中该 CallStartMessageContent的 staus是 5，表示RemoteHangup。 
这个状态返回不对，应该返回的是 对方未接听的状态码。 @heavyrain2012

**Comment by heavyrain2012** [comment]
社区版实现比较简单，无法支持这么详细的状态
