### ISSUE TITLE
xcode 编译直接报错

### ISSUE THREAD

**Issue by jackchan1314** [wildfirechat/ios-chat#175]
ld: warning: directory not found for option '-F/Users/chenjia/Desktop/ios-chat-master/wfclient/WFChatClient/Frameworks'
ld: warning: directory not found for option '-F/Users/chenjia/Desktop/ios-chat-master/wfclient/Frameworks'
Undefined symbols for architecture arm64:
  "___darwin_check_fd_set_overflow", referenced from:
      socket_gethostbyname(char const*, socket_ipinfo_t*, int, char const*, NetCheckTrafficMonitor*) in mars(dnsquery.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jackchan1314** [comment]
vx：13950317791 sos

**Comment by heavyrain2012** [comment]
请参考 #166
