### ISSUE TITLE
发送视频失败

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#176]
视频发送看日志发送前压缩，上传都生成了正常的url。
有些视频发送成功，有些视频发送失败，很奇怪。
但是WFCUMessageListViewController
发送消息
 - (WFCCMessage *)send:(WFCCConversation *)conversation
              content:(WFCCMessageContent *)content
               toUsers:(NSArray<NSString *> *)toUsers
       expireDuration:(int)expireDuration
              success:(void(^)(long long messageUid, long long timestamp))successBlock
                error:(void(^)(int error_code))errorBlock 
这个回调走的是失败的回调，错误码包括：
send message fail(54)
send message fail(-10090)

所以不知道 这个错误码什么意思。

环境：
git 2d86f5061ee38e93bdf684af12d92bb82b0d755c
Author: heavyrain2012 <heavyrain.lee@gmail.com>
Date:   Thu Apr 2 22:37:49 2020 +0800

    update av engine

服务端有同样环境提了相同issue：
https://github.com/wildfirechat/server/issues/201
@heavyrain2012

**Comment by heavyrain2012** [comment]
Duplicate of wildfirechat/server#201

**Comment by yeshengwu** [comment]
send message fail(54)
send message fail(-10090)
所以不知道 这个错误码什么意思。
