### ISSUE TITLE
第一次获取群信息为空

### ISSUE THREAD

**Issue by yzl140520** [wildfirechat/ios-chat#181]
iOS登录成功后，第一次调getGroupInfo(groupId, refresh: false)接口时经常获取不到群信息，要再次获取才能得到群信息，求解

**Comment by heavyrain2012** [comment]
是信息同步机制设计问题，请查看文件常见问题

**Comment by yzl140520** [comment]
> 是信息同步机制设计问题，请查看文件常见问题

文件常见问题没找到呀，麻烦给个具体链接

**Comment by yzl140520** [comment]
> 是信息同步机制设计问题，请查看文件常见问题

你们贴出来的野 火测试群二维码，怎么扫了加不了，是用野火扫的

**Comment by yzl140520** [comment]
> 是信息同步机制设计问题，请查看文件常见问题

还有会话列表，经常同一台设备，这次登录有会话，下次登录就没了，聊天历史消息也经常会丢，没有换设备，也没有删除重装

**Comment by heavyrain2012** [comment]
> > 是信息同步机制设计问题，请查看文件常见问题
> 
> 文件常见问题没找到呀，麻烦给个具体链接

https://docs.wildfirechat.cn/faq/general.html 问题9 



> > 是信息同步机制设计问题，请查看文件常见问题
> 
> 还有会话列表，经常同一台设备，这次登录有会话，下次登录就没了，聊天历史消息也经常会丢，没有换设备，也没有删除重装

什么样的设备，详细的复现步骤是什么，给我们抓一下日志吧

**Comment by yzl140520** [comment]
> > > 是信息同步机制设计问题，请查看文件常见问题
> > 
> > 
> > 文件常见问题没找到呀，麻烦给个具体链接
> 
> https://docs.wildfirechat.cn/faq/general.html 问题9
> 
> > > 是信息同步机制设计问题，请查看文件常见问题
> > 
> > 
> > 还有会话列表，经常同一台设备，这次登录有会话，下次登录就没了，聊天历史消息也经常会丢，没有换设备，也没有删除重装
> 
> 什么样的设备，详细的复现步骤是什么，给我们抓一下日志吧

在断开连接时clearSession传false就不会出现这问题了，clearSession是用来干嘛的

**Comment by lilong7676** [comment]
> > > > 是信息同步机制设计问题，请查看文件常见问题
> > > 
> > > 
> > > 文件常见问题没找到呀，麻烦给个具体链接
> > 
> > 
> > https://docs.wildfirechat.cn/faq/general.html 问题9
> > > > 是信息同步机制设计问题，请查看文件常见问题
> > > 
> > > 
> > > 还有会话列表，经常同一台设备，这次登录有会话，下次登录就没了，聊天历史消息也经常会丢，没有换设备，也没有删除重装
> > 
> > 
> > 什么样的设备，详细的复现步骤是什么，给我们抓一下日志吧
> 
> 在断开连接时clearSession传false就不会出现这问题了，clearSession是用来干嘛的

clearSession传false 好像还是会出问题，消息隔几个小时就会丢。。。
