### ISSUE TITLE
偶尔 崩溃

### ISSUE THREAD

**Issue by lengqingfeng** [wildfirechat/ios-chat#183]
WFChatClient | mars::stn::getEncodedId(bool) + 356
-- | --
1 WFChatClient | mars::stn::getEncodedId(bool) + 208
2 WFChatClient | _ZN4mars3stn3$_18__invokeERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEERKNS2_3mapIS8_S8_NS2_4lessIS8_EENS6_INS2_4pairIS9_S8_EEEEEERK10AutoBufferSM_RSK_PNS0_17shortlink_trackerE + 1284
3 WFChatClient | mars::stn::ShortLink::__RunReadWrite(int, int&, int&, mars::stn::ConnectProfile&) + 2288
4 WFChatClient | mars::stn::ShortLink::__Run() + 2252
5 WFChatClient | Thread::start_routine(void*) + 76
6 libsystem_pthread.dylib | __pthread_body + 132
7 libsystem_pthread.dylib | _pthread_start + 12742240254296116

FChatClient | 0x0000000106409738 EVP_MD_CTX_copy_ex
-- | --
1 WFChatClient | 0x0000000106419bec HMAC_CTX_copy
2 WFChatClient | 0x0000000106419bec HMAC_CTX_copy
3 WFChatClient | 0x0000000106414824 PKCS5_PBKDF2_HMAC
4 WFChatClient | 0x00000001064c94f4 sqlcipher_openssl_kdf
5 WFChatClient | 0x00000001064c79b0 sqlcipher_cipher_ctx_key_derive
6 WFChatClient | 0x00000001064c7410 sqlcipher_codec_key_derive
7 WFChatClient | 0x00000001064edff0 sqlite3Codec
8 WFChatClient | 0x00000001064f919c readDbPage
9 WFChatClient | 0x00000001064f8b80 getPageNormal
10 WFChatClient | 0x00000001064c3214 sqlite3BtreeBeginTrans
11 WFChatClient | 0x0000000106525164 sqlite3InitOne
12 WFChatClient | 0x00000001064dcb78 sqlite3LocateTable
13 WFChatClient | 0x000000010658d79c selectExpander
14 WFChatClient | 0x0000000106583e88 sqlite3WalkSelect
15 WFChatClient | 0x000000010658cafc sqlite3SelectPrep
16 WFChatClient | 0x0000000106554734 sqlite3Select
17 WFChatClient | 0x000000010653b92c yy_reduce
18 WFChatClient | 0x00000001064e40c0 sqlite3RunParser
19 WFChatClient | 0x00000001064e0db4 sqlite3LockAndPrepare
20 WFChatClient | 0x0000000106470358 _ZN4mars3stn19RecyclableStatementC2EP7sqlite3RKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEERi
21 WFChatClient | 0x0000000106474420 _ZN4mars3stn3DB212IsTableExistENSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
22 WFChatClient | 0x0000000106474560 _ZN4mars3stn3DB27UpgradeEv
23 WFChatClient | 0x00000001064aa0a8 _ZN4mars3stn11setAuthInfoERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_
24 WFChatClient | 0x00000001063194d0 -[WFCCNetworkService connect:token:]
25 GJHearlthStore | 0x00000001050062fc 0x0000000104dfc000
26 GJHearlthStore | 0x0000000105058efc 0x0000000104dfc000
27 libdispatch.dylib | 0x00000001ae1a3b9c 0x00000001ae1a1000
28 libdispatch.dylib | 0x00450001ae1a5134 0x00000001ae1a1000
29 libdispatch.dylib | 0x0002ec01ae1b0f50 _dispatch_main_queue_callback_4CF
30 CoreFoundation | 0x001e1c01ae7300fc 0x00000001ae680000
31 CoreFoundation | 0x002aa981ae72ad78 0x00000001ae680000
32 CoreFoundation | 0x004bd201ae72a2e8 CFRunLoopRunSpecific
33 GraphicsServices | 0x0043f681b09debe8 GSEventRunModal
34 UIKitCore | 0x00637581dc46c088 UIApplicationMain
35 GJHearlthStore | 0x002d328104e544d4 0x0000000104dfc000
36 libdyld.dylib | 0x00000001ae1dd050 0x00000001ae1dc000

**Comment by heavyrain2012** [comment]
内容是两个调用栈，是那个调用栈出了问题，还是都出了问题，出的错误是什么？有没有问题复现的规律？如果是用工具抓的，问题出现的比例有多大？

**Comment by heavyrain2012** [comment]
有没有多次调用connect，请查一下代码，都在哪些时机调用了connect

**Comment by lilong7676** [comment]
WFChatClient	
void mars_boost::signals2::detail::signal1_impl<void, bool, mars_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, mars_boost::function<void (bool)>, mars_boost::function<void (mars_boost::signals2::connection const&, bool)>, mars_boost::signals2::mutex>::do_disconnect<mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > >(mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > const&, mpl_::bool_<false>)
1	WFChatClient	
mars::stn::NetCore::~NetCore()
2	WFChatClient	
mars::stn::NetCore::~NetCore()
3	WFChatClient	
MessageQueue::__AsyncInvokeHandler(MessageQueue::MessagePost_t const&, MessageQueue::Message&)
4	WFChatClient	
MessageQueue::RunLoop::Run()
5	WFChatClient	
MessageQueue::MessageQueueCreater::__ThreadRunloop()
6	WFChatClient	
Thread::start_routine(void*)

**Comment by lilong7676** [comment]
SIGSEGV: Attempted to dereference garbage pointer 0x8bdfee968240.

0 WFChatClient            void mars_boost::signals2::detail::signal1_impl<void, bool, mars_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, mars_boost::function<void (bool)>, mars_boost::function<void (mars_boost::signals2::connection const&, bool)>, mars_boost::signals2::mutex>::do_disconnect<mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > >(mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > const&, mpl_::bool_<false>)
1 WFChatClient            mars::stn::NetCore::~NetCore()
2 WFChatClient            mars::stn::NetCore::~NetCore()
3 WFChatClient            MessageQueue::__AsyncInvokeHandler(MessageQueue::MessagePost_t const&, MessageQueue::Message&)
4 WFChatClient            MessageQueue::RunLoop::Run()
5 WFChatClient            MessageQueue::MessageQueueCreater::__ThreadRunloop()
6 WFChatClient            Thread::start_routine(void*)
7 libsystem_pthread.dylib __pthread_start

**Comment by lengqingfeng** [comment]
楼上的那个这么解决的

**Comment by lilong7676** [comment]
> 楼上的那个这么解决的

应该还是多次connect造成的，改了下连接的逻辑，最近好像没有很多这个报错了。

**Comment by heavyrain2012** [comment]
@lengqingfeng 使用新的SDK后，崩溃情况有没有改善，

**Comment by huangxianhui001** [comment]
我们的应用接入后,也是经常收到闪退的问题,APP已经启动一段时间了,所以应该不会存在那种重复connect的问题,也没有进入到IM的页面,我们是接入了另一个短视频的SDK,自从接入了短视频后,这个崩溃的问题就比较频繁了,不知道这个怎么确定是否为野火的问题,为什么会跟其他第三方SDK有冲突

**Comment by heavyrain2012** [comment]
@huangxianhui001 需要贴崩溃栈看一下

**Comment by heavyrain2012** [comment]
发现client层处理后台的逻辑有些问题，请更新到最新的client，这个问题应该就解决了

**Comment by heavyrain2012** [comment]
最近还有人有协议栈崩溃的问题吗，如果有请在这里反馈，谢谢

**Comment by lexiaoyao20** [comment]
![98EB26E5-1F87-42F0-A22A-460132334A51](https://user-images.githubusercontent.com/3021017/112093645-caff7900-8bd4-11eb-8309-13ea5444ecba.png)

我们这边也出现了这个闪退问题~ 用的是最新的SDK版本

**Comment by heavyrain2012** [comment]
这个问题我们在5.14号以后的版本加过保护，更新到这个日期之后的版本就应该没有这个问题了，建议用最新的协议栈

**Comment by wolimomomo** [comment]
2021.9.3 下载的最新demo编译，也出现这个问题

**Comment by lexiaoyao20** [comment]
<img width="1296" alt="0C2C62F9-5BDF-42B8-818D-70D4C444D4BF" src="https://user-images.githubusercontent.com/3021017/134447401-54abf6b3-c1ce-4b0b-85a2-c6bdbc44a502.png">

出现了多个 shortlink线程，我们这边确认不会去connect多次。而且 connect 的时候，你们SDK内部有 `_logined` 字段做了判断的，不存在多次 connect。

**Comment by heavyrain2012** [comment]
> <img alt="0C2C62F9-5BDF-42B8-818D-70D4C444D4BF" width="1296" src="https://user-images.githubusercontent.com/3021017/134447401-54abf6b3-c1ce-4b0b-85a2-c6bdbc44a502.png">
> 
> 出现了多个 shortlink线程，我们这边确认不会去connect多次。而且 connect 的时候，你们SDK内部有 `_logined` 字段做了判断的，不存在多次 connect。

这个看着像是分配内存失败，确认一下当时内存占用情况，是不是有内存泄漏了

**Comment by heavyrain2012** [comment]
今天刚更新了一个版本，这个版本应该彻底解决了崩溃问题，有崩溃问题的可以更新看看

**Comment by heavyrain2012** [comment]
最近大家有协议栈崩溃问题吗，如果有请提交到这里
