### ISSUE TITLE
批量发送图片,本都数据库只存储最后一条

### ISSUE THREAD

**Issue by LiuGanQQQ** [wildfirechat/ios-chat#184]
业务需要,批量发图片

复现流程:

1.进入会话,点击相册,批量选择

2.同时发送多条图片消息

3.消息发送后app显示无异常,点击查看图片,下标异常(可能是查看图片数据源是从数据库取的)

4.退出会话,重新进来只显示最后发的一张图片(猜测是数据库前几张图片消息没存进去)

5.删除本地聊天记录,从服务器拉历史消息,几个图片消息都会显示出来(印证数据库存储问题,而非消息丢失问题)

**Comment by LiuGanQQQ** [comment]
我之前做tcp通讯,用wcdb存消息,数据量较大的时候也没存丢过,感觉是你们图片上传那块做了什么处理...
望赶紧修复 0.0

**Comment by heavyrain2012** [comment]
这可能是某个版本的bug，请用最新版本，卸载重装试试

**Comment by yzl140520** [comment]
之前我也遇到同样问题，更新到最新版本就没事了

**Comment by LiuGanQQQ** [comment]
更新sdk 已解决
