### ISSUE TITLE
需求增加查询当前会话所有消息接口

### ISSUE THREAD

**Issue by Bearmond** [wildfirechat/ios-chat#185]
当用户通过searchMessage查找消息时，对搜索结果点击跳转到聊天页面，但是消息所在范围未知，可能超过当前已加载消息数，此时无法页面滚动至搜索的消息处。

**Comment by heavyrain2012** [comment]
getMessages接口有查询从某个位置起，向前或向后多少条消息的接口，使用这个来实现跳转到查询的消息。不能加载所有消息，如果一个会话内有几十万消息的话，内存都不够用，必须分段加载
