### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by yzl140520** [wildfirechat/ios-chat#186]
VVWork(25965,0x70000a2e8000) malloc: Heap corruption detected, free list is damaged at 0x6000004751d0
*** Incorrect guard value: 4916072044560675584
VVWork(25965,0x70000a2e8000) malloc: *** set a breakpoint in malloc_error_break to debug

-----------------

#0	0x00007fff51b1bfea in nanov2_allocate_from_block.cold.1 ()
#1	0x00007fff51b08f18 in nanov2_allocate_from_block ()
#2	0x00007fff51b08113 in nanov2_allocate ()
#3	0x00007fff51b08040 in nanov2_malloc ()
#4	0x00007fff51b0c2a3 in malloc_zone_malloc ()
#5	0x00007fff51b0ca55 in malloc ()
#6	0x00007fff4f92905a in operator new(unsigned long) ()
#7	0x000000010ee3cf00 in std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, void*>*, long>, bool> std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, http::less, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, std::__1::tuple<> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>&&, std::__1::tuple<>&&) ()
#8	0x000000010ee39eaa in http::HeaderFields::HeaderFiled(char const*, char const*) ()
#9	0x000000010f00ba6a in mars::stn::$_1::__invoke(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, AutoBuffer const&, AutoBuffer const&, AutoBuffer&, mars::stn::shortlink_tracker*) ()
#10	0x000000010f24832f in mars::stn::ShortLink::__RunReadWrite(int, int&, int&, mars::stn::ConnectProfile&) ()
#11	0x000000010f243b23 in mars::stn::ShortLink::__Run() ()
#12	0x000000010f2b0353 in Thread::start_routine(void*) ()
#13	0x00007fff51b3b109 in _pthread_start ()
#14	0x00007fff51b36b8b in thread_start ()

**Comment by heavyrain2012** [comment]
请检查是不是有内存泄漏的问题，看现象好像是分配内存引起的问题
