### ISSUE TITLE
群管理员无法修改群信息的extra字段

### ISSUE THREAD

**Issue by Bearmond** [wildfirechat/ios-chat#187]
根据业务需求，在extra字段中设置群介绍和群公告，但是现在群管理员无法修改extra字段。

**Comment by heavyrain2012** [comment]
群介绍和群公告，可以参考我们的实现，在应用服务中实现。另外如果修改extra也可以通过server api去修改。

管理员无法修改extra是什么现象，有没有错误码

**Comment by Bearmond** [comment]
错误码提示没有权限



---原始邮件---
发件人: "heavyrain.lee"<notifications@github.com&gt;
发送时间: 2020年6月19日(周五) 下午3:37
收件人: "wildfirechat/ios-chat"<ios-chat@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Amon"<1749608729@qq.com&gt;;
主题: Re: [wildfirechat/ios-chat] 群管理员无法修改群信息的extra字段 (#187)




 
群介绍和群公告，可以参考我们的实现，在应用服务中实现。另外如果修改extra也可以通过server api去修改。
 
管理员无法修改extra是什么现象，有没有错误码

**Comment by heavyrain2012** [comment]
已修改请用最新版本验证。如果验证失败，请查询该群组的类型回复我们
