### ISSUE TITLE
【iOS多人视频】多人视频时，iOS点击旋转摄像头功能按钮，有时会出现自己的小画面卡住

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/ios-chat#190]
多人视频时，iOS多次点击旋转摄像头功能按钮，就会出现切换失败，自己的小画面卡在了自己的头像等待中。

**Comment by heavyrain2012** [comment]
我们做过多次测试，在多人通话过程中快速连续点击切换前后摄像头按钮，没有能复现这个问题。请节后用我们最新的版本验证

**Comment by Charlie191011** [comment]
最近的SDK中，依然出现了这个问题，iOS和安卓都会出现。
