### ISSUE TITLE
修改在群组中的昵称时不能及时生效，需要重新进入详情页面才能生效

### ISSUE THREAD

**Issue by YYT-YONYOU** [wildfirechat/ios-chat#191]
修改在群组中的昵称时不能及时生效，需要重新进入详情页面才能生效

**Comment by heavyrain2012** [comment]
请用最新版本验证

**Comment by YYT-YONYOU** [comment]
新版的群名片已经可以了，但是修改群名还是不能及时更新。

**Comment by heavyrain2012** [comment]
刚解决了，请更新代码检查

**Comment by YYT-YONYOU** [comment]
我刚试了下，不行哦，

**Comment by YYT-YONYOU** [comment]
我试着重新获取群组信息，但是获取回来的还是旧的。

**Comment by heavyrain2012** [comment]
用我们的demo测试看看，另外需要把协议栈也更新到最新才行

**Comment by YYT-YONYOU** [comment]
我刚更新了协议栈。也是不行。我试试demo吧

**Comment by heavyrain2012** [comment]
你加微信 wildfirechat 然后拍一段录像发过来，谢谢

**Comment by YYT-YONYOU** [comment]
demo测试的时候可以。但是一旦打开修改页面是设置nav.modalPresentationStyle = 0;这个之后，就不行了，设置了这个修改完成之后会走viewWillAppear。这就调用协议栈，重新拿群信息，拿到的就是旧的
