### ISSUE TITLE
聊天界面中的emoj滚动困难

### ISSUE THREAD

**Issue by YYT-YONYOU** [wildfirechat/ios-chat#194]

**Comment by heavyrain2012** [comment]
请用最新版本验证

**Comment by yeshengwu** [comment]
在很早版本我们自己修复了这个问题，没提这个问题，因为这个好像跟im 没关系。现在你们居然自己修复了。嗯，没搞明白你们修bug的规则。

**Comment by yeshengwu** [comment]
还有，你们更新 协议库 mars 时能否说下具体更新了啥。因为我们是基于旧版本开发，但是协议库不知道是否需要更新。如果有具体更新提交日志，我们可以选择更新。 目前我们是用旧版本，不知道更新协议库有米有副作用。

**Comment by heavyrain2012** [comment]
> �在很早版本我们自己修复了这个问题，没提这个问题，因为这个好像跟im 没关系。现在你们居然自己修复了。嗯，没搞明白你们修bug的规则。

我们是焦距在IM能力上的，这个也是我们技术的价值所在，所以IM的问题优先级排在第一位的。如果IM的任务比较紧张，那就把UI的事情放一放，毕竟都开源了你们也能改；IM的任务轻松一点的时候，严重的UI问题就处理一下，也能方便客户使用。



> 还有，你们更新 协议库 mars 时能否说下具体更新了啥。因为我们是基于旧版本开发，但是协议库不知道是否需要更新。如果有具体更新提交日志，我们可以选择更新。 目前我们是用旧版本，不知道更新协议库有米有副作用。

最近服务加的一些功能，还有部分问题的修复，无法一一列举。一般情况下如果协议栈更新可以跟着服务器的版本走，如果服务器更新了，协议栈最好也更新。更新都是有风险的，所以请你们做好验证工作，如果发现有倒退问题请及时联系我们

**Comment by YYT-YONYOU** [comment]
完美解决了，谢谢大神
