### ISSUE TITLE
消息丢失

### ISSUE THREAD

**Issue by yzl140520** [wildfirechat/ios-chat#196]
消息丢失很严重，图片是连续发9张，只能收到八张，文本消息，一直连续发的话，大概率丢失

**Comment by heavyrain2012** [comment]
请提供视频录像及协议栈日志给我们

**Comment by heavyrain2012** [comment]
另外确认服务器使用最新版本的

**Comment by yzl140520** [comment]
> 请提供视频录像及协议栈日志给我们

野 火日志启动后，在13.4系统连续发9张图片会崩溃，所以协议栈日志暂时给不了

**Comment by heavyrain2012** [comment]
demo上是没有选择发送多张图片的功能的，能不能贡献给我们，我们也好自己来复现和解决这个问题

**Comment by yzl140520** [comment]
> 另外确认服务器使用最新版本的

目前服务器是没有用最新版本，等服务器升级后，再给你反馈

**Comment by yzl140520** [comment]
> demo上是没有选择发送多张图片的功能的，能不能贡献给我们，我们也好自己来复现和解决这个问题

呃。。。。。。这怎么贡献，你们找个图片游览器，稍微调整下代码就行了吧，而且我们是swift代码

**Comment by yzl140520** [comment]
> demo上是没有选择发送多张图片的功能的，能不能贡献给我们，我们也好自己来复现和解决这个问题

mars::stn (24)#0	0x00000001ae9b8ebc in __pthread_kill ()
#1	0x00000001ae8d4790 in pthread_kill$VARIANT$mp ()
#2	0x00000001ae8288a0 in __abort ()
#3	0x00000001ae828830 in abort ()
#4	0x00000001ae827c44 in __assert_rtn ()
#5	0x0000000106b85f4c in XLogger::DoTypeSafeFormat(char const*, string_cast const**) at /Users/yzl/yzl/vv/App/VVWork/Pods/WFChatClient/WFChatClient/Vendor/mars.framework/Headers/xlog/xlogger.h:550
#6	0x0000000106d167d0 in mars::stn::sendSavedMsg(long, mars::stn::TMessage&, mars::stn::SendMsgCallback*, int) ()
#7	0x0000000106d1be74 in mars::stn::UploadMediaForSendCallback::onSuccess(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#8	0x0000000106d1d6cc in mars::stn::UploadQiniuCallback::onSuccess(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) ()
#9	0x0000000106ebc89c in mars::stn::StnCallBack::Buf2Resp(unsigned int, void*, AutoBuffer const&, AutoBuffer const&, int&, int) ()
#10	0x0000000106f6e8bc in mars::stn::$_25::__invoke(unsigned int, void*, AutoBuffer const&, AutoBuffer const&, int&, int) ()
#11	0x0000000106f3ccec in mars::stn::ShortLinkTaskManager::__OnResponse(mars::stn::ShortLinkInterface*, mars::stn::ErrCmdType, int, AutoBuffer&, AutoBuffer&, bool, mars::stn::ConnectProfile&) ()
#12	0x0000000106f32918 in mars_boost::detail::function::void_function_obj_invoker0<mars_boost::_bi::bind_t<mars_boost::_bi::unspecified, mars_boost::function<void (mars::stn::ShortLinkInterface*, mars::stn::ErrCmdType, int, AutoBuffer&, AutoBuffer&, bool, mars::stn::ConnectProfile&)>, mars_boost::_bi::list7<mars_boost::_bi::value<mars::stn::ShortLink*>, mars_boost::_bi::value<mars::stn::ErrCmdType>, mars_boost::_bi::value<int>, mars_boost::_bi::value<move_wrapper<AutoBuffer, AutoBuffer> >, mars_boost::_bi::value<move_wrapper<AutoBuffer, AutoBuffer> >, mars_boost::_bi::value<bool>, mars_boost::_bi::value<mars::stn::ConnectProfile> > >, void>::invoke(mars_boost::detail::function::function_buffer&) ()
#13	0x0000000106bdecc0 in MessageQueue::__AsyncInvokeHandler(MessageQueue::MessagePost_t const&, MessageQueue::Message&) ()
#14	0x0000000106bddf1c in MessageQueue::RunLoop::Run() ()
#15	0x0000000106bdef78 in MessageQueue::MessageQueueCreater::__ThreadRunloop() ()
#16	0x0000000106f8a67c in Thread::start_routine(void*) ()
#17	0x00000001ae8dd1ec in _pthread_start ()
<img width="886" alt="image" src="https://user-images.githubusercontent.com/9834546/86075954-c7aee500-babb-11ea-98ee-ca57167e2617.png">

**Comment by heavyrain2012** [comment]
客户端协议栈有个限制，消息体的大小不能超过15K，之前有个bug，超过15K就会触发崩溃。最新版本已经修改不崩溃了，但是不能发送超过15K的内容。图片消息的图片是上次媒体服务器的，先上传得到一个url，然后图片消息内只包含url和缩略图，请检查缩略图是不是超过了15K

**Comment by yzl140520** [comment]
> 客户端协议栈有个限制，消息体的大小不能超过15K，之前有个bug，超过15K就会触发崩溃。最新版本已经修改不崩溃了，但是不能发送超过15K的内容。图片消息的图片是上次媒体服务器的，先上传得到一个url，然后图片消息内只包含url和缩略图，请检查缩略图是不是超过了15K

soga,我刚就遇到一个图片一直发送失败，跟了一下，怀疑是缩略图太大的原因

**Comment by yzl140520** [comment]
> 客户端协议栈有个限制，消息体的大小不能超过15K，之前有个bug，超过15K就会触发崩溃。最新版本已经修改不崩溃了，但是不能发送超过15K的内容。图片消息的图片是上次媒体服务器的，先上传得到一个url，然后图片消息内只包含url和缩略图，请检查缩略图是不是超过了15K

安卓端送九张图片，安卓手机能全部收到，iOS的只能收到部分，是什么原因？

**Comment by heavyrain2012** [comment]
Duplicate of #201
