### ISSUE TITLE
图片发送失败

### ISSUE THREAD

**Issue by ybmiao** [wildfirechat/ios-chat#197]
第一次安装应用，无法发送图片。划掉应用后可以发送。
报错信息
[I][mars::proto][stn_callback.cc, OnTaskEnd, 985][PROTO -> Upload TASK taskid:21 cmdid:20 channel_id:0 channel_select:1 cgi:/fs send_only:0 need_authed:1 limit_flow:0 limit_frequency:1 network_status_sensitive:0 channel_strategy:0 priority:3 retry_count:-1 server_process_cost:-1 total_timetout:-1 end with error code:404

**Comment by heavyrain2012** [comment]
您好，请提供完整日志。可以贴在这里，或者发邮件给 support@wildfirechat.cn
