### ISSUE TITLE
IM群聊，安卓发9张图片，iOS图片部分丢失收到6张/收到8张(安卓另外一部手机全部收到)

### ISSUE THREAD

**Issue by yzl140520** [wildfirechat/ios-chat#201]
如标题

**Comment by heavyrain2012** [comment]
把服务器更新到最新，还有把客户端也都更新到最新看看。如果还有问题，请给我们抓个录像看一下

**Comment by yzl140520** [comment]
> 把服务器更新到最新，还有把客户端也都更新到最新看看。如果还有问题，请给我们抓个录像看一下

OK

**Comment by heavyrain2012** [comment]
请配合我们：
1，把服务器版本和SDK更新到最新进行测试。
2，如果有问题，请录像并抓取协议栈日志和服务器日志发给我们。

请回复上述2个要求的结果

**Comment by yzl140520** [comment]
> 请配合我们：
> 1，把服务器版本和SDK更新到最新进行测试。
> 2，如果有问题，请录像并抓取协议栈日志和服务器日志发给我们。
> 
> 请回复上述2个要求的结果
1、都是最新SDK，现在文本消息暂时没有丢失，就是连续发九张图片时，在同一个群里，有些人全部收到，有些人只收到部分，
2、请稍等
