### ISSUE TITLE
A添加B好友，B添加A为好友，都未处理本次好友请求，B添加A为好友发送成功后此时 B客户端中好友A的加好友请求消失了

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#206]
如题。

另外：
此时，如果 B接受了A好友请求，A客户端好友请求列表状态没刷新，应该由 接受 变成 已接受。
Android端行为正常。

debug得知：A发送好友请求到B，B列表正常刷新，但是B去请求A好友时，B的好友请求列表刚刚的A的好友请求消失了。

**Comment by heavyrain2012** [comment]
客户端协议栈的bug，最新版本已经解决，请更新验证
