### ISSUE TITLE
iOS 好友请求处理

### ISSUE THREAD

**Issue by iOS-Kel** [wildfirechat/ios-chat#207]
iOS 好友请求接口handleFriendRequest:accept:extra:success:error:，accept参数传false时，后面双方就再也没法加好友了，怎么回事哦，这很不合理吧，请问有没有解决方案呀，我们应用想做忽略好友请求的功能

**Comment by heavyrain2012** [comment]
好友请求只有接受和拒绝两种操作，传false是拒绝，拒绝了之后在一定时间之内是不允许再加的，详情请参考常见问题里的说明。

忽略功能没有必要吧，如果不想处理不处理不就好了吗，可以参考一下微信的做法
