### ISSUE TITLE
发起打电话的 WFAVCallSessionDelegate疑问 

### ISSUE THREAD

**Issue by yeshengwu** [wildfirechat/ios-chat#209]
WFAVCallSessionDelegate 中 didError 中 error 有哪些具体错误？
我们目前想知道 当 p2p打洞失败有没有包含在 didError回调中？
或者我们客户端是否能捕获 p2p打洞失败的事件？ @heavyrain2012

**Comment by heavyrain2012** [comment]
error没有细分类，基本上所有操作出现异常都会报error，如果是致命错误才会结束通话，error可以作为出现问题时分析用的工具。p2p打洞失败不是一个error，是一个ice状态，这个状态会导致连接失败，从error的回调中无法看出打洞失败。

你们遇到了什么问题？

**Comment by yeshengwu** [comment]
顺便问一些： 拨打语音和视频电话 语音是用的 opus编码吗？还是 G.711?

**Comment by heavyrain2012** [comment]
opus
