### ISSUE TITLE
我在iOS沙盒里只发现一个数据库文件，但这个好像不是IM数据，请问IM数据文件是在沙河中哪个文件中？

### ISSUE THREAD

**Issue by tenxun123** [wildfirechat/ios-chat#210]
我在沙盒路径Library中，只发现Cache.db这个数据库文件，请问iOS数据库文件存放在哪个目录中？

<img width="1812" alt="WeChat7a7b815a112d632d4d5a2adb4cab379a" src="https://user-images.githubusercontent.com/68217763/87276996-0610bf00-c514-11ea-8475-6a19ffab77d8.png">

**Comment by tenxun123** [comment]
截图给你看看沙盒路径：

<img width="1868" alt="WeChat57b05e98303aca74738dcc0abae2d34c" src="https://user-images.githubusercontent.com/68217763/87277118-46703d00-c514-11ea-834a-9588a28927ab.png">

**Comment by tenxun123** [comment]
难道这个data文件夹就是你们的数据库吗？

<img width="802" alt="WeChat3340ab2d595c4c718a327dc9879a1c93" src="https://user-images.githubusercontent.com/68217763/87278538-43c31700-c517-11ea-8671-b5a0b90ca234.png">

**Comment by heavyrain2012** [comment]
对的，就是这个文件

**Comment by lilong7676** [comment]
> 难道这个data文件夹就是你们的数据库吗？
> 
> <img alt="WeChat3340ab2d595c4c718a327dc9879a1c93" width="802" src="https://user-images.githubusercontent.com/68217763/87278538-43c31700-c517-11ea-8671-b5a0b90ca234.png">

这个数据库 可以打开吗？

**Comment by tenxun123** [comment]
加密了，打不开
