### ISSUE TITLE
获取最近会话的LastMessage为空

### ISSUE THREAD

**Issue by Bearmond** [wildfirechat/ios-chat#211]
iOS端SDK获取最近会话列表，返回数组里面WFCCConversationInfo里面的lastMessage为nil，而且进入会话后拉取不到聊天记录。Android端可以正常拉取到lastMessage和聊天记录。

**Comment by heavyrain2012** [comment]
更新到最新的SDK试试

**Comment by Bearmond** [comment]
> 更新到最新的SDK试试

拉取到的信息依然没有Android端全

**Comment by heavyrain2012** [comment]
请录像给我们看一下问题

**Comment by Bearmond** [comment]
> 请录像给我们看一下问题


[录屏.zip](https://github.com/wildfirechat/ios-chat/files/4930216/default.zip)

**Comment by heavyrain2012** [comment]
IM服务的配置文件中有下面的配置。改成1之后，登录就会接受服务器上配置文件指定条数的历史消息，默认应该是3000条。注意是有副作用的，就是消息删除不掉，当在客户端删除消息后，卸载重装，还是会收下来的，具体问题文档的常见问题有描述

```
##首次登录，是否接收之前的历史消息。0 不同步历史消息；1 同步历史消息。
##选择不同步历史消息依然会同步最近5分钟内的消息。因为换手机期间可能收到消息，不能丢失。
message.roaming 0
```

**Comment by Bearmond** [comment]
> IM服务的配置文件中有下面的配置。改成1之后，登录就会接受服务器上配置文件指定条数的历史消息，默认应该是3000条。注意是有副作用的，就是消息删除不掉，当在客户端删除消息后，卸载重装，还是会收下来的，具体问题文档的常见问题有描述
> 
> ```
> ##首次登录，是否接收之前的历史消息。0 不同步历史消息；1 同步历史消息。
> ##选择不同步历史消息依然会同步最近5分钟内的消息。因为换手机期间可能收到消息，不能丢失。
> message.roaming 0
> ```

具体在iOS端SDK的哪个文件中呢？

**Comment by heavyrain2012** [comment]
这个是IM服务的配置文件，wildfirechat.conf，让服务器端的同事处理，修改重启之后，客户端卸载重装检查一下

**Comment by tenxun123** [comment]
这个问题你们java服务端不可以优化下吗？记录消息已读的标志，拉取过的历史消息下次登录后就不在拉取了

**Comment by heavyrain2012** [comment]
无法支持，服务器的消息记录都是无状态的，状态保存在客户端。
