### ISSUE TITLE
问题：尝试用最新版的WCDB打开消息数据库报错，是因为WCDB不支持sqlcipher 4吗？

### ISSUE THREAD

**Issue by lilong7676** [wildfirechat/ios-chat#212]
![image](https://user-images.githubusercontent.com/21004230/87623341-c2a69280-c757-11ea-9c79-9abcb228fbfd.png)
![image](https://user-images.githubusercontent.com/21004230/87623348-c76b4680-c757-11ea-8ab0-6c192fb47a18.png)

**Comment by heavyrain2012** [comment]
我们借鉴了WCDB，但并不是兼容WCDB，客户端数据库是没有办法打开的。

**Comment by lilong7676** [comment]
好的，谢谢回复。
