### ISSUE TITLE
聊天画面 发送视频 成功之后 点视频播放 闪退

### ISSUE THREAD

**Issue by shanggquan** [wildfirechat/ios-chat#215]
#### 操作说明
聊天画面 相册选择视频, 发送视频 成功之后 聊天页点视频播放 闪退

#### 表现现象
![截屏2020-07-20 上午11 52 39_副本](https://user-images.githubusercontent.com/11956371/87898050-b97f3380-ca7f-11ea-9475-3ec4cdc05f1e.jpg)

**Comment by heavyrain2012** [comment]
用最新的demo对比测试一下

**Comment by shanggquan** [comment]
![截屏2020-07-21 上午9 19 12_副本](https://user-images.githubusercontent.com/11956371/88001688-52bb5200-cb33-11ea-921a-67d6f914dadd.jpg)

**Comment by shanggquan** [comment]
现在是 2020年7月21号 11:04 我刚刚下载的demo 就是以上错误. 请您确认.

**Comment by heavyrain2012** [comment]
我们测试都没有复现问题，明白你加一下微信 wildfirechat ，进行微信沟通一下吧

**Comment by heavyrain2012** [comment]
这边反馈说没有收到你们微信反馈问题，请问问题解决了还是没有来得及微信反馈给我们？

**Comment by shanggquan** [comment]
闪退的原因找到了. URL可能是应该有空格 换NSURL之后 url是空的 所以闪退了.
![1761595573761_ pic_hd](https://user-images.githubusercontent.com/11956371/88368440-a8585e80-cdc0-11ea-940a-23471a466f00.jpg)

**Comment by shanggquan** [comment]
再问: 为什么URL里会有空格呢. 我把空格转译成%20 之后 访问不到视频 找不到服务器.

**Comment by heavyrain2012** [comment]
这个问题原因比较多，根本原因是测试文件服务器功能太弱。在协议栈和ui层做了修改，请更新协议栈和ui测试。另外如果上生产环境，请切换到七牛对象存储
