### ISSUE TITLE
IMToken是否是通过AppServer登录后获取的？

### ISSUE THREAD

**Issue by tenxun123** [wildfirechat/ios-chat#216]
您好：
我有如下几个问题：
（1）IMToken是否是通过APP server获取的，IM长连接成功，如果token过期后，怎么进行更新token？

 （2）我在IM server最新代码中发现了 GETTOKEN这个topic，是否意味了长连接可以更新token了，不需要通过AppServer进行更新了，这个更新后的token现在有使用进行长连接吗？或者说目前服务端这个topic还没有作用？

**Comment by tenxun123** [comment]
如果是跨平台C++代码通过这个topic进行自动更新token，那么在什么时机进行自动更新token呢？

**Comment by heavyrain2012** [comment]
token获取必须通过应用服务，sdk内部不能更新token

**Comment by tenxun123** [comment]
嗯，明白，那么后台这个GETTOKEN的topic是否是无用的呢？
