### ISSUE TITLE
希望能得到您的解答：在你们的WildFireChat工程中使用WFChatUIKit，WFChatClient的源代码，不用framework，结果报如下错误，

### ISSUE THREAD

**Issue by tenxun123** [wildfirechat/ios-chat#217]
前提：xcode11.6的版本，应该是最新的。

一：我在WildFireChat工程中直接使用WFChatUIKit，WFChatClient的源代码，调试，其它错误都解决了，现在报如下错误：

<img width="875" alt="WeChatfb16ac8174e3cab8a318a4448a3f81b3" src="https://user-images.githubusercontent.com/68217763/88164856-4fb18600-cc47-11ea-82f5-4dffe661a5a3.png">

二：调整后的工程结构
<img width="1168" alt="WeChat4bfb7958815ff4be918d3706b2e3efc1" src="https://user-images.githubusercontent.com/68217763/88164954-7a9bda00-cc47-11ea-854b-41d4a362460a.png">

三：在工程中把arm64架构去掉，就运行不起来了，报如下错误
<img width="1057" alt="WeChat784134500a515aa3cead74476b51e671" src="https://user-images.githubusercontent.com/68217763/88166714-48d84280-cc4a-11ea-8709-2300eac35736.png">

**Comment by heavyrain2012** [comment]
下载最新的源码，然后打开 ios-chat 项目空间，依次编译 WFChatClient，WFChatUIKit，WildfireChat项目就可以编译过的，请按照这个方法编译试试

**Comment by tenxun123** [comment]
你说的这个方法我试过了，可以编译通过。现在我新项目不想使用framework，想用源代码进行开发，然后就报那个错误了

**Comment by heavyrain2012** [comment]
所有的源码和库都在，应该可以支持你们这种使用方法，需要你们自己来研究了

**Comment by tenxun123** [comment]
好，我们研究下
