### ISSUE TITLE
发送视频消息返回-1，视频封面超过限制

### ISSUE THREAD

**Issue by 15611958820** [wildfirechat/ios-chat#218]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
在聊天信息中发送视频，，配置了七牛  文件也传上去了  但发送完信息返回-1     没发送成功

#### 表现现象
返回信息 errorcode  -1

#### 预期结果
大于15k的视频封面可以发送成功

#### 补充条件
[I][mars::proto][business.cc, sendSavedMsg, 1057][Message body size is :73916, is more than 15K limition! Plz make sure not exceed 10K!!!
这里限定了视频封面质量大小限制，可否自定义配置

**Comment by heavyrain2012** [comment]
由于协议栈的问题，不支持单个请求超过15K，所以确保消息的大小不能超过10K。缩略图可以使用jpeg格式，压缩率低一点，并限制大小，可以参考demo的做法
