### ISSUE TITLE
第一次音频通话接收后，再拨打一次给对方，双方无通话声音

### ISSUE THREAD

**Issue by 794341379** [wildfirechat/ios-chat#22]

**Comment by 794341379** [comment]
两个iOS设备，对同一个会话拨打两次，第一次音频通话有声音，第二次音频通话就没声音了,再次拨打另一个不同会话，就能正常音频通话。
应该是同一个会话的同一个targetId ,在第二次拨打的时候，第一次的没释放。

**Comment by kaixiang1306** [comment]
一样问题 :( 有谁知道如何解决吗

**Comment by ChinaJson** [comment]
一样的问题 现在解决没有？

**Comment by heavyrain2012** [comment]
最新版本应该已经解决，请用最新版本验证，如果还有问题请提新issue
