### ISSUE TITLE
有提供获取被禁言成员的方法吗，可以提供一个吗

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#220]
有提供获取被禁言成员的方法吗，可以提供一个吗

**Comment by heavyrain2012** [comment]
群成员对象有个type字段，当值为3时，群成员就是被禁言的。可以包装一个函数，获取到所有群成员后，再过滤出所有type为3个成员

**Comment by AliceTTY** [comment]
请问你们可以提供获取数组的方法吗，每次都要遍历所有的成员数组，群成员人数太多的话，可能性能不是很好。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "heavyrain.lee"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 下午5:18
收件人: "wildfirechat/ios-chat"<ios-chat@noreply.github.com&gt;; 
抄送: "Alice"<512642546@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wildfirechat/ios-chat] 有提供获取被禁言成员的方法吗，可以提供一个吗 (#220)





 
群成员对象有个type字段，当值为3时，群成员就是被禁言的。可以包装一个函数，获取到所有群成员后，再过滤出所有type为3个成员
