### ISSUE TITLE
撤回消息接收方能删除消息内容吗

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#222]
用户A发送消息a给用户B，用户A撤回a消息，此时能把B的收到的消息a的消息删除吗，现在的情况是，a消息的内容为撤回类消息，但是原来a消息的内容，从私密性考虑，既然A撤回消息，就是不想让用户B看见，虽然页面可以处理让用户A不展示消息，但是如果数据被抓包还是会暴露，从私密性考虑，请处理一下。

**Comment by heavyrain2012** [comment]
确实是个安全 隐患，可能会让人开发出防撤回插件。专业版已经修改了，请更新服务后验证
