### ISSUE TITLE
视频摄像头没有占满全屏问题

### ISSUE THREAD

**Issue by YYT-YONYOU** [wildfirechat/ios-chat#223]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
发起视频聊天

#### 表现现象
摄像头没有占满全屏 self.scalingType = kWFAVVideoScalingTypeAspectFill;如果改成这个，会拉伸，不自然

#### 预期结果
摄像头占满全屏

#### 补充条件
固定出现

#### demo对比结果
demo也是这样

**Comment by heavyrain2012** [comment]
已解决，请更新到最新代码验证
