### ISSUE TITLE
新建会话类型

### ISSUE THREAD

**Issue by shanggquan** [wildfirechat/ios-chat#225]
## 提issue小提示
新建会话类型   (不是"消息"类型,是"会话"类型)
#### 表现现象
模仿私聊(单聊)新建了一个会话类型 

仔细观察在单聊里 发送和接收的message信息里
发送message里有  target: BID  formUser:AID
接收message里有 target:AID  formUser:AID

新建的会话类型里;
发送message里有  target: BID  formUser:AID
接收message里有 target:BID  formUser:AID
请问 在接收里的message的target 没有改变 这个原因在哪里  
请给一些帮助 谢谢.

**Comment by sjhgithub** [comment]
似乎Single类型的会话,target不同于其它类型,会单独处理,目前不知道该字段的意义
[接收方]接收到的该消息,sender(from)      等于conversation.target;
[发送方]接收到的该消息,sender(from)[不]等于conversation.target
不明白该conversation.target的意义所在,望指教
