### ISSUE TITLE
（期望）搜索全部会话消息

### ISSUE THREAD

**Issue by LiuGanQQQ** [wildfirechat/ios-chat#227]
期望可以搜索全部会话消息，感谢

/**
 搜索消息
 
 @param conversation 会话
 @param keyword 关键词
 @return 命中的消息
 */
- (NSArray<WFCCMessage *> *)searchMessage:(WFCCConversation *)conversation
                                  keyword:(NSString *)keyword;

**Comment by heavyrain2012** [comment]
好的，我们会在一周左右的时间把这个功能加上，请耐心等待

**Comment by LiuGanQQQ** [comment]
> 好的，我们会在一周左右的时间把这个功能加上，请耐心等待

3Q

**Comment by heavyrain2012** [comment]
已添加，请更新客户端SDK进行验证
