### ISSUE TITLE
数据库搜索所有语音消息类型

### ISSUE THREAD

**Issue by storm52** [wildfirechat/ios-chat#230]
怎么获取语音类型所有消息，做一个通话记录的界面。希望有一个getMessagesByMediaType的方法

**Comment by heavyrain2012** [comment]
- (NSArray<WFCCMessage *> *)getMessages:(NSArray<NSNumber *> *)conversationTypes
                                           lines:(NSArray<NSNumber *> *)lines
                                    contentTypes:(NSArray<NSNumber *> *)contentTypes
                                            from:(NSUInteger)fromIndex
                                           count:(NSInteger)count
                                        withUser:(NSString *)user 

contentTypes 传入语音消息类型

**Comment by storm52** [comment]
contentTypes 传入语音消息类型传入6返回空，传入1会过滤只返回文字类型的，是有bug吗
[[[WFCCIMService sharedWFCIMService] getMessages:@[@(Single_Type)] lines:@[@(0)] contentTypes:@[@6] from:0 count:100000 withUser:nil] mutableCopy];

**Comment by heavyrain2012** [comment]
//基本消息类型
//未知类型的消息
#define MESSAGE_CONTENT_TYPE_UNKNOWN 0
//文本消息
#define MESSAGE_CONTENT_TYPE_TEXT 1
//语音消息
#define MESSAGE_CONTENT_TYPE_SOUND 2
//图片消息
#define MESSAGE_CONTENT_TYPE_IMAGE 3


contentType是消息内容类型，语音消息对应的值是2

**Comment by storm52** [comment]
不好意思是我没表达清楚。是要做通话记录，也就是视频通话类型的，应该是6吧

**Comment by heavyrain2012** [comment]
通话消息的type是400

VOIP_CONTENT_TYPE_START 400

**Comment by storm52** [comment]
谢谢，可以的 👍
