### ISSUE TITLE
怎么获取群里某个人的聊天信息

### ISSUE THREAD

**Issue by shanggquan** [wildfirechat/ios-chat#231]
## 提issue小提示
[[WFCCIMService sharedWFCIMService] getMessages:weakSelf.conversation contentTypes:nil from:0 count:100 withUser:@"ididid"]  
这里withUser:@"ididid" 不论写什么值 返回来的数据是一样的.

**Comment by heavyrain2012** [comment]
这个接口是给公众号使用的，我们会添加一个新的接口用来获取某个会话里的某个用户的所有发言

**Comment by heavyrain2012** [comment]
已添加，请更新到最新SDK进行验证

**Comment by shanggquan** [comment]
好的谢谢.

**Comment by heavyrain2012** [comment]
不客气
