### ISSUE TITLE
撤回功能

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#232]
1、自定义消息pushContent字段赋值推送文字后，撤回该消息，也会收到一条同样的推送，
2、撤回消息怎么才能拿到自定义消息的其他内容，撤回后重新编辑的功能需要用到

**Comment by heavyrain2012** [comment]
1、自定义消息pushContent字段赋值推送文字后，撤回该消息，也会收到一条同样的推送，
服务器的问题，最新版已经修改，请更新服务器。
2、撤回消息怎么才能拿到自定义消息的其他内容，撤回后重新编辑的功能需要用到
撤回消息的extra中包含部分字段，可以检查是否足够重新编辑
