### ISSUE TITLE
支持下载视频的播放吗？

### ISSUE THREAD

**Issue by zhao520wei** [wildfirechat/ios-chat#233]
## 提issue小提示
在聊天页面发送视频， 目前VideoPlayerKit是流视频播放， 如何改动能变成支持下载播放了？（先下载，后播放，不是在线播放的模式，现在如果服务器是仅支持下载播放）

#### 操作说明
后端文件系统之支持下载，不支持流媒体播放，希望前端修改一下，能够让播放视频功能正常

#### 表现现象
服务器下载视频播放时，视频播放是直接 
AVPlayerStatus status = [[change objectForKey:NSKeyValueChangeNewKey] integerValue]; 
直接返回AVPlayerStatusFailed

#### 预期结果
如何改动能够支持下载播放？

**Comment by AllLuckly** [comment]
VideoPlayerKit 无法播放视频了，都是用的一些不维护的库
