### ISSUE TITLE
我需要把连接的动作放在一个指纹验证之后，但是会报kConnectionStatusSecretKeyMismatch

### ISSUE THREAD

**Issue by storm52** [wildfirechat/ios-chat#235]
#### 操作说明
将AppDelegate里的 [[WFCCNetworkService sharedInstance] connect:savedUserId token:savedToken];操作放在延后执行
#### 表现现象
onConnectionStatusChanged里回调状态kConnectionStatusSecretKeyMismatch

#### 预期结果
希望正确连接上

**Comment by heavyrain2012** [comment]
kConnectionStatusSecretKeyMismatch有两种可能：
1. clientId和token不匹配导致的
2. 调用过disconnect函数，disconnect函数的cleanSession参数为true

请检查是否是上述两种原因
