### ISSUE TITLE
视频通话、视频通话切语音通话，声音外放，无法使用蓝牙耳机接听

### ISSUE THREAD

**Issue by songruifengdev** [wildfirechat/ios-chat#236]
用户A 向 用户B 发起视频通话，无法使用蓝牙耳机接听，声音处于外放状态。
视频通话切语音通话，无法使用蓝牙耳机接听，声音处于外放状态。
直接发起语音通话，可以使用蓝牙耳机接听。

希望在蓝牙耳机连接状态下，视频通话、切换语音通话都可以使用耳机接听。感谢。

**Comment by heavyrain2012** [comment]
已解决，请更新最新版本验证
