### ISSUE TITLE
请提供未读的被@消息获取方法

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#237]
我们现在有一个需求是：如果一个会话有多个未读的@全体或者被@消息，我们需要跳转聊天页面时定位到第一个被@的消息，请提供获取未读的被@消息获取方法相关的方法，请提供数组，按收到的时间排序。也请提一个实现该功能的方法

**Comment by heavyrain2012** [comment]
获取消息的方法中，有个方法可以传入参数消息状态，未读@消息的状态是mentioned和mentionall，可以读取2次获取到所有未读@信息

**Comment by AliceTTY** [comment]
请提供具体的方法和写法，
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/ios-chat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 晚上8:47
收件人:&nbsp;"wildfirechat/ios-chat"<ios-chat@noreply.github.com&gt;;
抄送:&nbsp;"Alice"<512642546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wildfirechat/ios-chat] 请提供未读的被@消息获取方法 (#237)





 
获取消息的方法中，有个方法可以传入参数消息状态，未读@消息的状态是mentioned和mentionall，可以读取2次获取到所有未读@信息

**Comment by heavyrain2012** [comment]
已经解决
