### ISSUE TITLE
新增的消息类型解析错误

### ISSUE THREAD

**Issue by LiuGanQQQ** [wildfirechat/ios-chat#239]
消息类型:MESSAGE_PC_LOGIN_REQUSET

![屏幕快照 2020-09-01 04 46 00 PM](https://user-images.githubusercontent.com/21186780/91828442-b8424880-ec72-11ea-8a1f-0749472f3929.png)

**Comment by heavyrain2012** [comment]
是我们粗心大意了，非常感谢您的提醒～～
