### ISSUE TITLE
在WFCCIMService.mm 里面写了个方法调用,报抽象函数问题,请看一下,谢谢

### ISSUE THREAD

**Issue by csdf-ssm** [wildfirechat/ios-chat#24]
mars::stn::setRefreshGroupInfoCallback(new IMGetGroupInfoCallback(suc,errorBlock));
报Allocating an object of abstract class type 'IMGetGroupInfoCallback'  请问这个怎么解决

**Comment by heavyrain2012** [comment]
你们修改的，我们也不清楚改啥了。
你们有什么需求可以提给我们加
