### ISSUE TITLE
iOS  调用相机拍摄画面花掉

### ISSUE THREAD

**Issue by yangshupeng** [wildfirechat/ios-chat#243]
ios:  聊天界面，点击底部调用拍摄的时候，如果刚开始相机是被遮住的，然后去掉遮住再拍摄，就会出现画面拍不清，有什么办法处理下吗。
![8071599734457_ pic](https://user-images.githubusercontent.com/15025850/92720984-f5f05100-f397-11ea-8506-28134c639269.jpg)

**Comment by heavyrain2012** [comment]
跟手机型号有关系吗，我这边试了几个手机都没有出现？另外换几个手机试试，看看是不是某一个型号，或者某一台手机的问题

**Comment by yangshupeng** [comment]
跟手机型号没关系，我这边的手机都会出现这个情况。你们的demo也有这个问题。我在描述的详细一点：
进入聊天界面，（先把手机平放在桌面上，遮住后摄像头）点击底部拍摄功能按钮的时候，唤起摄像功能后，先让后摄像头进入无光环境。过两三秒后在把手机拿起来，让后摄像头进入有光环境。这时就会出现上面的拍摄不清晰，花掉的画面。

**Comment by heavyrain2012** [comment]
这个问题发现什么规律没，有没有解决？请反馈，谢谢
