### ISSUE TITLE
XCode 12 编译报错

### ISSUE THREAD

**Issue by tonycody** [wildfirechat/ios-chat#245]
![image](https://user-images.githubusercontent.com/6773121/93726177-11a0f600-fbe7-11ea-8877-e1095f6b1885.png)

![image](https://user-images.githubusercontent.com/6773121/93726195-3006f180-fbe7-11ea-86ed-0eadcd55182e.png)

![image](https://user-images.githubusercontent.com/6773121/93726208-42812b00-fbe7-11ea-9f62-68d3f62c2f7a.png)

**Comment by heavyrain2012** [comment]
https://mp.weixin.qq.com/s/ZSAX0eHwTlqzLEJWQhTCnw 问题1

**Comment by heavyrain2012** [comment]
最新代码已经修改，请使用最新代码验证
