### ISSUE TITLE
下载项目后，模拟器无法编译

### ISSUE THREAD

**Issue by hongyu49** [wildfirechat/ios-chat#248]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
下载完代码，然后用xcode打开ios-chat.xcworkspace，选中client模拟器编译，编译不通过。选中真机可以编译通过

#### 预期结果
应该模拟器和真机都可以编译通过。

#### 补充条件
是毕现的

#### demo对比结果
就是下载的demo，client模拟器无法编译

**Comment by heavyrain2012** [comment]
Duplicate of #245

**Comment by hongyu49** [comment]
我用xcode10也不行

**Comment by hongyu49** [comment]
xcode11.6编译正常，建议在官网或者首次编译错误说明(必读)里添加说明目前正常的xcdoe版本，便于开发者入口，不然直接卡死在门口了

**Comment by heavyrain2012** [comment]
最新代码已经修改，请使用最新代码验证
