### ISSUE TITLE
删除会话和删除消息无效。删除会话和消息，app已卸载。重装之后，会话和聊天数据仍然可以加载。

### ISSUE THREAD

**Issue by wblzu** [wildfirechat/ios-chat#25]
调用接口
[[WFCCIMService sharedWFCIMService] removeConversation:ws.conversations[indexPath.row].conversation clearMessage:YES];
删除会话和消息，显示成功。
之后删除app，重新run，
然后调接口[[[WFCCIMService sharedWFCIMService] getConversationInfos:@[@(Single_Type), @(Group_Type), @(Channel_Type)] lines:@[@(0), @(1)]] mutableCopy];
或者调接口[[WFCCIMService sharedWFCIMService] getConversationInfo:self.conversation];
仍然返回之前被删除的会话和消息。

**Comment by china23z** [comment]
同问

**Comment by brian80s** [comment]
相同的问题。。。

**Comment by heavyrain2012** [comment]
请参考
http://docs.wildfirechat.cn/faq/general.html#消息无法删除问题

**Comment by YYYYYYYYYYang** [comment]
> 请参考
> [http://docs.wildfirechat.cn/faq/general.html#消息无法删除问题](http://docs.wildfirechat.cn/faq/general.html#%E6%B6%88%E6%81%AF%E6%97%A0%E6%B3%95%E5%88%A0%E9%99%A4%E9%97%AE%E9%A2%98
服务端更新了 但是IOS端还是不行 是否IOS端还需要哪些修改
