### ISSUE TITLE
在项目中饮用 WFChatClient 和WFChatUIKit 项目文件编译后，聊天页面不显示聊天消息内容

### ISSUE THREAD

**Issue by Elbays-Zhang** [wildfirechat/ios-chat#252]
在新建项目中引用 WFChatClient 和WFChatUIKit 项目文件编译生成的库文件后，在聊天页面，不显示聊天内容，但是在聊天布局已经有了，debug view hiearchey 中也是可以看到所有的文字， 比如聊天记录为“你好xxxxx/n 你好”，这个文字不显示，但是行高布局之类是正确的，uikit中xcassets中的图片也都不显示，点开用户资料，发消息之类按钮的文字也不显示 但是功能仍然存在。麻烦请告诉我是什么地方出现了问题呢？是某些地方集成时没有设置么？下面是图片
![WechatIMG5](https://user-images.githubusercontent.com/56579308/94532550-9a1b3880-0270-11eb-8daa-5b63ff3370ba.jpeg)
![WechatIMG6](https://user-images.githubusercontent.com/56579308/94532851-fbdba280-0270-11eb-8934-1d3358482704.jpeg)
![WechatIMG7](https://user-images.githubusercontent.com/56579308/94532879-0302b080-0271-11eb-95f5-103dcf89feb3.jpeg)

**Comment by heavyrain2012** [comment]
应该是kit层的资源没有添加到应用中去，请对比demo

**Comment by Elbays-Zhang** [comment]
> 应该是kit层的资源没有添加到应用中去，请对比demo

我这边刚才尝试了 新建项目，然后里面代码是拷贝demo中的，也是分成三个project，先编译client，然后编译uikit，之后把编译出的fremwork放在应用project中使用，内容完全一样，但是仍然出现了这些问题，请问是某个方面的设置问题么？xcode版本12.0.1

**Comment by Elbays-Zhang** [comment]
> 应该是kit层的资源没有添加到应用中去，请对比demo

感谢 找到问题了，的确少引入了一个资源。谢谢～
