### ISSUE TITLE
语音消息按钮，初次点击录音失败

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/ios-chat#255]
操作说明
聊天页面中，点击按下说话的语音按钮。首次点击，需要获取权限，获取后再次点击按钮进行录音，无论录音时长多长，都会报时长过短。第三次点击按钮，才可以正常录音发送

demo中，无权限时，点击按下说话按钮无响应，需要用户自己去系统权限开启野火的麦克风权限，回到demo中，再次按下说话即可录音。

**Comment by heavyrain2012** [comment]
已经解决，请更新最新代码验证
