### ISSUE TITLE
请提供获取未读消息的方法，

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#256]
请提供获取未读消息的方法：
1、获取未读的消息
2、获取未读 Mention的消息
3、获取未读MentionAll 的消息
请以事件的顺序排序，可以是数组，也可以是最早未读的单条消息，我们需要定位到未读的一条关于@的消息，让其出现在可视界面中。

**Comment by heavyrain2012** [comment]
SDK接口可以根据消息状态来获取消息，如果要获取所有未读消息，可以参数填写未读/mention/mention all（mention和mentionall也算是未读），问题2、3同理
