### ISSUE TITLE
iOS端APNS推送问题

### ISSUE THREAD

**Issue by Bearmond** [wildfirechat/ios-chat#257]
iOS端APP被杀死后，消息通过APNS发送到客户端，客户端打开只有消息发送者和发送内容，如何获取消息所在会话的会话ID和会话类型，或者消息ID也可以

**Comment by Bearmond** [comment]
![image](https://user-images.githubusercontent.com/15085583/97530636-8426a200-19ed-11eb-8958-590360c8d489.png)
如图所示，客户端在后台和进程被杀死后接收到的数据不一致

**Comment by heavyrain2012** [comment]
这些数据在推送服务都有，你们修改一下推送服务，加上你们需要的信息
