### ISSUE TITLE
kFriendRequestUpdated

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#259]
kFriendRequestUpdated的时候，我们需要推送本地消息提醒用户有好友添加请求，但是第一次登陆app时，会出现之前处理过的通知，然后我们使用kSettingUpdated来判断是来判断是否获取最新的设置，但是kSettingUpdated不是每一次登陆都走，无法判断kFriendRequestUpdated通知时最新的还是已处理过的，请提供相应的解决方案

**Comment by heavyrain2012** [comment]
不能用kSettingUpdated来判断是否第一次登录。可以根据好友请求的状态，如果是未读状态，弹出好友请求就行。一般情况下应用在前台时，不需要弹出通知，只需要在通讯录tab上加上未读数字就好了，因为有可能已经远程推送过了，再本地通知就重复了。可以参考微信的设计

**Comment by AliceTTY** [comment]
我们按照这个方来来实行，在登陆成功之后通过clearUnreadFriendRequestStatus 清除未读好友请求数，getUnreadFriendRequestStatus 获取未读好友请求数来判断是否推送消息，但是在第一次登陆的时候，kFriendRequestUpdated会推送不合理的数据，且此时通过getUnreadFriendRequestStatus获取的未读好友也不零，并且推过来的list里面出现了id，获取好友申请里面，有没有该id的信息。请提供新的处理方案

**Comment by heavyrain2012** [comment]
好友请求和消息类似，都是有状态的，用户查看后也是需要清掉所有的未读。当kFriendRequestUpdated，获取到所有未读的请求，时间小于5秒的弹出通知。如果手机不在线会通过推送提醒

**Comment by heavyrain2012** [comment]
可以对比一下我们demo的处理
