### ISSUE TITLE
一个群成员退出群组之后，其他人的这个群的会话列表也被删除了

### ISSUE THREAD

**Issue by LuShanshan633** [wildfirechat/ios-chat#26]
数据库这个群还存在，但是拉取会话列表拉不到这个群

**Comment by heavyrain2012** [comment]
非常感谢找出我们这个很严重的bug，这个bug在协议栈中的，一直都存在，在收到退群的消息时，没有判断是谁退出就把群删了。ios/android协议栈已经更新，请使用最新的server代码配合验证
