### ISSUE TITLE
请提供一个获取searchMessage的总条数

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#262]
请提供一个获取searchMessage的总条数，我们在做搜索功能的时候，有一个关于搜索该内容的总数展示，请提供一个获取searchMessage总条数的方法

**Comment by heavyrain2012** [comment]
搜索是sql语句做的，很难做到一次搜索返回部分内容及总的命中数目。建议做得像微信那些，滚动加载，不显示总数
