### ISSUE TITLE
已读状态有问题

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#264]
1.A与B聊天，A发送两条消息

2.A撤回第一条发送的消息

3.B去读取消息

4.A界面上的消息应该是已读状态，但是实际上还是未读状态

5.A再发送一条消息，两条消息都变成了已读

例：撤回前的两条数据发送时间为：1604930314000，1604930339000
撤回后的发送时间变成了：1604930332016，1604930358273
此时B查看消息，A回调的已读时间为：1604930332016，  
1604930332016 < 1604930358273 导致读取状态为未读，实际上此消息已读

**Comment by heavyrain2012** [comment]
已经解决，请更新到最新版本验证
