### ISSUE TITLE
关于已读消息

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#267]
通过getConversationRead和kMessageReaded获得的关于已读数据，在群聊的时候，请将已踢出群和已退群的id删除，新加入群的id加入都字典里面，时间可以为新成员加入群的时间，这样已读未读状态更准确

**Comment by heavyrain2012** [comment]
这个协议栈不太好处理，建议在UI显示时，同时读取群成员信息，根据群成员信息来处理不在群内的id和新加入群的id
