### ISSUE TITLE
下载最新ios包 编译成功wfclient再编译wfuikit报错

### ISSUE THREAD

**Issue by ey87666** [wildfirechat/ios-chat#268]
mac系统版本10.15.6

xcode版本11.7

![image](https://user-images.githubusercontent.com/32732531/99752751-e4f25780-2b1f-11eb-9d7a-048c2de1ccd4.png)

**Comment by ey87666** [comment]
![image](https://user-images.githubusercontent.com/32732531/99752992-5af6be80-2b20-11eb-914a-e6b31cfe4446.png)
![21605839020_ pic_hd](https://user-images.githubusercontent.com/32732531/99753004-65b15380-2b20-11eb-90c4-77e7424da84f.jpg)

**Comment by heavyrain2012** [comment]
xcode版本太低，请更新到最新测试
