### ISSUE TITLE
删除消息后，刷新后还是能获取到被删除的消息

### ISSUE THREAD

**Issue by CoderJYZhu** [wildfirechat/ios-chat#269]
1.调用删除消息方法 deleteMessage，返回删除成功
2.再次获取会话消息列表 getMessages，还是能获取到被删除的消息

**Comment by heavyrain2012** [comment]
现在无法删除远程消息，删除后，如果开启拉取远程消息功能，还是能把消息从服务上拉回来的。请确认消息是不是通过getRemoteHistoryMessage加载回来的，如果是这个原因需要做个取舍是否要关掉这个功能
