### ISSUE TITLE
能不能加上聊天内容 日期查看. 仿微信这样

### ISSUE THREAD

**Issue by shanggquan** [wildfirechat/ios-chat#270]
## 提issue小提示
能不能加上聊天内容 日期查看. 像微信这样
![WechatIMG24](https://user-images.githubusercontent.com/11956371/100854990-a74ce180-34c4-11eb-9a19-f7c02be9c8ac.jpeg)

**Comment by heavyrain2012** [comment]
可以考虑添加这个功能，需要等一段吧，估计过完春节开始加

**Comment by shanggquan** [comment]
谢谢 等您的消息.

**Comment by heavyrain2012** [comment]
已经添加了，client加上了按照时间获取消息记录的接口，请检查
