### ISSUE TITLE
免打扰设置

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#271]
- (void)setConversation:(WFCCConversation *)conversation
                 silent:(BOOL)silent
                success:(void(^)(void))successBlock
                  error:(void(^)(int error_code))errorBlock
调用此方法设置免打扰时，在第一次打开一个会话，并没有发送或者接受任何消息的情况下，会设置成功，但是此时免打扰状态并没有，有消息发送的情况是正常的

**Comment by heavyrain2012** [comment]
好像是以前的一个bug，更新到最新的SDK试试

**Comment by AliceTTY** [comment]
新下载的sdk还是有这个问题
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wildfirechat/ios-chat"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午3:37
收件人:&nbsp;"wildfirechat/ios-chat"<ios-chat@noreply.github.com&gt;;
抄送:&nbsp;"Alice"<512642546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wildfirechat/ios-chat] 免打扰设置 (#271)





 
好像是以前的一个bug，更新到最新的SDK试试

**Comment by heavyrain2012** [comment]
已解决，请更新最新协议栈测试
