### ISSUE TITLE
关于修改ui后 每次都需要重新编译库然后引入项目的问题

### ISSUE THREAD

**Issue by Elbays-Zhang** [wildfirechat/ios-chat#272]
在每次修改WFChatUIKit 中的某处时，我发现每次修改后 运行项目（或者demo）修改的参数都不生效，需要重新编译后将framework库重新引入项目（或者demo），我在直接下载未改动的demo中同样发现这种情况，请问是什么地方的设置有问题或者需要修改么？希望给个解答，

**Comment by heavyrain2012** [comment]
WFChatUIKit目录下有个xcodebuild.sh脚本，可以在这个脚本添加把生成的库拷贝到你的工程目录的语句，这样当你修改过WFChatUIKit后执行一遍运行，当编译完成后会自动调用这个脚本，这个脚本把库拷贝过去。

**Comment by Elbays-Zhang** [comment]
> WFChatUIKit目录下有个xcodebuild.sh脚本，可以在这个脚本添加把生成的库拷贝到你的工程目录的语句，这样当你修改过WFChatUIKit后执行一遍运行，当编译完成后会自动调用这个脚本，这个脚本把库拷贝过去。

我看了挺多的相关的技术贴，但是用在项目和demo中都不生效。按理说我们不应该每写一句代码，就打包.Framework，再集成到测试项目中看实际效果，您的意思是用在xcodebuild.sh中 添加一条脚本，把文件直接生成到项目路径中么？ 也就是每修改一条代码，就comd+b编译一次自动替换项目中的库文件然后生效这种？

**Comment by heavyrain2012** [comment]
对的，我们就用的这种笨方法，一般可以放到同一个workspace中，然后分别点一次就行。其实应该可以建立显式依赖关系，xcode自动检测是否编译的。但我们没有去深入研究还是用这种办法。
