### ISSUE TITLE
同一张图片 iOS  Android 发送出去显示的大小不一样

### ISSUE THREAD

**Issue by vhuichen** [wildfirechat/ios-chat#275]
iOS 和 Android 发送同一张图片，显示的大小不一样。
建议可以自定义缩略图片的最大宽高

**Comment by heavyrain2012** [comment]
你们可以找到生成缩略图的地方，修改一下生成缩略图图的方法，建议缩略图大小不要超过7K，过大会有各种各样的问题，比如消息接收卡顿或者发送失败

**Comment by vhuichen** [comment]
我直接hook后修改了
