### ISSUE TITLE
旧版本没有缓存“未知类型消息”

### ISSUE THREAD

**Issue by vhuichen** [wildfirechat/ios-chat#276]
步骤1、聊天界面接收到新版本发来的自定义消息，显示“未知类型消息(xxxx)"
步骤2、退出聊天界面，重新进来，“未知类型消息(xxxx)" 不再显示，按理说这个消息还是要显示的

debug看了一下，是因为重新进来无法从数据库拿到“未知类型消息"，这应该是bug吧！

如果一开始不在聊天页面，那么根本就不知道对方发了一条“未知类型消息"

**Comment by vhuichen** [comment]
又试了下，有时候会显示部分“未知类型消息”

**Comment by heavyrain2012** [comment]
跟 https://github.com/wildfirechat/android-chat/issues/498 同一个问题，这个问题关掉，在那边讨论吧
