### ISSUE TITLE
ios 11.4 模拟器运行崩溃

### ISSUE THREAD

**Issue by q240252859** [wildfirechat/ios-chat#277]
## 提issue小提示
dyld`__abort_with_payload:
    0x10d1a7ed4 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x10d1a7ed9 <+5>:  movq   %rcx, %r10
    0x10d1a7edc <+8>:  syscall 
->  0x10d1a7ede <+10>: jae    0x10d1a7ee8               ; <+20>
#### 操作说明
#R
#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是毕现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
已解决，请参考 https://github.com/wildfirechat/ios-chat/commit/ba972c81203dfe1d249ac3be5d9851cc845ab5fc
