### ISSUE TITLE
ZLPhotoBrowser 报错

### ISSUE THREAD

**Issue by xyy112121** [wildfirechat/ios-chat#278]
#### 操作说明
使用最新的demo版本，依次编译client 和uikit 再修改FireChat的bundle identifier ,能够成功编译   

#### 表现现象
闪退 报错如下

dyld: Library not loaded: @rpath/ZLPhotoBrowser.framework/ZLPhotoBrowser
  Referenced from: /private/var/containers/Bundle/Application/D824BD2C-B1DC-49DC-AE4A-58035798BE09/野火IM.app/野火IM
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

#### 补充条件
能显示启动页
然后就直接crash

#### demo对比结果
用的原装的demo，没有改一句代码

**Comment by heavyrain2012** [comment]
这个库是动态库，引入库的时候需要“Embed & Sign"
