### ISSUE TITLE
iOS清除未读数问题

### ISSUE THREAD

**Issue by DigitEdge** [wildfirechat/ios-chat#279]
`- (void)clearUnreadStatus:(WFCCConversation *)conversation DEPRECATED_MSG_ATTRIBUTE("use clearUnreadStatus:lines: instead");`
该方法被标记为已废弃，提示使用`clearUnreadStatus:lines:`代替，但是`clearUnreadStatus:lines:`这个方法清除的是某一类消息的未读数，导致我点开某一个群（或私聊对象），其他群（或私聊对象）的未读消息也被清除。这个是有其他参数或者方法可以控制的吗？lines参数？

**Comment by heavyrain2012** [comment]
这个问题我们查了一下历史，应该是标记错了，那个方法可以使用。被废弃的应该是clearAllUnreadStatus，我们改了，请更新代码
