### ISSUE TITLE
ios推送，pro签证有时会收不到

### ISSUE THREAD

**Issue by yichenlo01** [wildfirechat/ios-chat#28]
使用pro签证的时候，只能收到第一则讯息
之后的讯息就不会再收到推送。

使用过APNS Online Tester来进行推送是没问题的。
有查过PushServer跟IM Server但还不知道问题在哪

**Comment by yichenlo01** [comment]
这边同一只手机注册了满多的帐号
看了DB，有满多笔资料的uuid 跟 token一样
有没有可能是这样造成的?

**Comment by heavyrain2012** [comment]
请debug push服务，检查im服务传递过来的信息（token，环境类型）是否正确，请确实之后告诉我们结果
