### ISSUE TITLE
PC快速登录手机允许之后，换手机顶账号会再次弹出确认登录界面

### ISSUE THREAD

**Issue by LiuGanQQQ** [wildfirechat/ios-chat#280]
#### 操作说明
1.PC点击快速登录
2.手机确认登录
3.换手机顶已登录账号会再次弹出确认登录界面

#### 表现现象
重复弹出确认登录界面（PC实际已登录）

#### 预期结果
不重复弹出确认登录界面

#### 补充条件
必现的，最新版本

#### demo对比结果
表现一致

我看了下demo里面的代码，pc快速登录的消息过来之后，demo里面是判断的90s内就会登录，感觉逻辑不对
可否将消息类型改成存储消息，然后拿到后标为已读，下次判断是否是已读来确定弹不弹出确认登录界面

**Comment by heavyrain2012** [comment]
90秒有点太长，改成60秒比较合适。这个问题产生的概率很低（仅当点完pc快速登录后60秒内换机），产生的后果也很轻微，修改的意义不大还容易产生问题，建议保持现状吧
