### ISSUE TITLE
手机端踢PC端下线延迟较高

### ISSUE THREAD

**Issue by LiuGanQQQ** [wildfirechat/ios-chat#281]
#### 操作说明
手机端踢PC端下线

#### 表现现象
踢下线之后有时候2s左右就会下线，有时候4分30s才会下线，但是切换会话框可以响应下线

#### 预期结果
很快就会下线

#### 补充条件
偶发的，时间不稳定，同样的设备和网络多次验证的结果

#### demo对比结果
和demo表现一致

**Comment by heavyrain2012** [comment]
我们新加了一个命令能够加快服务器踢客户端下线的速度，请更新到最新服务器，然后更新pc客户端
