### ISSUE TITLE
被踢出群聊的用户会话列表没有被删除

### ISSUE THREAD

**Issue by DuJieJerry** [wildfirechat/ios-chat#283]
被踢出群聊的用户会话列表没有被删除，而且再也无法删除。但是安卓版本没有这类问题

**Comment by heavyrain2012** [comment]
是最新版本的SDK吗

**Comment by heavyrain2012** [comment]
微信也是这个逻辑吧，被踢掉的要保留会话。

**Comment by huangxianhui001** [comment]
但是解散群的时候，会话列表的群聊会话会被删掉，我们希望像微信一样，群成员的会话列表还在，只有删除人自己本地删掉，不影响其他人

**Comment by heavyrain2012** [comment]
是的，被踢的保留会话，解散的不保留会话，与微信有点儿不一样。因为我们大多数客户都是要求解散要删除会话的，所以就实现成这样。
