### ISSUE TITLE
更新远程服务端消息

### ISSUE THREAD

**Issue by xyy112121** [wildfirechat/ios-chat#284]
## 提issue小提示
无消息更新，即比如我发送了一个自定义的红包消息，我领取后，只能通过
- (void)updateMessage:(long)messageId
              content:(WFCCMessageContent *)content;
来刷新 本地消息，但是我无法法更新远程消息，导致别人手机上的红包无法修改红包状态

android的我看是有一个onMessageUpdate 的api可以操作，请问一下 ios这边是用哪个API呢？

**Comment by heavyrain2012** [comment]
android和ios都无法更新远程消息。如果有业务状态需要变更，请在业务服务器处理，以红包为例，红包状态要放到红包服务器，一端打开后到红包服务器更新状态，然后通知对方（可以是自定义下消息），对方收到消息去红包服务器更新状态
