### ISSUE TITLE
上传某种类型的文件会直接闪退

### ISSUE THREAD

**Issue by DuJieJerry** [wildfirechat/ios-chat#285]
在上传H5Log 2019-02-22 16.pages这种.pages的文件的时候会出现闪退
![image](https://user-images.githubusercontent.com/8652929/106351865-df806d00-6319-11eb-90d5-efb8a51f89ac.png)

**Comment by DuJieJerry** [comment]
如果不允许的文件，应该回调Fail之类的，不应该直接闪退

**Comment by heavyrain2012** [comment]
使用的是我们最新的SDK吗，更新到最新试试

**Comment by DuJieJerry** [comment]
> 使用的是我们最新的SDK吗，更新到最新试试

您好，是使用最新的 SDK

**Comment by heavyrain2012** [comment]
我们测试是可以的啊，你用我们appstore上的demo测试一下看看

**Comment by heavyrain2012** [comment]
是不是这个文件地址没有权限访问
