### ISSUE TITLE
语音通话和视频通话的耳机、蓝牙问题

### ISSUE THREAD

**Issue by AliceTTY** [wildfirechat/ios-chat#286]
语音通话和视频通话时，我们有一个“声音外发”的功能，可以切换声音是否外放。如果连接了有线/蓝牙耳机，提示：声音已通过有线/蓝牙耳机播放，并显示有线/蓝牙耳机图标，且不可切换其他播放模式。请提供以下几个功能。
1、在手机插入耳机的模式下开启视频，默认声音是听筒，取掉耳机在插入声音会进入耳机。请问这个怎么设置。
2、请增加声音进入耳机的状态。
3、请增加声音连入蓝牙的状态。
4、请给一个连入蓝牙、耳机、普通状态之前切换的监听事件。

**Comment by heavyrain2012** [comment]
已解决，插拔耳机和蓝牙耳机连接断开事件都能正确切换音频输出，添加了事件回调，demo上的处理时耳机插入或蓝牙耳机连接时，speaker按钮不可用。请联系我们更新SDK
