### ISSUE TITLE
iOS 手动断开连接后，无法重连

### ISSUE THREAD

**Issue by vhuichen** [wildfirechat/ios-chat#288]
IM连接成功，过一段时间，检测到断开连接了，此时如果3秒内没有任何状态返回（并且没有连接成功）。
这时我手动调用断开连接的方法，等待3秒后，再手动调用连接方法，然后就无法重连了。

疑问
1、调用断开连接的方法后，底层还会不会重连？我这里后端检测到是依然会重连，不知道会不会是bug
2、调用断开连接的方法后，多久可以调用重连方法？（一开始就是断开连接的，但底层可能自己在重连）

**Comment by vhuichen** [comment]
内部的重连间隔好像是30秒，太长了

**Comment by heavyrain2012** [comment]
1、调用断开连接的方法后，底层还会不会重连？我这里后端检测到是依然会重连，不知道会不会是bug
可能是断开的请求要发过去，你请求的两个参数都是什么值？
2、调用断开连接的方法后，多久可以调用重连方法？（一开始就是断开连接的，但底层可能自己在重连）
这个我们也需要测试一下

你们这么做的原因是什么，是觉得重连太慢来加快速度是吗，还是其它原因

**Comment by vhuichen** [comment]
> 1、调用断开连接的方法后，底层还会不会重连？我这里后端检测到是依然会重连，不知道会不会是bug
> 可能是断开的请求要发过去，你请求的两个参数都是什么值？
> 2、调用断开连接的方法后，多久可以调用重连方法？（一开始就是断开连接的，但底层可能自己在重连）
> 这个我们也需要测试一下
> 
> 你们这么做的原因是什么，是觉得重连太慢来加快速度是吗，还是其它原因

1、断开连接是这个
```
[WFCCNetworkService.sharedInstance disconnect:YES clearSession:NO];
```
2、重连太慢了。而且偶尔连接IM时，会一直处于`kConnectionStatusConnecting`的状态

**Comment by heavyrain2012** [comment]
是不是这个原因 https://mp.weixin.qq.com/s/YY42ZyPQlpvpSi3fMz6IDQ ，把client层更新到最新，如果还有重连慢的问题，给我们抓一下日志分析一下

重连慢的问题我们先等一下再解决，最近任务有点儿多

**Comment by vhuichen** [comment]
> 是不是这个原因 https://mp.weixin.qq.com/s/YY42ZyPQlpvpSi3fMz6IDQ ，把client层更新到最新，如果还有重连慢的问题，给我们抓一下日志分析一下
> 
> 重连慢的问题我们先等一下再解决，最近任务有点儿多

client 已经是最新的了，使用时一直在前台，重连慢是偶现的，目前只发现一次。
退出登录，切换账号后又是没问题的
