### ISSUE TITLE
引用内容丢失

### ISSUE THREAD

**Issue by vhuichen** [wildfirechat/ios-chat#289]
发了一条消息，内容为
~~~
节目就是这么给力1🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃😳😳😳😳😳😳😳😳😯😊😊😊😭😭😭😭😭😭😭😭😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉
~~~
引用这条消息，退出聊天窗口后再次进来，引用的内容丢失了。

测试发现较短的引用文本是没问题的，但这条文本必现。

APP 是从商店下载的最新的APP

**Comment by heavyrain2012** [comment]
已修正，请参考 https://github.com/wildfirechat/ios-chat/commit/675cd8df46ec37e099f8ca5d91fc54be65dbaef7
