### ISSUE TITLE
断开网络连接，IM 不能很快的返回连接状态

### ISSUE THREAD

**Issue by DigitEdge** [wildfirechat/ios-chat#290]
不管是监听kConnectionStatusChanged通知，还是使用ConnectionStatusDelegate中的onConnectionStatusChanged：方法，当我连接上 IM 之后，断开手机网络连接，要过很久才会收到连接状态改变的反馈。

**Comment by DigitEdge** [comment]
> 不管是监听kConnectionStatusChanged通知，还是使用ConnectionStatusDelegate中的onConnectionStatusChanged：方法，当我连接上 IM 之后，断开手机网络连接，要过很久才会收到连接状态改变的通知。

Android 同事那边断开网络后马上就收到了连接状态反馈

**Comment by heavyrain2012** [comment]
已经解决，请检查 https://github.com/wildfirechat/ios-chat/commit/d730c246bf3562bbabd0c95ea6b0e54592bcb234
