### ISSUE TITLE
通过服务端发消息ios端收到消息为os端WFCCPTextMessageContent

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/ios-chat#291]
#### 操作说明
通过服务器端发送消息（我们期望的消息是不计入聊天列表），IOS端收到消息时类型不是期望类型。

#### 表现现象
通过服务器端消息发送代码进行发消息代码如下：
![image](https://user-images.githubusercontent.com/8434253/110884640-5e58c480-8320-11eb-998b-cd60eed93b93.png)
我们尝试设置setPersistFlag=0 来标记该消息不计入聊天列表。type 为9表示自定义业务
前端收到消息：
![image](https://user-images.githubusercontent.com/8434253/110884939-e17a1a80-8320-11eb-93f6-2e1b06022cf5.png)
![image](https://user-images.githubusercontent.com/8434253/110884987-fd7dbc00-8320-11eb-835c-c099d6397cb6.png)

#### 预期结果
预期得到的消息类为WFCCTextMessageContent，我们期望通过后台服务器向前端发送一种可以不用显示的消息，去执行我们的一些动作

#### 提问
请问在什么情况下是WFCCPTextMessageContent，什么情况下是WFCCTextMessageContent？
当收到这种类型的消息，虽然可以解析，但是会计入消息列表，请问是否我们使用的发送消息代码有什么问题，或者前端处理有问题？

**Comment by heavyrain2012** [comment]
自定义消息类型请使用1000以上，客户端需要注册消息，把自定义消息类型注册后，客户端收到payload就能转换为自定义消息内容。所以：
1，修改自定义消息类型1000以上。
2，客户端定义消息内容，并***注册***
