### ISSUE TITLE
关于重连的问题

### ISSUE THREAD

**Issue by vhuichen** [wildfirechat/ios-chat#293]
我测试发现SDK内部的重连间隔是30秒，太长了。所以我自己做了一个重连，步骤如下：

1、发现断开连接并且没有任何状态返回，等待至少3秒以上，再手动调用SDK的断开连接的方法
2、手动断连3秒后，我再手动重新连接

这时候发现SDK一直返回 `-1` 的状态码回来，并且后端没有接受到SDK的任何连接请求
这个问题可以优化下吗？

**Comment by heavyrain2012** [comment]
建议不要尝试自己重连，因为底层的重连用的是mars默认的方式，应该是最合适的。mars默认重连应该是重连间隔不断加长的，不是第一次就是30s。请检查什么情况连不上，我们来分析一下
