### ISSUE TITLE
运行时 Could not build module 'WFChatUIKit'

### ISSUE THREAD

**Issue by wrp9411** [wildfirechat/ios-chat#296]
<img width="473" alt="图片" src="https://user-images.githubusercontent.com/82071880/113803066-5f014100-978e-11eb-85bc-04dcb95125a7.png"> 运行时一直找不到这个文件，有人知道什么情况吗

**Comment by heavyrain2012** [comment]
先编译chatclient，再编译chatuikit，最后再编译chat
