### ISSUE TITLE
偶现崩溃问题

### ISSUE THREAD

**Issue by vhuichen** [wildfirechat/ios-chat#298]
![image](https://user-images.githubusercontent.com/12621313/117792533-f3732d80-b27d-11eb-8f1c-44a467a747ad.png)

一种有规律情况就是进入后台一段时间后，再次进入前台，崩溃。
有时候就是用着用着就崩溃了，这两者都报了同一个堆栈。

我测试发现就算不connect，甚至不设置IP地址,调用SDK的接口也不会崩溃。或者disconnect后，再次调用SDK的接口也不会崩溃。
所以我很难断定究竟是哪里出了问题。可能是我的使用方式有问题，但至少不应该直接崩溃。

或者你们能否做一些异常处理，或者可以将异常返回给应用。

**Comment by heavyrain2012** [comment]
您好，请确认协议栈的日期

**Comment by vhuichen** [comment]
#ifndef Mars_verinfo_h
#define Mars_verinfo_h

#define MARS_REVISION "77de0332"
#define MARS_PATH "firechat"
#define MARS_URL ""
#define MARS_BUILD_TIME "2021-02-22 16:00:04"
#define MARS_TAG ""

#endif

**Comment by heavyrain2012** [comment]
已针对此问题添加了代码保护，请更新最新协议栈验证
