### ISSUE TITLE
取消群管理无效

### ISSUE THREAD

**Issue by LuShanshan633** [wildfirechat/ios-chat#30]
取消某个成员的管理员之后，拉取群成员信息的type没有改变

**Comment by heavyrain2012** [comment]
已经解决，请clone下来最新的iOS和Server代码进行验证

**Comment by qiu198022** [comment]
这个问题确定解决了吗？我今天用最新的ios和server的代码进行验证，还是出现了这个问题！之前拉进去的2个管理员移除之后，mysql数据库还是type=1

**Comment by heavyrain2012** [comment]
@qiu198022 请详细描述一下问题复现步骤

**Comment by heavyrain2012** [comment]
@qiu198022 请使用最新代码验证
