### ISSUE TITLE
iOS端发送消息 -10087错误

### ISSUE THREAD

**Issue by Bearmond** [wildfirechat/ios-chat#301]
iOS端发送图片和视频信息，发送失败，错误码为-10087

**Comment by heavyrain2012** [comment]
请检查配置文件中端口的配置，端口应该是80，不是9000

**Comment by Bearmond** [comment]
目前PC端和Android端都正常，iOS端使用野火服务配置server host的时候并没有指定端口。是需要参照Demo配置8888，还是需要指定为80？目前iOS发送文本消息没有任何问题，只有在发送图片、视频这类消息有错误码为-10087的问题。





------------------ 原始邮件 ------------------
发件人: heavyrain.lee ***@***.***&gt;
发送时间: 2021年7月3日 20:39
收件人: wildfirechat/ios-chat ***@***.***&gt;
抄送: Amon ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[wildfirechat/ios-chat] iOS端发送消息 -10087错误 (#301)





 
请检查配置文件中端口的配置，端口应该是80，不是9000

**Comment by heavyrain2012** [comment]
是IM服务的问题，让服务器查一下 IM服务配置文件中对象存储服务配置有没有端口的配置

**Comment by Bearmond** [comment]
那么为什么PC端和Android端没有问题呢？





------------------ 原始邮件 ------------------
发件人: heavyrain.lee ***@***.***&gt;
发送时间: 2021年7月3日 20:51
收件人: wildfirechat/ios-chat ***@***.***&gt;
抄送: Amon ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[wildfirechat/ios-chat] iOS端发送消息 -10087错误 (#301)





 
是IM服务的问题，让服务器查一下 IM服务配置文件中对象存储服务配置有没有端口的配置

**Comment by heavyrain2012** [comment]
iOS/Android/PC 使用的是同一个协议栈，理论上行为应该完全一致才对，但可能每个端使用的都是不同的版本，所以行为上会有区别。这个问题是IM服务配置问题，让服务端同事查一下吧

**Comment by Bearmond** [comment]
好的，感谢





------------------ 原始邮件 ------------------
发件人: heavyrain.lee ***@***.***&gt;
发送时间: 2021年7月4日 18:14
收件人: wildfirechat/ios-chat ***@***.***&gt;
抄送: Amon ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[wildfirechat/ios-chat] iOS端发送消息 -10087错误 (#301)





 
iOS/Android/PC 使用的是同一个协议栈，理论上行为应该完全一致才对，但可能每个端使用的都是不同的版本，所以行为上会有区别。这个问题是IM服务配置问题，让服务端同事查一下吧
