### ISSUE TITLE
iOS14杀死APP时,接收不到音视频通知

### ISSUE THREAD

**Issue by luoyunqing-git** [wildfirechat/ios-chat#304]
接听音视频电话的app处于线程被杀死的状态
1.iOS14运行的APP,发音视频电话给iOS12.5运行的APP,可以接收到声音文字提醒
1.iOS12.5运行的APP,发音视频电话给iOS14运行的APP,不能接收到声音文字提醒
下载的demo也是同样状况

**Comment by heavyrain2012** [comment]
音视频通知主要的问题是政策问题，请选择适合你们的推送方式，然后去在推送服务和客户端实现。请参考链接 https://docs.wildfirechat.cn/blogs/iOS音视频通知的处理.html
