### ISSUE TITLE
ios/android  会存在话消息丢失，加载历史也拉不出来？

### ISSUE THREAD

**Issue by amumuku** [wildfirechat/ios-chat#308]
#### 操作说明
打开应用

#### 表现现象
现在情况 大致这样 同一个账号：【ios/android 一样的场景】以 ios 进程退出后 ，android正常 打开着为例，
一段时间后，群里不停的发消息，android 正常，ios重新进，会丢一部分消息;

#### 预期结果
android 不丢消息

#### 补充条件
偶现

**Comment by heavyrain2012** [comment]
有没有更多更详细的信息提供，截图录像也行

**Comment by heavyrain2012** [comment]
没有回复，先关闭，如果有新情况请重新open或者新提issue
