### ISSUE TITLE
项目是Swift版本，集成后报 can not build Module

### ISSUE THREAD

**Issue by huainanzi** [wildfirechat/ios-chat#309]
项目是Swift版本，集成后报 can not build Module

**Comment by 740629515** [comment]
我也是这个问题诶, 话说大佬怎么解决的啊?

**Comment by huainanzi** [comment]
> 我也是这个问题诶, 话说大佬怎么解决的啊?

你的也是在bridge中添加报错的吗？老版本不会，新的master有问题

**Comment by 740629515** [comment]
是的啊,Could not build module 'WFChatUIKit'

**Comment by huainanzi** [comment]
> 是的啊,Could not build module 'WFChatUIKit'

是的，我也是今天集成遇到，找不到问题。

**Comment by 740629515** [comment]
你之前也是用这个库的吗? im是部署在自己服务器上的吗

**Comment by huainanzi** [comment]
> 你之前也是用这个库的吗? im是部署在自己服务器上的吗

老哥，怎么样，报错解决了吗

**Comment by heavyrain2012** [comment]
请参考示例项目 https://github.com/wildfirechat/WFSwiftDemo 注意项目中的SDK比较旧了，可以找到集成方法后更新到最新SDk

**Comment by huainanzi** [comment]
> 请参考示例项目 https://github.com/wildfirechat/WFSwiftDemo 注意项目中的SDK比较旧了，可以找到集成方法后更新到最新SDk

不是的，你可以把这个WFSwiftDemo中的Frameworks换成最新的master中的SDK,同样会报错

**Comment by heavyrain2012** [comment]
已经更新SDK，请重试

**Comment by 740629515** [comment]
> 已经更新SDK，请重试

现在可以了
