### ISSUE TITLE
野火IM IOS SDK发送图片在苹果手机空白

### ISSUE THREAD

**Issue by xtweng** [wildfirechat/ios-chat#313]
IM APP在新MAC系统上面打包过的，但是出现发送图片空白的情况。旧版本mac机器上打包不会出现。请问是否有解决方法？ 

![1628840952(1)](https://user-images.githubusercontent.com/3360890/129323225-3582a87f-ae93-4b18-9772-bdefd33b29f9.png)

![image](https://user-images.githubusercontent.com/3360890/129317723-73297735-e774-4c04-862c-c9fd52560bc1.png)

**Comment by heavyrain2012** [comment]
显示图片是UI层的代码，你们连上xcode debug看一下，看看图片地址是多少，为什么没有显示出来图片
