### ISSUE TITLE
群组拉人出错

### ISSUE THREAD

**Issue by LuShanshan633** [wildfirechat/ios-chat#32]
踢人之后再重新拉人，没有拉成功，拉第二次才会成功，发送了两条通知
![image](https://user-images.githubusercontent.com/8368530/61179934-21ff2d80-a640-11e9-941e-b8c6e1e63808.png)

**Comment by LuShanshan633** [comment]
重复踢人拉人成员显示不正确

**Comment by heavyrain2012** [comment]
现在是否正确了，请确认
