### ISSUE TITLE
聊天页面发送长图，会被截断

### ISSUE THREAD

**Issue by magic-geng** [wildfirechat/ios-chat#326]
#### 操作说明
进入聊天会话页面，发送图片消息时，选择一张长图，发送成功之后，显示的图片会被截断。

#### 预期结果
预期结果，不应该被截断。

#### 补充条件
必现，最新的sdk。

#### demo对比结果
demo也是如此

**Comment by heavyrain2012** [comment]
1，截断的是缩略图还是点开查看的大图？
2，用最新的代码编译安装测试一下看看demo有没有问题？

请确认上述两个问题
