### ISSUE TITLE
.txt文件消息，上传后获取的链接乱码

### ISSUE THREAD

**Issue by CoderJYZhu** [wildfirechat/ios-chat#327]
消息聊天，发送.txt文件，上传后台后获取到的文件链接打开显示乱码，如：http://imdev.****.cn/fs/4/2021/11/08/16/f0e7b98d4ccc4152bf171fb7df084af5-4-1636360314-Ic6K8cjJWCN8.txt

**Comment by heavyrain2012** [comment]
这个文件我们看了一下，是unicode格式的，我们尝试着把文件上传到七牛和我们的minio服务，浏览器打开也是同样的乱码。检查发现都是因为没有正确的编码，浏览器是支持修改编码的，改成unicode就能正确显示了。为什么对象服务存储都不支持格式，原因是文本文件没有所谓的头文件来指定内容，也就无法区分到底是什么格式，所以就只能让浏览器来根据自己的设置来显示某种格式了。所以这个问题无解，只能让用户发送有格式的文件，比如word文件，或者手动调一下浏览器的编码
