### ISSUE TITLE
手机加入会议后，正常是手机外放出声，连上耳机，此时耳机正常听见其他人说话。然后断开耳机，就变成了手机听筒出声，应该还是切换回外放

### ISSUE THREAD

**Issue by Charlie191011** [wildfirechat/ios-chat#328]
手机加入会议后，正常是手机外放出声，连上耳机，此时耳机正常听见其他人说话。然后断开耳机，就变成了手机听筒出声，应该还是切换回外放；

拔插设备时，需要根据系统当时的默认设备，自动切换

**Comment by heavyrain2012** [comment]
最新版本已经解决了，等下次给你们发布版本再验证
