### ISSUE TITLE
iOS客户端 可以新增一个配置为：是否自动拉去历史远程会话的设置么？

### ISSUE THREAD

**Issue by 794341379** [wildfirechat/ios-chat#33]
iOS客户端 可以新增一个配置为：是否自动拉去历史远程会话的设置么？
在需求中，第一次下载APP，仿照微信一样，不拉取历史会话。

**Comment by heavyrain2012** [comment]
Duplicate of #42

**Comment by heavyrain2012** [comment]
在服务端实现了，请参考
http://docs.wildfirechat.cn/faq/general.html#消息无法删除问题
