### ISSUE TITLE
WFAVEngineKit.framework 不支持BitCode

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#330]
## 提issue小提示
ld: warning: directory not found for option '-F/Users/ice/Desktop/work/云在/App/ios-chat/Classes/Moments'
ld: '/Users/ice/Desktop/work/云在/App/ios-chat/wfchat/Frameworks/WFAVEngineKit.framework/WFAVEngineKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/ice/Desktop/work/云在/App/ios-chat/wfchat/Frameworks/WFAVEngineKit.framework/WFAVEngineKit' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### 操作说明
真机编译

#### 表现现象
编译失败， WFAVEngineKit.framework/WFAVEngineKit' does not contain bitcode

#### 预期结果
编译成功

**Comment by heavyrain2012** [comment]
音视频SDK和WebRtc的库不支持bitcode，请关掉bitcode再打包。如果像去掉实时音视频功能，可以移除这两个库，再找到到开关WFCU_SUPPORT_VOIP，把这个开关关掉就可以支持bitcode了
