### ISSUE TITLE
shareExtension 使用问题chatclient 问题

### ISSUE THREAD

**Issue by Michael-lu-ke** [wildfirechat/ios-chat#331]
能在demo里边添加一下用法吗

**Comment by Michael-lu-ke** [comment]
项目中添加 shareExtension 之后，调用chatclient里边的方法都报错，用户信息保存到app group里边，然后在 shareExtension 中调用connect方法也不成功

**Comment by heavyrain2012** [comment]
shareExtension与宿主App是隔离的，如果在shareExtension中连接，就会引起多端问题，因此无法在Extension中正常使用ChatClient。可以参考我们demo中的实现，shareExtension中调用appserver来上传媒体文件和发送消息
