### ISSUE TITLE
苹果 APNS 后台配置如何配置？

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#332]
## 提issue小提示
https://docs.wildfirechat.cn/quick_start 这里未找到相关服务器后台如何配置APNS的地方，哪里有相关的文档呢？

#### 预期结果
正确配置后端APNS 证书，正常接收推送信息

**Comment by heavyrain2012** [comment]
请检查：
1. https://docs.wildfirechat.cn/server/push_config.html
2. https://github.com/wildfirechat/push_server
