### ISSUE TITLE
发送接收的图片比例显示异常

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#333]
#### 操作说明
1、发送图片前会对图片进行按比例裁剪 （因为使用的是原图大小，按比例缩放，这个是正确的）
+ (instancetype)contentFrom:(UIImage *)image cachePath:(NSString *)path fullImage:(BOOL)fullImage {
    WFCCImageMessageContent *content = [[WFCCImageMessageContent alloc] init];
    
    if(!fullImage) {
        image = [WFCCUtilities image:image scaleInSize:CGSizeMake(1024, 1024)];
    }
    
    NSData *imgData = UIImageJPEGRepresentation(image, 0.9);
    [imgData writeToFile:path atomically:YES];
    
    content.localPath = path;
    content.size = image.size;
    UIImage *thumbnailImage = [WFCCUtilities generateThumbnail:image withWidth:141 withHeight:141];
    
    content.thumbnail = thumbnailImage;
    NSLog(@"<==> 发送方图片尺寸: content.size = %@, thumbnailsize = %@ path = %@",NSStringFromCGSize(content.size), NSStringFromCGSize(thumbnailImage.size), path);
    return content;
}
2、发送的时候会把图片上传（关于尺寸等信息是否有上传，如何上传的不清楚，为看到相关的文档，只看到有个 thumbParameter 属性，但是不知道如何使用）
3、显示的时候，图片的大小逻辑如下
+ (CGSize)sizeForClientArea:(WFCUMessageModel *)msgModel withViewWidth:(CGFloat)width {
    WFCCImageMessageContent *imgContent = (WFCCImageMessageContent *)msgModel.message.content;
    CGSize size = CGSizeMake(141, 141);
    UIImage *thumbnailImage = imgContent.thumbnail;
    NSLog(@"<==> 接收方图片尺寸: content.size = %@, thumbnailsize = %@",NSStringFromCGSize(imgContent.size), NSStringFromCGSize(thumbnailImage.size));
    if(thumbnailImage) {
        size = thumbnailImage.size;
    } else {
        size = [WFCCUtilities imageScaleSize:imgContent.size targetSize:CGSizeMake(141, 141) thumbnailPoint:nil];
    }
    
    
    if (size.height > width || size.width > width) {
        float scale = MIN(width/size.height, width/size.width);
        size = CGSizeMake(size.width * scale, size.height * scale);
    }
    return size;
}

 - (void)setModel:(WFCUMessageModel *)model {
    [super setModel:model];
    
    WFCCImageMessageContent *imgContent = (WFCCImageMessageContent *)model.message.content;
    self.thumbnailView.frame = self.bubbleView.bounds;
    if (!imgContent.thumbnail && imgContent.thumbParameter) {
        [self.thumbnailView sd_setImageWithURL:[NSURL URLWithString:[[NSString stringWithFormat:@"%@?%@", imgContent.remoteUrl, imgContent.thumbParameter] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]]];
    } else {
        self.thumbnailView.image = imgContent.thumbnail;
    }
}

（1）图片大小根据   self.thumbnailView.frame = self.bubbleView.bounds; 来设置
（2）bubbleView 大小根据缩略图大小来设置，此时 缩略图的大小跟上传时候裁剪的大小不一致了，导致显示异常
因聊天数据加载逻辑部分在mars中黑盒，无法了解到，所以无法修改

#### 表现现象
发送接收的同一张照片，显示的大小不一致

#### 预期结果
1、发送接收的图片缩放比例一致，显示正常
2、关于缩略图的参数设置如何设置

- (WFCCMessagePayload *)encode {
    WFCCMediaMessagePayload *payload = [[WFCCMediaMessagePayload alloc] init];
    payload.extra = self.extra;
    payload.contentType = [self.class getContentType];
    payload.searchableContent = @"[图片]";
    
    NSMutableDictionary *dataDict = [NSMutableDictionary dictionary];
    if (self.thumbParameter.length && self.size.width > 0) {
        [dataDict setValue:self.thumbParameter forKey:@"tp"];
        [dataDict setValue:@(self.size.width) forKey:@"w"];
        [dataDict setValue:@(self.size.height) forKey:@"h"];
    } else if (![[WFCCIMService sharedWFCIMService] imageThumbPara]) {
        dataDict = nil;
        payload.binaryContent = UIImageJPEGRepresentation(self.thumbnail, 0.45);
    } else {
        UIImage *image = [UIImage imageWithContentsOfFile:self.localPath];
        if (image) {
            [dataDict setValue:[[WFCCIMService sharedWFCIMService] imageThumbPara] forKey:@"tp"];
            [dataDict setValue:@(image.size.width) forKey:@"w"];
            [dataDict setValue:@(image.size.height) forKey:@"h"];
        } else {
            payload.binaryContent = UIImageJPEGRepresentation(self.thumbnail, 0.45);
            dataDict = nil;
        }
    }
    
    if (dataDict) {
        NSData *data = [NSJSONSerialization dataWithJSONObject:dataDict
                                                       options:kNilOptions
                                                         error:nil];
        payload.content = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    }
    
    payload.mediaType = Media_Type_IMAGE;
    payload.remoteMediaUrl = self.remoteUrl;
    payload.localMediaPath = self.localPath;
    return payload;
}

thumbParameter  imageThumbPara 格式如何使用？
（1）thumbParameter 看起来是本地配置的一个字符串，格式是什么？
（2）imageThumbPara 看mars 头文件猜测是通过后端配置的，如何配置？

**Comment by heavyrain2012** [comment]
thumbParameter和imageThumbPara是废弃的参数，请忽略掉，这两个参数应该为空，代码不应该走到跟这两个参数有关的代码去。
在会话中显示的是缩略图，请确认显示不同时，缩略图大小是否一致，以及缩略图的来源在哪里

**Comment by LengYi** [comment]
发送时是从本地读取的缩略图，然后将其2进制流发送至服务器端。读取是直接从 mars里面读的，这部分代码没开源，无法看到逻辑，外面接收到时，缩略图尺寸大小已经不一样了。

**Comment by heavyrain2012** [comment]
媒体消息encode后的messagepayload在服务器和协议栈是透传的。也就是说图片消息encode的payload发到对端是没有改变的，你可以debug看一下

**Comment by LengYi** [comment]
> 媒体消息encode后的messagepayload在服务器和协议栈是透传的。也就是说图片消息encode的payload发到对端是没有改变的，你可以debug看一下

经过测试，发现  
payload.binaryContent = UIImageJPEGRepresentation(self.thumbnail, 0.45);
UIImage *thumbnailImage = [UIImage imageWithData:payload.binaryContent];

UIImageJPEGRepresentation 经过该方法压缩之后，再次读取图片，图片尺寸就变大了，暂时没有找到更好的压缩图片尺寸保持不变的方法。

**Comment by heavyrain2012** [comment]
感觉不太可能吧，我们测试了在UIImageJPEGRepresentation函数前打印出来大小，然后再把函数返回的data再转回图片打印大小，测试都是一样的，测试代码如下

        NSLog(@"image size before convert to data (%f,%f)", self.thumbnail.size.width, self.thumbnail.size.height);
        payload.binaryContent = UIImageJPEGRepresentation(self.thumbnail, 0.45);
        UIImage *restored = [UIImage imageWithData:payload.binaryContent];
        NSLog(@"image from data size is (%f,%f)", restored.size.width, restored.size.height);
