### ISSUE TITLE
打包上传AppStore后台报错

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#335]
<img width="832" alt="上传AppStore报错" src="https://user-images.githubusercontent.com/5643730/144185896-cdc72c73-3644-46cf-928c-458e22fdbf1d.png">

**Comment by heavyrain2012** [comment]
上架需要移除模拟器架构，可以从网上搜索一下怎么去除，demo代码下有个脚本removex86也可以参考
