### ISSUE TITLE
请问集成了chatuikit, 这里面的内容我怎么自定义呢?

### ISSUE THREAD

**Issue by 740629515** [wildfirechat/ios-chat#336]
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-12-01 at 17 06 33](https://user-images.githubusercontent.com/17950169/144204954-397ebb64-583f-45b1-9660-dd464f6fec8b.png)
#

**Comment by heavyrain2012** [comment]
可以修改chatuikit的源码进行修改
