### ISSUE TITLE
创建群聊头像

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#337]
## 提issue小提示
创建群聊，群头像是在mars SDK中处理的吗？还是后端生成的群头像，iOS客户端未看到对应处理的源码

#### 预期结果
能自己处理群头像

**Comment by heavyrain2012** [comment]
client层生成的，对应代码是开源的，您再找找看

**Comment by LengYi** [comment]
> 

一、创建群调用的是以下接口, 传入群名称(本地拼接的), 图片为空
  [[WFCCIMService sharedWFCIMService] createGroup:nil name:name portrait:nil type:GroupType_Restricted groupExtra:nil members:memberIds memberExtra:extraStr notifyLines:@[@(0)] notifyContent:nil success:^(NSString *groupId) {
        NSLog(@"create group success");
        
        WFCUMessageListViewController *mvc = [[WFCUMessageListViewController alloc] init];
        mvc.conversation = [[WFCCConversation alloc] init];
        mvc.conversation.type = Group_Type;
        mvc.conversation.target = groupId;
        mvc.conversation.line = 0;
        
        mvc.hidesBottomBarWhenPushed = YES;
        UINavigationController *nav = self.navigationController;
        [self.navigationController popToRootViewControllerAnimated:NO];
        [nav pushViewController:mvc animated:YES];
        
    } error:^(int error_code) {
        NSLog(@"create group failure");
        [ws.view makeToast:WFCString(@"CreateGroupFailure")
                  duration:2
                  position:CSToastPositionCenter];
        
    }];

二、之后调用mars接口 图片为空
- (void)createGroup:(NSString *)groupId
               name:(NSString *)groupName
           portrait:(NSString *)groupPortrait
               type:(WFCCGroupType)type
         groupExtra:(NSString *)groupExtra
            members:(NSArray *)groupMembers
        memberExtra:(NSString *)memberExtra
        notifyLines:(NSArray<NSNumber *> *)notifyLines
      notifyContent:(WFCCMessageContent *)notifyContent
            success:(void(^)(NSString *groupId))successBlock
              error:(void(^)(int error_code))errorBlock {

    std::list<std::string> memberList;
    for (NSString *member in groupMembers) {
        memberList.push_back([member UTF8String]);
    }
    mars::stn::TMessageContent tcontent;
    fillTMessageContent(tcontent, notifyContent);
    
    std::list<int> lines;
    for (NSNumber *number in notifyLines) {
        lines.push_back([number intValue]);
    }
    mars::stn::createGroup(groupId == nil ? "" : [groupId UTF8String], groupName == nil ? "" : [groupName UTF8String], groupPortrait == nil ? "" : [groupPortrait UTF8String], (int)type, groupExtra == nil ? "" : [groupExtra UTF8String], memberList, memberExtra == nil ? "" : [memberExtra UTF8String], lines, tcontent, new IMCreateGroupCallback(successBlock, errorBlock));
}

并未看到群头像，本地处理的代码，如果要自定义群头像，是把本地的图片地址传入 groupPortrait 吗？

**Comment by heavyrain2012** [comment]
创建群时，传入groupPortrait参数，这样群组信息里的头像链接就是你传入的。如果不传入这个参数，群组的头像链接就是空的。

在UI层显示时检查群组信息里头像链接存在不，如果存在就显示群组信息里的，如果不存在则会根据群组成员自动拼接，请检查client层的WFCCUtilities对象的下面这个方法
```
+ (NSString *)getGroupGridPortrait:(NSString *)groupId
                             width:(int)width
                generateIfNotExist:(BOOL)generateIfNotExist
               defaultUserPortrait:(UIImage *(^)(NSString *userId))defaultUserPortraitBlock;
```

**Comment by LengYi** [comment]
> 
已找到客户端创建群头像的地方，但是创建完并没有上传头像至后端，安卓部分创建完群里就上传了群头像，如果要上传群头像，使用啥接口呢？

**Comment by LengYi** [comment]
> > 
> 
> 已找到客户端创建群头像的地方，但是创建完并没有上传头像至后端，安卓部分创建完群里就上传了群头像，如果要上传群头像，使用啥接口呢？

创建群的时候 是通过 [[WFCCIMService sharedWFCIMService] createGroup:nil name:name portrait:portrait type:GroupType_Restricted groupExtra:nil members:memberIds memberExtra:extraStr notifyLines:@[@(0)] notifyContent:nil success:^(NSString *groupId)      portrait 参数上传的群头像，但是这个 portrait 应该是

**Comment by LengYi** [comment]
> 
使用以下接口上传图片，获取到 图片url地址再创建群聊
  [[WFCCIMService sharedWFCIMService] modifyMyInfo:@{@(Modify_Portrait):remoteUrl} success:^{
      dispatch_async(dispatch_get_main_queue(), ^{
        [ws.portraitView sd_setImageWithURL:[NSURL URLWithString:[remoteUrl stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]] placeholderImage:previousImage];

          [ws.view makeToast:WFCString(@"UpdateDone")];
      });
    } error:^(int error_code) {
      dispatch_async(dispatch_get_main_queue(), ^{
          [ws.view makeToast:WFCString(@"UpdateFailure")];
      });
    }];

**Comment by LengYi** [comment]
> > 
> 
> 使用以下接口上传图片，获取到 图片url地址再创建群聊  [[WFCCIMService sharedWFCIMService] uploadMedia:nil
                                                  mediaData:portraitData mediaType:Media_Type_PORTRAIT success:^(NSString *remoteUrl)

**Comment by heavyrain2012** [comment]
> 使用以下接口上传图片，获取到 图片url地址再创建群聊 [[WFCCIMService sharedWFCIMService] uploadMedia:nil
> mediaData:portraitData mediaType:Media_Type_PORTRAIT success:^(NSString *remoteUrl)

对使用这个上传，再修改群组的头像信息。不过我们现在推荐的做法是不上传头像，当头像为空时，显示时使用群成员头像拼接出来群头像

**Comment by LengYi** [comment]
> > 使用以下接口上传图片，获取到 图片url地址再创建群聊 [[WFCCIMService sharedWFCIMService] uploadMedia:nil
> > mediaData:portraitData mediaType:Media_Type_PORTRAIT success:^(NSString *remoteUrl)
> 
> 对使用这个上传，再修改群组的头像信息。不过我们现在推荐的做法是不上传头像，当头像为空时，显示时使用群成员头像拼接出来群头像

如果不上传群头像  1、别人扫群二维码时，将无法看到群头像 2、此时是没有办法本地拼接群头像的，因为经过测试没入群拿不到群成员信息

**Comment by heavyrain2012** [comment]
确实是个问题，我们考虑一下

**Comment by heavyrain2012** [comment]
解决办法是在应用服务提供一个接口，可以获取群内前9个人的头像url，客户端根据这9个url来拼接群头像。请参考 https://github.com/wildfirechat/im-app_server/blob/master/src/main/java/cn/wildfirechat/app/AppController.java 中的getGroupMembersForPortrait方法，客户端代码中也能根据这个方法的路径找到对应的代码
