### ISSUE TITLE
如何关闭陌生人聊天功能

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#338]
## 提issue小提示
后端有个配置可以关闭陌生人聊天，关闭后，App端获取群相关信息，groupInfo.privateChat 值还是为 0 允许默认人聊天

#### 预期结果
初始创建的群，关闭 陌生人聊天，返回的标记是正确的

**Comment by heavyrain2012** [comment]
后端配置关闭陌生人聊天是指两个人不是好友时是否可以聊天，如果关闭，则只有好友才可以聊天，这跟groupInfo.privateChat无关
