### ISSUE TITLE
请问一下，如果群里有3个人，a发了1条消息，b发了2条消息，c收到的未读是3条。但是我只想接受b的未读数，即我只想收到未读为2。a的未读数不加入到里面这样可以吗？但是能看到a发的消息

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#339]
请问一下，如果群里有3个人，a发了1条消息，b发了2条消息，c收到的未读是3条。但是我只想接受b的未读数，即我只想收到未读为2。a的未读数不加入到里面这样可以吗？但是能看到a发的消息

**Comment by heavyrain2012** [comment]
无法做到，因为计数是计算群里的所有消息的未读，没有办法针对某个人的技术
