### ISSUE TITLE
iphone12 pro系统15.2手机共享异常

### ISSUE THREAD

**Issue by liminting** [wildfirechat/ios-chat#340]
多台苹果手机进入会议，iphone12 pro系统15.2手机开启共享屏幕

#### 表现现象
其他与会人员可以看到共享者第一帧画面后一直不动，无法实时看到共享者操作

#### 预期结果
与会人员都可以正常实时观看共享画面
#### 补充条件
在iphone 12 pro 系统15.2手机上必现，其他类型手机没有发现这个问题。
#### demo对比结果
Demo测试效果一样

**Comment by heavyrain2012** [comment]
最新添加了直播功能，直播功能应该没有问题
