### ISSUE TITLE
iOS 消息缓存的DB格式是什么，使用什么可视化工具打开查看？

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#343]
文档说 https://docs.wildfirechat.cn/ios/chatclient.html 客户端的DB中会存储上一次从服务器更新来的信息。我在该路径下查看数据库，没有发现我发送的数据 Library/Caches/cn.com.yunzai.dao/Cache.db   具体是缓存在哪里了呢？

**Comment by LengYi** [comment]
> 文档说 https://docs.wildfirechat.cn/ios/chatclient.html 客户端的DB中会存储上一次从服务器更新来的信息。我在该路径下查看数据库，没有发现我发送的数据 Library/Caches/cn.com.yunzai.dao/Cache.db 具体是缓存在哪里了呢？
<img width="794" alt="截屏2021-12-22 下午6 23 23" src="https://user-images.githubusercontent.com/5643730/147077772-816a63df-7964-406b-984b-2b326481e65e.png">

经过研究 好像是在这边 ，但是这个数据库是啥数据库呢？用 mySql 跟sqlite3 都打不开

**Comment by heavyrain2012** [comment]
是经过加密的，无法查看
