### ISSUE TITLE
发送超长文本，上下滑动卡顿

### ISSUE THREAD

**Issue by magic-geng** [wildfirechat/ios-chat#346]
#### 操作说明
在聊天会话页面，发送多条超长的文本，然后上下滑动，会卡顿。目前只有ios15的系统会卡顿。

#### 表现现象
滑动卡顿

#### 预期结果
不卡顿

#### 补充条件
在ios13的系统上，没有卡顿，只有在ios15的系统才会卡顿，而且必现

#### demo对比结果
demo也是一样的卡顿

**Comment by heavyrain2012** [comment]
显示的处理全是UI层的，可能就是计算文本的长度比较耗时，这部分代码都是开源的，你们可以debug看一下，看一下有没有办法解决

**Comment by magic-geng** [comment]
已解决
