### ISSUE TITLE
是否能开源修改的mars相关源码

### ISSUE THREAD

**Issue by ZYuanCheng** [wildfirechat/ios-chat#347]
看到ios端mars头文件中protot.h 代码与原mars代码一起，是否能开源此代码
现有的mars功能需求不能满足业务，要在这部分代码中添加功能，谢谢。

**Comment by heavyrain2012** [comment]
协议栈代码涉及到公司收费的pc等项目，所以无法开源。如果您有什么需求，我们会进行评估，确实有必要在协议栈中添加的，我们会排期添加，如果是没有必要在协议栈中添加的，我们也会给出建议

**Comment by ZYuanCheng** [comment]
@heavyrain2012 感谢您的回复，我们现在在选型评估方案，我们的需求是这样的，类似于企业微信，通讯录需要组织架构，一个人可以属于多个公司，一个人也可以属于多个组织，目前我看到的ios端或android端通讯录只有getfriend 方法，服务端使用的mqtt可以扩展；
我个人建议，可以把协议栈闭源，但这类的业务应该可以按用户去扩展，或者您根据我这个需求，现有的框架可以实现，也可以告诉我，谢谢！

**Comment by heavyrain2012** [comment]
明白你们的需求了，大概就是企业通讯录功能吧，这个功能跟IM服务应该是解耦合的，需要单独实现服务和客户端。在服务器端可以通过api来跟IM服务进行交互，比如创建组织官方群，还有官方群的人员变动等。客户端把IM和企业通讯录集成在一起，不使用野火提供的通讯录，使用你们自己研发的企业通讯录，野火不需要是好友才能聊天，只要通过组织通讯录拿到对方用户id，就可以跟对方聊天了

**Comment by ZYuanCheng** [comment]
@heavyrain2012 感谢你的回复，你的意思是我要实现企业通讯录，就在你们提供的接口工程im-app_server里面写一个接口，还是在server工程里面写一个通讯录接口去实现？

**Comment by heavyrain2012** [comment]
server服务要保持功能内聚，不要在这个服务上做任何的修改。可以在appserver或者你们其他业务服务上加组织通讯录功能

**Comment by ZYuanCheng** [comment]
用户id 在server工程的数据库里面，用appserver或者其他工程，那要同步用户信息才能保持一致，会不会比较麻烦。

**Comment by heavyrain2012** [comment]
不会很麻烦的，用户信息只保存一份就可以了，组织通讯录只保存IM服务中没有保存的部分。
