### ISSUE TITLE
使用getRemoteMessages从服务器获取会话消息，如果设置了消息类型（自定义消息），只能拿到从第一次会话加载完的聊天记录中筛选的结果，无法拿到更多服务器的消息，就算下拉加载了更多聊天记录依然不行。

### ISSUE THREAD

**Issue by xxuqizhing** [wildfirechat/ios-chat#348]
#### 操作说明

图一
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/32894908/153137482-0578d950-1c59-4c71-9b66-01fcf2183891.png">

/**
 获取服务器消息
 @param conversation 会话
 @param beforeMessageUid 起始index
 @param count 总数
 @param successBlock 返回消息
 @param errorBlock 返回错误码
 */
- (void)getRemoteMessages:(WFCCConversation *)conversation
                   before:(long long)beforeMessageUid
                    count:(NSUInteger)count
             contentTypes:(NSArray<NSNumber *> *)contentTypes
                  success:(void(^)(NSArray<WFCCMessage *> *messages))successBlock
                    error:(void(^)(int error_code))errorBlock;
如上图，在使用getRemoteMessages获取自定义类型消息时（即参数中contentTypes有值时），只能拿到16条自定义消息，这些消息是从第一次会话加载完的聊天记录中筛选的结果（即第一次安装APP后自动同步的会话的聊天记录）。

但是不设置消息类型时，接口是能拿到所有消息的，如下图

图二
<img width="990" alt="image" src="https://user-images.githubusercontent.com/32894908/153139085-4196e694-e6a6-4ce5-98d0-d42fefda10f1.png">

两张图为同一会话，除contentTypes不一样外，其余参数相同。如图此会话消息总数为1903，MESSAGE_CONTENT_TYPE_DIYFILE自定义类型消息总数为47。

#### 表现现象
当设置了contentTypes后，此接口返回的数据一直为从第一次会话加载完的聊天记录中筛选的结果，就算手动下拉加载了更多历史聊天记录后再次调用此接口，返回的数据依旧是从第一次会话加载完的聊天记录中筛选的结果（即图一中的16条）。

#### 预期结果
设置了contentTypes后，此接口返回数据（图一）应与手动筛选（图二）的消息数量一致

**Comment by heavyrain2012** [comment]
请联系我们更新版本验证

**Comment by xxuqizhing** [comment]
好的，已发送邮件。
