### ISSUE TITLE
类型转换错误

### ISSUE THREAD

**Issue by EF03** [wildfirechat/ios-chat#353]
![image](https://user-images.githubusercontent.com/47837419/154665080-8883b64b-2b1b-45dd-b571-57254a1cad4c.png)
WFCCCompositeMessageContent中再转换serverTime上有问题
一样的訊息无法重现，不确定怎么造成的
![image](https://user-images.githubusercontent.com/47837419/154665019-e649c12e-3033-4e61-83e8-9a45b0baa2ed.png)
现在是先类型判断后处理 不确定合不合适

**Comment by heavyrain2012** [comment]
这个问题是pc或者web发送的组合消息的时间不对，iOS做了兼容，请参考 https://github.com/wildfirechat/ios-chat/commit/c0c795e1fef91e22f744feadb109723786b7fb1e 。另外需要更新pc或web的创建组合消息的代码
