### ISSUE TITLE
自定义消息发送图片，视频，文件可以和发送图片，视频，文件消息一样先sendMessage然后上传吗？

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#354]
请问一下，就是我们的图片视频文件这些上传没有用sdk里面的content用的是自定义的消息类型，请问一下能不能把自定义的消息类型弄成像sdk里面图片类型的消息一样先发出去然后再上传呢

**Comment by heavyrain2012** [comment]
可以的，请参考一下图片消息，把消息继承自mediamessagecontent，把localpath填上，当协议栈发现localpath存在且remoteUrl不存在时，就会自动把localpath的内容上传上去，然后保存为remoteUrl发送出去

**Comment by ryanranya** [comment]
我们的图片，视频，文件是传到我们自己的服务器上，通过接口的方式。如果我先调用sendMessageContent发送自定义的消息图片，文件，视频。还有一些信息比如图片，视频，文件地址是后台返回的也需要一起发送出去，这种情况是不是必须等后台返回给我这些数据之后再才能sendMessageContent发送我的这条自定义消息呢。能不能弄成比如我先sendMessageContent，然后去给这条消息补充信息呢(比如图片的url这些信息)？

**Comment by ryanranya** [comment]
我们的图片，视频，文件是传到我们自己的服务器上，通过接口的方式。如果我先调用sendMessageContent发送自定义的消息图片，文件，视频。还有一些信息比如图片，视频，文件的一些信息是后台返回的也需要一起发送出去。这种情况是不是必须等后台返回给我这些数据之后再才能sendMessageContent发送我的这条自定义消息呢。能不能弄成比如我先sendMessageContent，然后去给这条消息补充信息呢？我们的文件还需要MD5校验，服务器上有了相同的图片则不再需要上传相同的图片了

**Comment by heavyrain2012** [comment]
只要媒体类消息体了有remoteUrl就可以直接发送，是否先上传再发送，还是先发送再上传取决于你们的设计，如果先发送再上传只要确保发送时的remoteUrl就是上传后的地址就行

**Comment by ryanranya** [comment]
请问一下我看到你们发送文件都是继承WFCCMediaMessageContent这个类的。一开始的时候我们能拿到loaclPath，调动sendMessage，发送成功之后是协议栈里面自动给remoteUrl赋值再发送吗？请问能不能实现我先sendmessage给传locaPath，等我们后台返回成功之后我再手动给remoteUrl赋值，再发送呢？

**Comment by heavyrain2012** [comment]
如果已经发送成了，是没有办法再对remoteUrl进行赋值的。可以在发送之前先insertMessage，消息的状态是发送中，这样UI上显示就是发送中了，然后你们再自己上传，上传成功过后修改消息内容，把remoteUrl填上，最后再调用一个方法是sendSavedMessage，就把消息真正的发出去。

**Comment by ryanranya** [comment]
收到，谢谢提醒

**Comment by ryanranya** [comment]
我通过
![截屏2022-02-24 下午3 23 42](https://user-images.githubusercontent.com/26618638/155479300-05a7d34e-cdcb-42b9-aae2-c80fb211bc76.png)
这样的方式insert消息，然后去调用我们自己的网络请求发送图片通过
![截屏2022-02-24 下午3 22 22](https://user-images.githubusercontent.com/26618638/155479416-121207a3-0d3e-4127-a020-e90241602ec6.png)
这样的fan方法重新给content赋值，但是我在对端不能拿到remoteUrl。
请问这种方式是对的吧！

**Comment by ryanranya** [comment]
我通过
![截屏2022-02-24 下午3 23 42](https://user-images.githubusercontent.com/26618638/155479300-05a7d34e-cdcb-42b9-aae2-c80fb211bc76.png)
这样的方式insert消息，然后去调用我们自己的网络请求发送图片通过
![截屏2022-02-24 下午3 22 22](https://user-images.githubusercontent.com/26618638/155479416-121207a3-0d3e-4127-a020-e90241602ec6.png)
这样的fan方法重新给content赋值，但是我在对端不能拿到remoteUrl。
请问这种方式是对的吧！

**Comment by heavyrain2012** [comment]
图片上传成功后，要更新一下消息的内容，有个updateMessageContent方法，然后再sendSavedMessage

**Comment by ryanranya** [comment]
还有一个问题就是我
/**
 插入消息
 
 @param conversation 会话
 @param content 消息内容
 @param status 消息状态，注意消息状态会影响消息方向
 @param serverTime 时间，0为当前时间
 @return 消息实体
 */
- (WFCCMessage *)insert:(WFCCConversation *)conversation
                 sender:(NSString *)sender
                content:(WFCCMessageContent *)content
                 status:(WFCCMessageStatus)status
                 notify:(BOOL)notify
             serverTime:(long long)serverTime;
通过这个api插入消息之后，会话列表有了，但是我saveSendMessage之后又出现一条，相当于两条一样的消息。这个需要怎么处理呢
        JWellBaseMessageConten *content = [JWellBaseMessageConten contentFrom:contentDic];
            if (messageContentType == 1002 ) {
                content.thumbnail = thumbnail;
            }
            [[WFCCIMService sharedWFCIMService] updateMessage:message.messageId content:content];
            WFCCMessage *messageConten = message;
            messageConten.content = content;
            [self sendSavedMessage:messageConten];
我用的就是这样的方法，哪里用的不对吗？

**Comment by heavyrain2012** [comment]
你看一下这两条消息的消息id是不是一样的，如果是一样的在消息列表插入消息时做一下排重，如果消息id一样就替换不插入
