### ISSUE TITLE
视频通话关闭扬声器bug

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#356]
if (_speakerButton.button.selected) {
            BOOL isSuccess = [self.currentSession enableSpeaker:YES];
            if (isSuccess) {
                [self setAlertLableTextConnected:@"声音已通过扬声器播放"];
            }
        }else{
            BOOL isSuccess = [self.currentSession enableSpeaker:NO];
            if (isSuccess) {
                [self setAlertLableTextConnected:@"声音已通过听筒播放"];
            }
        }

我调用相同的方法，语言通话的时候可以关闭扬声器，但是视频通话的时候扬声器不能关闭。

**Comment by heavyrain2012** [comment]
我们查到原因了，原因是最初设计时视频通话只能是speaker或者耳机等，不能通过听筒，确实不是太合理，已经放开这个限制了。请直接给我们发邮件索要新的SDK，邮件上说清楚公司名称还有域名，我们这边有值班的同事给你们打包

**Comment by ryanranya** [comment]
![image](https://user-images.githubusercontent.com/26618638/156490186-8c8e4372-4b6e-4da9-a43e-a2d9b0ec4eb8.png)
调用这个方法邀请更多人加入群聊的时候这里消息发给了对方，但是我本地的
![image](https://user-images.githubusercontent.com/26618638/156490290-6e3eb44d-e03d-4bbc-a9b5-47035da26969.png)
这个数组里面没有加进去，

**Comment by ryanranya** [comment]
![image](https://user-images.githubusercontent.com/26618638/156490476-9f93e6da-d49a-45d1-9e6e-d3cc5bacee5f.png)
我这里添加了，对方也收到消息了。对方也能加入但是我
![image](https://user-images.githubusercontent.com/26618638/156490592-6440bb86-ae06-4e76-993f-696c6994d9e4.png)
这里取的时候这里是空的
