### ISSUE TITLE
合并转发多条不同消息，大小限制15k

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#359]
#### 操作说明
聊天进行消息合并转发，转发的内容包括，视频、文本、图片等

#### 表现现象
提示转发失败，日志输出如下
[警告！！！消息内容大小是:245188，大小超过15K了，建议不要超过15K，如果大消息过多会影响接受体验，建议大文件使用媒体消息类型!!!

#### 预期结果
正常转发

**Comment by heavyrain2012** [comment]
协议栈实际上最大发送包为200K，请控制合并消息大小，让消息大小在200K以内

**Comment by heavyrain2012** [comment]
最新版本已经把组合消息改成媒体类消息，可以不限制消息大小了
