### ISSUE TITLE
updateMessage失败

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#360]
- (void)updateMessage:(long)messageId
              content:(WFCCMessageContent *)content;
调用这个方法去更新insert的消息，
我在kSendingMessageStatusUpdated里面收到传过来的通知消息但是在里面取到的消息不是update的最新消息。而是insert开始进去的消息。

**Comment by heavyrain2012** [comment]
我看我们代码kSendingMessageStatusUpdated这个通知是没有带消息的，只有消息的id，是不是你们改过，可以在发送通知时重新从协议栈加载一次消息

**Comment by ryanranya** [comment]
你说在sendSaveMessage的时候吗？

**Comment by ryanranya** [comment]
新的问题：A用户给B用户发送语言或者视频通话的时候B用户没有接听。等超时之后自动挂端。但是B用户这边挂单的原因是kWFAVCallEndReasonRemoteTimeout对方为接听，返回的原因应该是未接听吧。是对方拨打给我的

**Comment by heavyrain2012** [comment]
> 你说在sendSaveMessage的时候吗？

你可以看一下demo代码中发出kSendingMessageStatusUpdated这个通知的代码，只有messageid，没有消息。
