### ISSUE TITLE
- (WFCCUserInfo *)getUserInfo:(NSString *)userId      refresh:(BOOL)refresh;

### ISSUE THREAD

**Issue by 18254819000** [wildfirechat/ios-chat#362]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
1.正常启动app，好友修改头像，然后进入聊天页面和好友聊天。
2.正常启动app，先进入一次好友信息页面，然后好友修改头像。
#### 表现现象
1.好友修改了用户信息后，如果不打开好友信息页面，好友信息就一直不会更新。
2.先进入了一次用户信息页面后，好友信息就即使更新。

#### 预期结果
希望进入聊天页面后，如果好友信息发生了更新，就及时更新好友的本地信息。
#### 补充条件
是否是毕现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
请参考 https://docs.wildfirechat.cn/faq/general.html 问题4

**Comment by 18254819000** [comment]
进入聊天页面 强制更新用户信息的方法，没有效果。   操作1 说的 就是这个问题

**Comment by heavyrain2012** [comment]
获取用户信息使用强制更新参数，还是会立即返回本地的数据，然后再去服务器更新，如果有更新会发送一个通知。需要在UI层添加监听，当收到用户信息更新的通知后再刷新一下UI重新获取一下用户信息
