### ISSUE TITLE
视频通话转语音通话无声音

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#365]
我用A用户给B用户发送视频通话，B用户转语音接听，A用户说话B用户无声音。B用户说话A用户能听到。

**Comment by heavyrain2012** [comment]
音视频版本是那个？两个手机都是iOS吗？

**Comment by ryanranya** [comment]
都是你们发的最新版本，任何设备都是这样。PC，安卓，iOS都是这样

**Comment by heavyrain2012** [comment]
音视频有3个版本，免费1对1的，多人版的，高级版。你们测试的是那个版本？

**Comment by ryanranya** [comment]
我们用的是高级版，就是付费的那种

**Comment by heavyrain2012** [comment]
查出来了，是SDK有问题，请联系我们更新音视频SDK

**Comment by ryanranya** [comment]
现在iOS和iOS的可以了，但是iOS和其他端的还不行

**Comment by heavyrain2012** [comment]
其他端是那一端？测试的方式是什么？

**Comment by ryanranya** [comment]
和安卓手机端。直接用iOS视频通话安卓转语音，iOS说话iOS无声音

**Comment by ryanranya** [comment]
最开始我们是iOS呼出视频通话其他端转语音接听，呼出端说话接收端听不到声音。然后你们给了新的音视频SDK。现在iOS和iOS之间可以了，但是iOS和安卓之间用这样的方式来iOS呼出，安卓端直接转语音。iOS说话安卓端无声音。安卓端说话iOS能听到。都切换了最新的音视频sdk。

**Comment by heavyrain2012** [comment]
android端更新最新SDK了吗？是不是android端的问题？android和android测试情况怎么样？
