### ISSUE TITLE
insert消息出现闪退

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#366]
WFChatClient
mars::app::GetAccountUserName() + 192
1
WFChatClient
mars::app::GetAccountUserName() + 188
2
WFChatClient
fillTMessage(mars::stn::TMessage&, WFCCConversation*, WFCCMessageContent*) + 324
3
WFChatClient
-[WFCCIMService insert:sender:content:status:notify:serverTime:] + 260
4
HBuilder
-[ShareService shareLineMessage:conversation:complete:] + 260
5
HBuilder
-[ShareExtensionSearchViewController shareSendMessage:] + 1112
6
HBuilder
-[ShareExtensionSearchViewController sureButtonClick:] + 208
7
HBuilder
-[ShareExtensionPopupView sureButtontap:] + 184
8
UIKitCore
-[UIApplication sendAction:to:from:forEvent:] + 96
9
UIKitCore
-[UIControl sendAction:to:forEvent:] + 124
10
UIKitCore
-[UIControl _sendActionsForEvents:withEvent:] + 348
11
UIKitCore
-[UIButton _sendActionsForEvents:withEvent:] + 156
12
UIKitCore
-[UIControl touchesEnded:withEvent:] + 532
13
UIKitCore
-[UIWindow _sendTouchesForEvent:] + 1228
14
UIKitCore
-[UIWindow sendEvent:] + 4392
15
UIKitCore
-[UIApplication sendEvent:] + 896
16
UIKitCore
___dispatchPreprocessedEventFromEventQueue + 8124
17
UIKitCore
___processEventQueue + 6748
18
UIKitCore
___eventFetcherSourceCallback + 168
19
CoreFoundation
___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
20
CoreFoundation
___CFRunLoopDoSource0 + 204
21
CoreFoundation
___CFRunLoopDoSources0 + 256
22
CoreFoundation
___CFRunLoopRun + 768
23
CoreFoundation
_CFRunLoopRunSpecific + 572
24
GraphicsServices
_GSEventRunModal + 160
25
UIKitCore
-[UIApplication _run] + 1080
26
UIKitCore
_UIApplicationMain + 332
27
HBuilder
main + 88
28
???
0x00000001052d8000 + 0

**Comment by heavyrain2012** [comment]
应该是没有调用connect函数，只有调用过connect函数后协议栈才能使用

**Comment by ryanranya** [comment]
好的。我试试但是这个崩溃不是必现的
