### ISSUE TITLE
WFAVEngineKit 中关于pushkit的 代码

### ISSUE THREAD

**Issue by 18254819000** [wildfirechat/ios-chat#369]
业务需要，需要看一下，WFAVEngineKit 中关乎 pushkit 框架的代码

**Comment by heavyrain2012** [comment]
```
#pragma mark - voip push
- (void)registerVoipPushService {
  if ([[UIApplication sharedApplication] respondsToSelector:@selector(registerUserNotificationSettings:)]) {
    NSLog(@"AVEngine registerUserNotificationSettings");
    //注册推送, 用于iOS8以及iOS8之后的系统
    PKPushRegistry *pushRegistry = [[PKPushRegistry alloc] initWithQueue:dispatch_get_main_queue()];
    pushRegistry.delegate = self;
    pushRegistry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];
  }
}

/*!
 @method        pushRegistry:didUpdatePushCredentials:forType:
 @abstract      This method is invoked when new credentials (including push
 token) have been received for the specified
 PKPushType.
 @param         registry
 The PKPushRegistry instance responsible for the delegate callback.
 @param         credentials
 The push credentials that can be used to send pushes to the device for the
 specified PKPushType.
 @param         type
 This is a PKPushType NSString constant which is present in [registry
 desiredPushTypes].
 */
- (void)pushRegistry:(PKPushRegistry *)registry
didUpdatePushCredentials:(PKPushCredentials *)credentials
             forType:(NSString *)type {
    const char *data = [credentials.token bytes];
    NSMutableString *token = [NSMutableString string];

    for (NSUInteger i = 0; i < [credentials.token length]; i++) {
        [token appendFormat:@"%02.2hhX", data[i]];
    }
    
    NSString *voipToken = [token copy];

    if (voipToken.length > 0) {
        [[WFCCNetworkService sharedInstance] setVoipDeviceToken:voipToken];
    }
    NSLog(@"AVEngine voip device token is %@", voipToken);
}

/*!
 @method        pushRegistry:didReceiveIncomingPushWithPayload:forType:
 @abstract      This method is invoked when a push notification has been
 received for the specified PKPushType.
 @param         registry
 The PKPushRegistry instance responsible for the delegate callback.
 @param         payload
 The push payload sent by a developer via APNS server API.
 @param         type
 This is a PKPushType NSString constant which is present in [registry
 desiredPushTypes].
 */
- (void)pushRegistry:(PKPushRegistry *)registry
didReceiveIncomingPushWithPayload:(PKPushPayload *)payload
             forType:(NSString *)type {
  NSLog(@"AVEngine didReceiveIncomingPushWithPayload: type is %@, dictionary is %@", payload.type, payload.dictionaryPayload);
  
  //  if (payload.dictionaryPayload[@"VOIP"] ) {
  
  if (!self.pushTimer) {
    self.pushTimer = [NSTimer scheduledTimerWithTimeInterval:1
                                                      target:self
                                                    selector:@selector(tryConnect)
                                                    userInfo:nil
                                                     repeats:NO];
  }
  //  } else {
  //    NSLog(@"didReceiveIncomingPushWithPayload is not VoIP.");
  //  }
}

- (void)tryConnect {
  if (self.pushTimer) {
    if (self.pushTimer.valid) {
      [self.pushTimer invalidate];
    }
    self.pushTimer = nil;
  }
    [[WFCCNetworkService sharedInstance] forceConnect:60];
}

```

**Comment by 18254819000** [comment]
从代码看 ，收到push之后，仅仅只进行了 一个IM的强制链接 。链接之后代码又做了哪些 处理呢 ？WFAVEngineDelegate中的  didReceiveCall  方法是在什么 条件下触发的呢？？

**Comment by heavyrain2012** [comment]
强制连接后IM会建立连接从而收到来电的消息，收到来电的消息就会回调到来电的delegate和播放铃声的delegate

**Comment by heavyrain2012** [comment]
你们是遇到什么问题了吗？

**Comment by 18254819000** [comment]
需要对接PushKit 和 CallKit框架，有demo吗？

**Comment by 18254819000** [comment]
对接PushKit 和 CallKit框架，如何对接SDK？ 有 方案吗

**Comment by heavyrain2012** [comment]
我们没有开发callkit相关功能，这个功能需要你们自己来开发，现有的代码应该可以满足你们开发callkit的需求，如果有某些功能因为接口没有开放无法开发可以给我们提需求

**Comment by 18254819000** [comment]
现在的推送都是走的APN对吧？  我现在注释掉appdelegate里面所有 的播放音视频来电声音的代码 ， 杀掉app 之后，收到 推送  还是会 播放声音，这是怎么回事

**Comment by 18254819000** [comment]
推送后台服务  有开发 VOIP 推送吗？  c.add(Calendar.MINUTE, 1); //voip通知，使用普通推送  这个注释是说   voip推送没有开发代码吗

**Comment by heavyrain2012** [comment]
有voip的开发，如果打开会走voip推送相关的代码。

**Comment by heavyrain2012** [comment]
voip的推送的type和包名都是跟普通推送不同的，具体voip和普通推送的区别请从网上查找一下

**Comment by 18254819000** [comment]
更换  WFAVEngineKit.xcframework  之后  真机跑不起来了 。  
老的代码 更新 xcframework 需要注意什么

**Comment by 18254819000** [comment]
- (void)pushRegistry:(PKPushRegistry *)registry
didReceiveIncomingPushWithPayload:(PKPushPayload *)payload
 forType:(NSString *)type   这个方法 iOS 11之后就改了，需要你们更新 一下。  
另外，使用voip的话 后台改一下开关就可以了吗？ voip推送 你们有没有成功测试过？？

**Comment by heavyrain2012** [comment]
这个方法没有问题，你需要理解voip推送的流程。当push_server 收到voip相关的推送时，会给客户端发送voip的推送，voip的推送会拉取应用，然后回调上面的这个方法，这个方法会强制connect IM服务，连上IM服务后会收下来来电通知消息，收到来电通知消息后，就会回调来电事件和响铃事件，这个时候在弹出来电界面（用callkit）或则弹出来电的通知（不用callkit）

**Comment by heavyrain2012** [comment]
voip的推送需要你们自己来调试，我们是测试过的

**Comment by 18254819000** [comment]
我想确认一下voip 是否能正常使用。我这边调试出现问题了，你们调试过那就是服务端的voip push是正常的。

**Comment by heavyrain2012** [comment]
这个推送服务的说明你们需要仔细看一下 https://github.com/wildfirechat/push_server 。其中推送服务到客户端这个是需要你们自己来处理的，如果推送内容正确到达推送服务，则后面的排查就跟IM服务完全无关了，是推送厂商推送服务的调试，需要客户自己按照推送厂商的官方文档进行调试。

**Comment by heavyrain2012** [comment]
推送服务进行voip推送，如果推送成功，客户端则会被拉起，在客户端打日志看看有没有被拉起就能知道有没有推送成功

**Comment by 18254819000** [comment]
现在正常的推送 如果是音视频的时候 是没有进行强制链接IM 的 是吗

**Comment by 18254819000** [comment]
新的SDK中，调用了 [WFAVEngineKit notRegisterVoipPushService]   ,日志中 依然有voip device token is **** 输出。为什么

**Comment by heavyrain2012** [comment]
这个方法  [WFAVEngineKit notRegisterVoipPushService]  需要放到所有音视频操作之前调用，请确认是否放到所有音视频操作之前？

**Comment by 18254819000** [comment]
是的，demo里面也有这个问题。

**Comment by 18254819000** [comment]
需要看一下 WFAVEngineKit 的代理方法  - (void)didReceiveCall:(WFAVCallSession *)session  中  session  是如何构造的 。

**Comment by 18254819000** [comment]
我们这边可能需要在收到VOIP推送之后 ，锁屏状态下也可以进行通话。  我们的SDK 是否可以支持实现这个方案 。

**Comment by heavyrain2012** [comment]
> 

这个代码没有办法给你们分享，你们用它公开的接口就可以了

**Comment by heavyrain2012** [comment]
> 我们这边可能需要在收到VOIP推送之后 ，锁屏状态下也可以进行通话。 我们的SDK 是否可以支持实现这个方案 。

收到voip推送后，IM服务被激活，收到来电邀请，回调到方法didReceiveCall，后面需要你们自己来对接callkit

**Comment by 18254819000** [comment]
[[WFCCNetworkService sharedInstance] forceConnect:60];   参数 60 是什么 意思

**Comment by heavyrain2012** [comment]
这个函数是要让client保持连接60秒，你可以点进去看一下，做的事情就是启动一个后台任务，后台任务持续60秒

**Comment by 18254819000** [comment]
我现在的情况是， 程序杀死之后，拨打音视频通话可以收到voip推送， 此时调用[[WFCCNetworkService sharedInstance] forceConnect:60]; 这个方法，但是 一直收不到 - (void)didReceiveCall:(WFAVCallSession *)session  的回调。  另外，如果是必须走强连的方法的话，在锁屏状态下 我如何进行接听

**Comment by heavyrain2012** [comment]
收到voip推送后，应用会被拉起，这时候需要先调用connect，让IM连上才能收到来电的消息，这样才能收到didReceiveCall的回调

**Comment by 18254819000** [comment]
我收不到 didReceiveCall  怎么调用接听函数啊 ？

**Comment by heavyrain2012** [comment]
> 收到voip推送后，应用会被拉起，这时候需要先调用connect，让IM连上才能收到来电的消息，这样才能收到didReceiveCall的回调

看这个回复，确认一下收到的是普通推送还是voip推送？voip推送会拉起应用，确认拉起应用后有没有调用connect？如果调用了connect，有没有链接状态转变为已连接？请确认这3个问题

**Comment by 18254819000** [comment]
收到的是 voip推送，这是肯定的。在pushkit代理里面  调用的强连方法，之后没有任何的反应，链接状态没有任何输出

**Comment by heavyrain2012** [comment]
> > 收到voip推送后，应用会被拉起，这时候需要先调用connect，让IM连上才能收到来电的消息，这样才能收到didReceiveCall的回调
> 
> 看这个回复，确认一下收到的是普通推送还是voip推送？voip推送会拉起应用，确认拉起应用后有没有调用connect？如果调用了connect，有没有链接状态转变为已连接？请确认这3个问题

“voip推送会拉起应用，确认拉起应用后有没有调用connect”，这个connect是连接IM用的，必须要调用这个，没有所谓的强连接，那个只是保持后台任务1分钟

**Comment by 18254819000** [comment]
> > > 收到voip推送后，应用会被拉起，这时候需要先调用connect，让IM连上才能收到来电的消息，这样才能收到didReceiveCall的回调
> > 
> > 
> > 看这个回复，确认一下收到的是普通推送还是voip推送？voip推送会拉起应用，确认拉起应用后有没有调用connect？如果调用了connect，有没有链接状态转变为已连接？请确认这3个问题
> 
> “voip推送会拉起应用，确认拉起应用后有没有调用connect”，这个connect是连接IM用的，必须要调用这个，没有所谓的强连接，那个只是保持后台任务1分钟

- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(NSString *)type  我在这个 方法里面输出了本地的通知，同时 调用 了  [[WFCCNetworkService sharedInstance] forceConnect:20];然后 在- (void)onConnectionStatusChanged:(ConnectionStatus)status  和 - (void)didReceiveCall:(WFAVCallSession *)session 里面 都 做了本地通知，现在只有第一个本地通知会触发。后面的都不会触发

**Comment by heavyrain2012** [comment]
收到voip推送，应该会执行 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions代码，在这里需要执行初始化，请参考demo里的做法，函数的最后调用 [[WFCCNetworkService sharedInstance] connect:savedUserId token:savedToken];

**Comment by 18254819000** [comment]
用demo测试 也 不能收到 通话 请求 。   把[[WFCCNetworkService sharedInstance] connect:savedUserId token:savedToken];  放在pushkit的回调方法里面 也不能成功连接IM ，是怎么回事？

**Comment by 18254819000** [comment]
网上很多说是 iOS13之后，要在收到voip推送之后的代理方法完成之前就要执行callkit，否则程序就会被终止。

**Comment by heavyrain2012** [comment]
这个我们没有研究过，只要确保应用是激活状态，能连上IM就能收下来电通知

**Comment by 18254819000** [comment]
https://developer.apple.com/videos/play/wwdc2019/707/?time=175  这个视频中说明了 And new this year, it's very important that you know that you must report incoming calls with CallKit in the didReceiveIncomingPush callback or your app will be terminated. And, if you repeatedly do this, or if you repeatedly fail not to report an incoming call, the system may stop launching your app for VoIP pushes altogether.   请你们也研究一下，收到推送之后，只保活能否实现网络电话的接听。  另外 ，能否实现在锁屏状态下接听音视频电话？

**Comment by 18254819000** [comment]
现在是voip推送可以收到，IM链接没有 反应，也就无法进行后面的处理

**Comment by 18254819000** [comment]
> 这个我们没有研究过，只要确保应用是激活状态，能连上IM就能收下来电通知

这个确保应用是激活状态，是如何确保的？？

**Comment by 18254819000** [comment]
iOS 13之后，callkit  必须在收到voip推送的代理里面执行，否则app就不会被激活。如果在收到推送之后，执行callkit， 是可以链接IM的。但是业务逻辑上 是不是应该在执行callkit之前，我就得知道这个音视频通话的信息啊 。

**Comment by heavyrain2012** [comment]
野火的来电是通过消息来通知的，只有先连上IM才能收到来电的回调，如果没有连上IM是没有办法知道来电信息的

**Comment by heavyrain2012** [comment]
> iOS 13之后，callkit 必须在收到voip推送的代理里面执行，否则app就不会被激活。如果在收到推送之后，执行callkit， 是可以链接IM的。但是业务逻辑上 是不是应该在执行callkit之前，我就得知道这个音视频通话的信息啊 。

推送服务知道来电的发起人，可以让推送服务把发起人加入到推送信息中，这样收到推送就知道是谁来电的了

**Comment by 18254819000** [comment]
> > iOS 13之后，callkit 必须在收到voip推送的代理里面执行，否则app就不会被激活。如果在收到推送之后，执行callkit， 是可以链接IM的。但是业务逻辑上 是不是应该在执行callkit之前，我就得知道这个音视频通话的信息啊 。
> 
> 推送服务知道来电的发起人，可以让推送服务把发起人加入到推送信息中，这样收到推送就知道是谁来电的了

如果我通过推送服务把通话session的信息推过来，未连接IM的情况下 ，可以接听到语音通话吗？ 因为现在必须在voip推送里面调起callkit才能激活app，这个时候接电话可能和IM连接还未成功。

**Comment by heavyrain2012** [comment]
必须是连上IM服务后音视频功能才可以使用，在连上IM和收到来电的回调之前是没有办法接听的

**Comment by heavyrain2012** [comment]
我们已经在demo上加上了callkit的支持，可以参考我们demo的代码
