### ISSUE TITLE
通讯录能否添加一个好友来源的字段

### ISSUE THREAD

**Issue by HubeauChou** [wildfirechat/ios-chat#37]
这是一个新的需求，通讯录的好友列表，能否增加一个好友来源的字段，一个可以自定义的字符串。（比如：“来自二维码扫描”、“来自手机联系人”、“来自xx群聊”）

**Comment by heavyrain2012** [comment]
通过好友申请时，可以多加一个extra参数，这个参数会放到好友信息的extra中，可以实现这个功能
