### ISSUE TITLE
iOS和安卓之间视频通话转语音的问题

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#371]
我们替换了最新的高级版SDK，但是iOS给安卓拨打视频通话，安卓转语音接听。iOS这边说话安卓那边无法听到。安卓说话iOS这边可以听到。测试iOS和iOS之间是正常的，安卓和安卓之间是可以的。但是iOS和安卓之间这样操作安卓无法听到iOS这边说话，

**Comment by imndx** [comment]
demo 上可以复现吗？我测试了下，好像没有复现。

**Comment by heavyrain2012** [comment]
我们测试了最新的情况，没有发现问题。你们ios和android的sdk都是最新的吗？如果有不是最新的，发邮件找我们要最新的SDK试试

**Comment by ryanranya** [comment]
都是最新的，昨天你们邮件发给我们的，以前是都不行，但是你改过之后iOS之间是可以的，但是iOS和安卓还是有问题

**Comment by heavyrain2012** [comment]
最新版本验证没有问题
