### ISSUE TITLE
编译运行都正常，但是打包，用transport 提交之后，收到邮件：ITMS-90429: Invalid Swift Support

### ISSUE THREAD

**Issue by pangyunxiu** [wildfirechat/ios-chat#372]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
编译运行都正常，但是打包，用transport 提交之后，收到邮件：ITMS-90429: Invalid Swift Support

#### 表现现象
编译运行都正常，但是打包，用transport 提交之后，收到邮件：ITMS-90429: Invalid Swift Support-The files libswiftDarwin.dylib, libswiftAssetsLibrary.dylib, libswiftMetal.dylib, libswiftCoreAudio.dylib, libswiftsimd.dylib, libswiftQuartzCore.dylib, libswift_Concurrency.dylib, libswiftos.dylib, libswiftMapKit.dylib, libswiftObjectiveC.dylib, libswiftDispatch.dylib, libswiftCoreLocation.dylib, libswiftAccelerate.dylib, libswiftCoreGraphics.dylib, libswiftCoreData.dylib, libswiftCoreFoundation.dylib, libswiftUIKit.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftPhotos.dylib, libswiftMediaPlayer.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload/Ukaku.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

#### 预期结果
能正确打包提审

#371 ### 补充条件
必现

#### demo对比结果
没试过

**Comment by heavyrain2012** [comment]
检查一下这个解决方案行不行 https://developer.apple.com/library/archive/qa/qa1881/_index.html 如果不行可以从网上搜索看看

**Comment by pangyunxiu** [comment]
> 检查一下这个解决方案行不行 https://developer.apple.com/library/archive/qa/qa1881/_index.html 如果不行可以从网上搜索看看

已经花了8小时各种找了，就是没办法解决了，才来找你们的。

**Comment by heavyrain2012** [comment]
https://developer.apple.com/library/archive/qa/qa1881/_index.html  这个方法可行吗

**Comment by pangyunxiu** [comment]
已经解决了，是应为我 xcode13.2为了兼容 iphone6 12.0系统导致的问题，我把兼容的设置删了，再更新成 xcode13.3就解决了
