### ISSUE TITLE
频道消息解析问题

### ISSUE THREAD

**Issue by Bearmond** [wildfirechat/ios-chat#373]
SDK解析服务器发送的频道消息失败，VUE-PC端成功，iOS端WFCCtextMessageContent中没有content字段，VUE-PC端可以直接json解析出来。
![WechatIMG2314](https://user-images.githubusercontent.com/15085583/161523568-d89e04dd-d86e-4b42-94fe-ac75efe2f056.jpeg)
<img width="443" alt="WechatIMG2319" src="https://user-images.githubusercontent.com/15085583/161523587-142b9083-7611-4f38-91a0-a5ac33ff97f7.png">

**Comment by heavyrain2012** [comment]
没有看明白什么情况？是你们自定义消息了吗？你们都作了什么修改和操作？
