### ISSUE TITLE
iOS版本问题：WiFi网络下，语音通话过程中，关闭WiFi使用移动网络信号，听不到对方声音

### ISSUE THREAD

**Issue by guopingzhang** [wildfirechat/ios-chat#375]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
1.iOS版本，wifi网络状态下，拨打语音通话
2.关闭WiFi，使用移动网络信号继续通话

#### 表现现象
听不到对方说话

#### 预期结果
wifi切移动网络信号后，语音通话正常

#### 补充条件
必现，iOS 音视频SDK是2022年3月24号版本

#### demo对比结果
demo也存在这个问题

**Comment by heavyrain2012** [comment]
最新版本已经添加切换功能
