### ISSUE TITLE
协议栈无限发送kUserInfoUpdated的通知，导致界面卡死

### ISSUE THREAD

**Issue by ryanranya** [wildfirechat/ios-chat#377]
两个账号A先登录，然后B登录相同的账号挤掉A，此时A再换一个账号点击进入群聊有被卡死的问题。发现协议栈一直发送kUserInfoUpdated通知更新消息。

**Comment by heavyrain2012** [comment]
看一下通知里的用户信息是什么状态？这个用户存在吗？

**Comment by heavyrain2012** [comment]
还有给我们抓一下协议栈日志看看吧，把协议栈日志发给support@wildfirechat.cn
