### ISSUE TITLE
多人音视频 视频推流缩放问题

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/ios-chat#379]
对接专业音视频 sdk 遇到  ios 缩放模式，其他几种都是无效的，全是自适应模式 

![image](https://user-images.githubusercontent.com/18641493/164126013-978520e2-fffa-4a30-a6e8-4d929364394b.png)
/**
 缩放模式

 - kWFAVVideoScalingTypeAspectFit: 自适应
 - kWFAVVideoScalingTypeAspectFill: 拉伸
 - kWFAVVideoScalingTypeAspectBalanced: 平衡
 */
typedef NS_ENUM(NSInteger, WFAVVideoScalingType) {
    kWFAVVideoScalingTypeAspectFit,
    kWFAVVideoScalingTypeAspectFill,
    kWFAVVideoScalingTypeAspectBalanced,
    kWFAVVideoScalingTypeScaleFill
};

[self.currentSession setupLocalVideoView:centerView scalingType:kWFAVVideoScalingTypeScaleFill];

请帮忙协助助理，谢谢。

**Comment by heavyrain2012** [comment]
masksToBounds 属性要设置为true
