### ISSUE TITLE
发送文件消息时，选择特殊文件（文件夹、0KB、损坏文件）直接崩溃闪退

### ISSUE THREAD

**Issue by CoderJYZhu** [wildfirechat/ios-chat#381]
发送文件消息时，选择特殊文件（文件夹、0KB、损坏文件）直接崩溃闪退
<img width="1172" alt="WeChat8a0b0949efccd0ce6e561b35c3bafd76" src="https://user-images.githubusercontent.com/11565354/167779369-7a37e962-133f-4aa3-80c4-61effe41b456.png">

测试文件：
[演示文稿.key.zip](https://github.com/wildfirechat/ios-chat/files/8667142/key.zip)

**Comment by heavyrain2012** [comment]
这是因为这些类型的文件是文件夹

**Comment by heavyrain2012** [comment]
请检查提交 https://github.com/wildfirechat/ios-chat/commit/8d1c579bb5b2e7e15085b146f6e16af6cc8f4ddd

**Comment by CoderJYZhu** [comment]
经测试还是崩溃，文件是.key ，[[NSFileManager defaultManager] fileExistsAtPath:file isDirectory:&isDir] 只判断文件夹不行把

**Comment by heavyrain2012** [comment]
[[NSFileManager defaultManager] fileExistsAtPath:file isDirectory:&isDir]  这个方法判断出来是文件夹？还是普通文件？

**Comment by CoderJYZhu** [comment]
fileExistsAtPath这个方法是判断当前文件夹是否存吧， 上面的测试文件.key文件 调用该方法返回 isDir = no，走到后面还是崩溃

**Comment by CoderJYZhu** [comment]
建议还是直接获取文件大小来判断

**Comment by heavyrain2012** [comment]
上面附件里的文件应该判断出来是目录才对啊
