### ISSUE TITLE
CallKit 问题

### ISSUE THREAD

**Issue by 18254819000** [wildfirechat/ios-chat#382]
在开启 USE_CALL_KIT 的情况下， 如果被叫方手机处于锁屏状态 ，收到音视频通话的时候 无法正常 通话，如何解决 ？

**Comment by heavyrain2012** [comment]
debug看一下有没有调用到接听电话 [[WFAVEngineKit sharedEngineKit].currentSession answerCall:false callExtra:nil];

**Comment by 18254819000** [comment]
app杀死之后，后台日志推送成功，App没有 任何的反应。  会是什么情况

**Comment by heavyrain2012** [comment]
这种情况就需要查一下推送，voip推送应该能拉起应用，会走到推送回调才对

**Comment by 18254819000** [comment]
[WFAVEngineKit notRegisterVoipPushService]; 现在是这个情况，这个方法如果调用了，那么就能正常收到 voip推送，但是日志里面也没有 voip device token is *********** 的信息。  如果不调用这个方法，有 voip device token is 日志输出 ，但是收不到voip推送

**Comment by 18254819000** [comment]
我们感觉目前的voip推送的地方 还有bug。我这边通过多台手机实测 发现 一个现象，只有再以下操作下才可以收到Voip推送：
1. 先注释掉 [WFAVEngineKit notRegisterVoipPushService];，然后代码会上报voiptoken。这种 情况下，voip推送一直收不到推送。
2. 然后 打开[WFAVEngineKit notRegisterVoipPushService];重新给设备刷新程序，然后 voip推送 才可以正常收到。
3. 然后再注释掉 [WFAVEngineKit notRegisterVoipPushService];  app就无法收到推送 。而且在切换至第三步的时候，偶尔会在didReceiveIncomingPushWithPayload:(PKPushPayload *)payload
                                  forType:(NSString *)type 中出现callId 是空的情况，程序崩溃。  收到的推送内容如下； 
aps =     {
        alert =         {
            body = "\U901a\U8bdd\U9080\U8bf7";
            title = 9001;
        };
        badge = 1;
        sound = "ring.caf";
    };
    wfc =     {
        contType = 400;
        convLine = 0;
        convTarget = 1ygqmws2k;
        convType = 0;
        pushData = "";
        sender = uygqmws2k;
    };

**Comment by 18254819000** [comment]
/**
 开启或关闭扬声器
 
 @param speaker 是否使用扬声器
 @return 操作是否成功
 */
- (BOOL)enableSpeaker:(BOOL)speaker;

需要看一下 WFAVEngineKit 内部该方法的具体实现代码 ？  
我们目前遇到了新的 问题，在使用系统页面通话的过程中 扬声器使用有问题。

**Comment by heavyrain2012** [comment]
这个接口需要在接通后才能调用
