### ISSUE TITLE
删除消息失败

### ISSUE THREAD

**Issue by BurtonUrton** [wildfirechat/ios-chat#383]
目前在后台打 im server (http://domain:18080/admin/message/delete)
检查DB有修改资料
android有移除该讯息但ios这没有反应
现在不确定ios要在哪边如何实现移除讯息这个功能
还请劳烦 提示

**Comment by heavyrain2012** [comment]
iOS的协议栈是什么时候的版本？是不是比较旧？可以更新后测试看看

**Comment by BurtonUrton** [comment]
协议栈的版本要到哪里看?

我们这的repo是2022/01/28 clone下来的

**Comment by heavyrain2012** [comment]
你们IM服务是专业版IM？是那天发给你们的版本，api/version可以看到编译日期？

**Comment by heavyrain2012** [comment]
我们测试在单聊对话server api删除消息时，发送方确实有问题，请更新版本验证

**Comment by BurtonUrton** [comment]
是专业版的
"buildTime":"20211213130121"
以下api/version

{
	"tags":"null",
	"branch":"a3a68ff313e22214e91b5b5f44913660246674b8",
	"dirty":"null",
	"mailto:remoteoriginurl":"git@github.com:heavyrain2012/server_commercial.git",
	"commitId":"a3a68ff313e22214e91b5b5f44913660246674b8",
	"commitIdAbbrev":"a3a68ff",
	"describe":"moli-280-ga3a68ff",
	"describeShort":"null",
	"commitUserName":"heavyrain2012",
	"mailto:commituseremail":"heavyrain.lee@gmail.com",
	"commitMessageFull":"log4j version 2.15.0\n",
	"commitMessageShort":"log4j version 2.15.0",
	"commitTime":"20211210161350",
	"nodeIds":"1 2 ",
	"closestTagName":"null",
	"closestTagCommitCount":"null",
	"buildUserName":"imndx",
	"mailto:builduseremail":"imndxx@gmail.com",
	"buildTime":"20211213130121",
	"buildHost":"null",
	"buildVersion":"null",
	"verified":true,
	"currentNode":1,
	"runTime":2330391
}

**Comment by heavyrain2012** [comment]
请发邮件给我们要求更新版本
