### ISSUE TITLE
将mars.xcframework导入到自定义framework库中问题

### ISSUE THREAD

**Issue by leblanc-zx** [wildfirechat/ios-chat#387]
将mars.xcframework导入到自定义framework库中，通过pod管理，安装到demo中后，一直报错library not found -lmars。
楼主还有mars.framework库吗

**Comment by heavyrain2012** [comment]
为什么要使用mars.xcframework，不是应该使用chatclient库吗？

**Comment by leblanc-zx** [comment]
没有直接编译chatclient库，而是将chatclient库中的一部分放到了我自定义的库中进行二次开发了，并且对chatclient中的代码也有修改。

**Comment by leblanc-zx** [comment]
多谢楼主，现在已经解决了

**Comment by heavyrain2012** [comment]
不用客气
