### ISSUE TITLE
真机运行报错

### ISSUE THREAD

**Issue by liuhuanbo** [wildfirechat/ios-chat#388]
模拟器可以正常运行，真机报如图错误
<img width="944" alt="image" src="https://user-images.githubusercontent.com/9410051/177102040-b99e6e0f-5a80-4368-b7c3-c9f7e2df8b2a.png">

**Comment by liuhuanbo** [comment]
也按照文档中先运行了  WFChatUIKit这个了

**Comment by liuhuanbo** [comment]
图附上日志报错信息。
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/9410051/177453805-e13459a1-f2df-49ed-b727-47e9032813a3.png">

**Comment by heavyrain2012** [comment]
看问题 #389 已经解决了真机运行的问题，此问题关闭
