### ISSUE TITLE
代码打包报错

### ISSUE THREAD

**Issue by liuhuanbo** [wildfirechat/ios-chat#389]
模拟器真机运行可以，打包报错。

**Comment by heavyrain2012** [comment]
请提供更多信息

**Comment by liuhuanbo** [comment]
<img width="1114" alt="WechatIMG250" src="https://user-images.githubusercontent.com/9410051/178390835-b9c5add4-0f26-4b49-96f7-550a26a9b4bb.png">
<img width="1163" alt="WechatIMG251" src="https://user-images.githubusercontent.com/9410051/178390842-3df12233-80aa-4614-99cc-63d576ce3b85.png">
真机已经可以跑起来，现在打包报错，错误信息如上图

**Comment by heavyrain2012** [comment]
你们有没有做什么修改

**Comment by heavyrain2012** [comment]
我用我们最新代码，什么都不修改（如果你们自己操作，还需要更换包名和配置开发者后台），直接archive，是可以成功的。你们是用的我们demo，还是把sdk放到你们项目中了？你们试试只改包名和证书看看能不能打包成功？

**Comment by liuhuanbo** [comment]
就只是改了包名，配置了签名需要的相关文件，用的是Demo，代码未做任何修改。真机，模拟机都可以，打包就出错了。github上面是最新的代码吗?

**Comment by heavyrain2012** [comment]
打包不要选arm架构，只支持arm64架构
