### ISSUE TITLE
处理好友请求的方法，accept无论传YES还是NO，结果都是同意好友请求。

### ISSUE THREAD

**Issue by wblzu** [wildfirechat/ios-chat#39]
处理好友请求的方法，accept无论传YES还是NO，结果都是同意好友请求。
- (void)handleFriendRequest:(NSString *)userId
                     accept:(BOOL)accpet
                  success:(void(^)(void))successBlock
                    error:(void(^)(int error_code))errorBlock

**Comment by heavyrain2012** [comment]
已经处理完成，请验证

**Comment by wblzu** [comment]
可以了，感谢大神
