### ISSUE TITLE
长按对话框中的文字时，不支持复制一部分

### ISSUE THREAD

**Issue by CoderJYZhu** [wildfirechat/ios-chat#390]
在聊天对话框中长按一段文字时，无法选择这段文字中的一部分（只能复制全部文字），希望能否支持复制一部分文字。
消息类型为文字时，长按出现文字选择光标。

**Comment by heavyrain2012** [comment]
请检查WFCUTextCell.m 文件中的textLabel属性，现在用的是AttributedLabel控件，可以支持电话号码和网址的识别，你们可以找找看看有没有支持选择复制的控件
