### ISSUE TITLE
主持人控制会议成员全体静音/单人静音

### ISSUE THREAD

**Issue by daiyyyyyyy** [wildfirechat/ios-chat#391]
会议进行时，主持人可以一键将全体成员静音，或操作单个成员静音

**Comment by heavyrain2012** [comment]
没有办法在janus统一控制，需要应用层来实现这个功能。可以在应用服务（会议服务）中记录当前全局静音状态，新加入成员要判断这个状态，当会议中主持人控制时修改这个状态，并通过自定义消息通知用户更新全局静音状态
