### ISSUE TITLE
关于iOS集成问题

### ISSUE THREAD

**Issue by MondoYang** [wildfirechat/ios-chat#395]
目前我按照文档提示，集成ChatUIKit，运行release_libs.sh脚本，并导入所有framework到自己的项目中；
但是UI部分无法修改
所以请问下，应该如何修改UI？

**Comment by heavyrain2012** [comment]
可以修改UI的代码，再编译打包，把生成的新库加入到您的项目中。实际上更方便的是把chatclient和chatuikit工程拖入到你们的工程中，然后建立依赖，这样不不用生成库了

**Comment by pangyunxiu** [comment]
> 可以修改UI的代码，再编译打包，把生成的新库加入到您的项目中。实际上更方便的是把chatclient和chatuikit工程拖入到你们的工程中，然后建立依赖，这样不不用生成库了

能详细点吗？？？我不懂怎么集成。。。搞了2天了，还是集成不了
