### ISSUE TITLE
iOS单聊，用户卸载再重新安装，收到之前旧的已读消息的回调

### ISSUE THREAD

**Issue by LiuQiang11** [wildfirechat/ios-chat#396]
## 提issue小提示
  iOS单聊，用户卸载再重新安装，收到之前旧的已读消息的回调，再AppDelegate 中的onReceiveMessage回调中，收到了之前旧的已读的消息，而且消息状态还是Message_Status_Unread

**Comment by heavyrain2012** [comment]
因为消息的更新和设置的更新是分开的，协议栈先更新消息再更新设置，只有在收到设置已更新后的状态才是准确的
