### ISSUE TITLE
网络状况监控统计

### ISSUE THREAD

**Issue by zxiaokai** [wildfirechat/ios-chat#398]
可以添加一个客户端的网络状况监控统计页面，方面排查视频中的卡顿等问题
类似这种

![image](https://user-images.githubusercontent.com/19197030/186829319-444a822e-599a-46bc-8219-7d3b5cd5b8b4.png)

**Comment by heavyrain2012** [comment]
最新版本已经暴露获取统计的接口，里面应该有对应的信息

**Comment by zxiaokai** [comment]
您好！您的邮件我已收到。我将在看到邮件后尽快后，尽快给您回复。祝您工作顺利，身体健康！
