### ISSUE TITLE
Highlight the search result is not working properly

### ISSUE THREAD

**Issue by mhamidg** [wildfirechat/ios-chat#400]
Highlight the search result (iOS - Chat Search) is not working properly. Sometime it highlight the result sometime not. I have attached a video herewith. 

https://user-images.githubusercontent.com/48473070/188847548-f1a6da3f-344e-4f9e-b5e5-b1f35dd75b7f.mov

**Comment by heavyrain2012** [comment]
请用我们最新demo测试，如果发现问题请录制demo的视频，谢谢配合
