### ISSUE TITLE
使用脚本release_libs.sh生成xcframework，导入工程后，打包提审被拒。

### ISSUE THREAD

**Issue by MondoYang** [wildfirechat/ios-chat#401]
#### 操作说明

使用脚本release_libs.sh生成xcframework，导入工程后，并且动态库引入包时选择Embed & [Sign]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/15028501/192193099-a54c2702-ac8a-4d56-b4e5-9a4a1f3de7af.png">
并且能正常运行。不管是模拟器，还是打包上传到蒲公英再安装，都能正常运行。

#### 表现现象
但是我在打包上传到App Store提审的时候，在苹果那边缺会崩溃，并附上崩溃日志，说没有找到该文件
<img width="850" alt="image" src="https://user-images.githubusercontent.com/15028501/192193387-514f2586-694f-49ec-a834-6b4dfde4980e.png">

["Library not loaded: '@rpath\/WFChatClient.framework\/WFChatClient'","Referenced from: '\/Volumes\/VOLUME\/*\/PsychoTests.app\/PsychoTests'","Reason: tried: '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file), 'l\u0001"]

请问一下，这个可能是哪里的问题？

**Comment by heavyrain2012** [comment]
我们没有遇到过，野火demo上架都很正常，没有出现过问题

**Comment by heavyrain2012** [comment]
你可以看一下打包后的包里，有没有野火的sdk

**Comment by MondoYang** [comment]
我看了一下，上传到App Store上提审的包里只有WFChatUIKit.xcframework这个SDK，有时候没有WFChatClient这个SDK，有时候没有ZLPhotoBrowser，但是我这边本地打包上传蒲公英的包里面SDK就是全的。

请问一下这个是什么原因？需要我怎么处理？麻烦告知一下，万分感谢！

**Comment by heavyrain2012** [comment]
我们没有遇到过这个问题，野火demo都是正常的，你可以对比设置看看或者从网上查查看有没有包含不进去动态库的案例和解决方案

**Comment by MondoYang** [comment]
用笨办法解决了，我在没有缺失的包里，把缺失的SDK复制到要提审的包里，验证后，能够正常运行，并提包。
