### ISSUE TITLE
单独导出WFChatClient framework 文件异常

### ISSUE THREAD

**Issue by LHbeliever** [wildfirechat/ios-chat#402]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
拉到代码之后，打开ios-chat工程，我想直接导出WFChatClient framework 文件 ，真机编译直接报错，模拟器正常。
#### 表现现象
导致我无法在真机上进行测试

#### 预期结果
真机编译正常，可以正常导出WFChatClient framework 文件

#### 补充条件
必现

#### demo对比结果
无

**Comment by heavyrain2012** [comment]
项目下有个 release_libs.sh 脚本，执行这个脚本会打包生成client和kit的动态库，是xcframework格式的，包含真机，和x64+arm64两种架构的模拟器，因为是动态库，引入项目需要使用 “Embed”方式。请使用这个脚本来打包sdk

**Comment by LHbeliever** [comment]
![image](https://user-images.githubusercontent.com/16771842/195237219-040da0c7-1207-44b6-aaa6-2121e3e2839d.png)
运行了.sh 脚本打包之后的文件夹没有看到client和kit动态库

**Comment by heavyrain2012** [comment]
脚本有没有错误信息，尝试一下自己解决错误，如果无法解决错误，请把错误信息贴出来

**Comment by LHbeliever** [comment]
![image](https://user-images.githubusercontent.com/16771842/195242291-013a7d01-0f42-4cbc-8e5b-a79650bc8f53.png)
错误信息

**Comment by heavyrain2012** [comment]
我们测试了一下，用最新版本测试是正常的啊。这个图上日志看不出来根本原因，看图上client的库找不到，说明编译client就已经失败了。请用最新代码和最新xcode进行编译，如果确认是最新代码+最新xcode编译还是失败，请把所有的编译日志发邮件给 support@wildfirechat.cn

**Comment by lijuanjuan0117** [comment]
> 
我使用的最新版本14.0.1的xcode和最新的代码  也无法导出这两个库  报错日志已经发到这个邮箱  麻烦帮忙看一下  多谢！

**Comment by LHbeliever** [comment]
@lijuanjuan0117 兄弟，你弄好了没。

**Comment by lijuanjuan0117** [comment]
> @lijuanjuan0117 兄弟，你弄好了没。

你看看这个  https://github.com/wildfirechat/ios-chat/releases/tag/1.1.22

**Comment by LHbeliever** [comment]
我把framework下载下来了。但是在使用的时候，WFCCNetworkService  一旦使用到就会提示 Undefined symbol: _OBJC_CLASS_$_WFCCNetworkService 不使用这个类就是正常的，但是我初始化需要使用到这个类..

**Comment by heavyrain2012** [comment]
库是动态库，要embed

**Comment by heavyrain2012** [comment]
另外我们找了2台x86_64的电脑，操作系统和xcode全都升级到最新，打包都没有出问题，这太神奇了。。。

**Comment by lijuanjuan0117** [comment]
> 另外我们找了2台x86_64的电脑，操作系统和xcode全都升级到最新，打包都没有出问题，这太神奇了。。。

我的操作系统和xcode也都是最新，刚刚又尝试了一次  还是不能导出  但是直接运行demo是完全没问题的
