### ISSUE TITLE
Demo WFChatClient 编译错误

### ISSUE THREAD

**Issue by songyuyang0918** [wildfirechat/ios-chat#403]
version： Xcode 13.3 (13E113)
WFChatClient 编译arm64 报错
<img width="1292" alt="截屏2022-10-18 20 54 08" src="https://user-images.githubusercontent.com/15685672/196435123-71c76cf2-6ecf-4c90-9f4e-8822051a3361.png">
<img width="946" alt="截屏2022-10-18 20 54 27" src="https://user-images.githubusercontent.com/15685672/196435172-35b04980-1f7d-41ff-b941-5df041d8c369.png">

2022年10月18日下的源码
模拟器没问题，跑真机就不行了。

**Comment by heavyrain2012** [comment]
因为协议栈是用xcode14编译的，所以必须使用xcode14才可以
