### ISSUE TITLE
xcode  13.4.1 打包报 architecture armv7 报错

### ISSUE THREAD

**Issue by ienjoylife** [wildfirechat/ios-chat#406]
你好！

#### 操作说明
使用 release_libs.sh 自动打包后，将生成的 WFChatClient.xcframework  WFChatUIKit.xcframework 拖到工程中，真机可以运行，打包报以下错误：
Undefined symbols for architecture armv7:
  "_kFriendRequestUpdated", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_OBJC_CLASS_$_CreateBarCodeViewController", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCUGroupInfoViewController", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCUProfileTableViewController", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCCRecallMessageContent", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCUForwardViewController", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFAVEngineKit", referenced from:
      objc-class-ref in WFCCallKitManager.o
      objc-class-ref in DiscoverViewController.o
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCCMessage", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_kUserInfoUpdated", referenced from:
      -[WFCMeTableViewController viewDidLoad] in WFCMeTableViewController.o
  "_OBJC_CLASS_$_WFCCUtilities", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCULocationPoint", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFCULocationViewController", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFZConferenceInfo", referenced from:
      objc-class-ref in AppService.o
  "_OBJC_CLASS_$_AFHTTPRequestSerializer", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFCUBlackListViewController", referenced from:
      objc-class-ref in WFCPrivacyTableViewController.o
  "_OBJC_CLASS_$_WFCCPCLoginRequestMessageContent", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCCThingsDataContent", referenced from:
      objc-class-ref in DeviceViewController.o
  "_setQrCodeDelegate", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_OBJC_CLASS_$_WFCUConversationTableViewController", referenced from:
      objc-class-ref in WFCBaseTabBarController.o
  "_OBJC_CLASS_$_VideoPlayerKit", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFCUGeneralModifyViewController", referenced from:
      objc-class-ref in DeviceInfoViewController.o
  "_OBJC_CLASS_$_WFZHomeViewController", referenced from:
      objc-class-ref in DiscoverViewController.o
  "_OBJC_CLASS_$_WFCUMessageListViewController", referenced from:
      objc-class-ref in DiscoverViewController.o
      objc-class-ref in WFCSettingTableViewController.o
      objc-class-ref in ChatroomListViewController.o
      objc-class-ref in PCSessionViewController.o
  "_OBJC_CLASS_$_WFCUFavChannelTableViewController", referenced from:
      objc-class-ref in DiscoverViewController.o
  "_OBJC_CLASS_$_WFCCChatroomInfo", referenced from:
      objc-class-ref in ChatroomListViewController.o
  "_OBJC_CLASS_$_QQLBXScanViewController", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCUConfigManager", referenced from:
      objc-class-ref in WFCLoginViewController.o
      objc-class-ref in WFCMeTableViewHeaderViewCell.o
      objc-class-ref in WFCMeTableViewController.o
      objc-class-ref in CreateDeviceViewController.o
      objc-class-ref in WFCDiagnoseViewController.o
      objc-class-ref in WFCThemeTableViewController.o
      objc-class-ref in WFCDestroyAccountViewController.o
      ...
  "_kReceiveMessages", referenced from:
      -[DeviceViewController viewDidLoad] in DeviceViewController.o
  "_OBJC_CLASS_$_WFCUGeneralSwitchTableViewCell", referenced from:
      objc-class-ref in WFCPrivacyTableViewController.o
  "_OBJC_CLASS_$_WFCCThingsLostEventContent", referenced from:
      objc-class-ref in DeviceViewController.o
  "_OBJC_CLASS_$_AFJSONRequestSerializer", referenced from:
      objc-class-ref in AppService.o
  "_OBJC_CLASS_$_WFZConferenceInfoViewController", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCCTextMessageContent", referenced from:
      objc-class-ref in DeviceInfoViewController.o
  "_OBJC_CLASS_$_WFCUMultiVideoViewController", referenced from:
      objc-class-ref in WFCCallKitManager.o
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCUVideoViewController", referenced from:
      objc-class-ref in WFCCallKitManager.o
      objc-class-ref in AppDelegate.o
  "_MBProgressMaxOffset", referenced from:
      ___39-[WFCLoginViewController sendCodeDone:]_block_invoke in WFCLoginViewController.o
      ___40-[WFCLoginViewController onLoginButton:]_block_invoke_2 in WFCLoginViewController.o
      ___42-[CreateDeviceViewController onCreateBtn:]_block_invoke.85 in CreateDeviceViewController.o
      ___46-[WFCChangePasswordViewController onRightBtn:]_block_invoke.125 in WFCChangePasswordViewController.o
      ___43-[DeviceTableViewController viewDidAppear:]_block_invoke.60 in DeviceTableViewController.o
      ___40-[DeviceInfoViewController onDeleteBtn:]_block_invoke in DeviceInfoViewController.o
      ___40-[DeviceInfoViewController onDeleteBtn:]_block_invoke.135 in DeviceInfoViewController.o
      ...
  "_OBJC_CLASS_$_BubbleTipView", referenced from:
      objc-class-ref in DiscoverMomentsTableViewCell.o
  "_OBJC_CLASS_$_WFCUContactListViewController", referenced from:
      objc-class-ref in WFCBaseTabBarController.o
  "_OBJC_CLASS_$_WFCUFilesEntryViewController", referenced from:
      objc-class-ref in WFCMeTableViewController.o
  "_OBJC_CLASS_$_SDPhotoBrowser", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFCUMyProfileTableViewController", referenced from:
      objc-class-ref in WFCMeTableViewController.o
  "_OBJC_CLASS_$_WFCUBrowserViewController", referenced from:
      objc-class-ref in DiscoverViewController.o
      objc-class-ref in WFCBaseTabBarController.o
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFCUMessageSettingViewController", referenced from:
      objc-class-ref in WFCMeTableViewController.o
  "_OBJC_CLASS_$_WFCUCompositeMessageViewController", referenced from:
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFCCIMService", referenced from:
      objc-class-ref in WFCMeTableViewController.o
      objc-class-ref in DeviceViewController.o
      objc-class-ref in DeviceInfoViewController.o
      objc-class-ref in WFCCallKitManager.o
      objc-class-ref in WFCPrivacyTableViewController.o
      objc-class-ref in WFCFavoriteTableViewController.o
      objc-class-ref in ChatroomListViewController.o
      ...
  "_OBJC_CLASS_$_MBProgressHUD", referenced from:
      objc-class-ref in WFCLoginViewController.o
      objc-class-ref in CreateDeviceViewController.o
      objc-class-ref in WFCChangePasswordViewController.o
      objc-class-ref in DeviceTableViewController.o
      objc-class-ref in DeviceInfoViewController.o
      objc-class-ref in WFCDestroyAccountViewController.o
      objc-class-ref in PCSessionViewController.o
      ...
  "_OBJC_CLASS_$_WFCCConversation", referenced from:
      objc-class-ref in AppService.o
      objc-class-ref in DeviceViewController.o
      objc-class-ref in DeviceInfoViewController.o
      objc-class-ref in DiscoverViewController.o
      objc-class-ref in WFCSettingTableViewController.o
      objc-class-ref in ChatroomListViewController.o
      objc-class-ref in PCSessionViewController.o
      ...
  "_OBJC_CLASS_$_AFHTTPSessionManager", referenced from:
      objc-class-ref in AppService.o
      objc-class-ref in WFCDiagnoseViewController.o
      objc-class-ref in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_StyleDIY", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCCCallStartMessageContent", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WFCUFavoriteItem", referenced from:
      objc-class-ref in AppService.o
  "_CSToastPositionCenter", referenced from:
      ___44-[WFCFavoriteTableViewController playSound:]_block_invoke.113 in WFCFavoriteTableViewController.o
      -[WFCFavoriteTableViewController performCopy:] in WFCFavoriteTableViewController.o
  "_OBJC_CLASS_$_WFCUUtilities", referenced from:
      objc-class-ref in WFCLoginViewController.o
      objc-class-ref in WFCFavoriteBaseCell.o
      objc-class-ref in WFCChangePasswordViewController.o
      objc-class-ref in WFCFavoriteCompositeCell.o
      objc-class-ref in DeviceViewController.o
      objc-class-ref in WFCDestroyAccountViewController.o
      objc-class-ref in WFCFavoriteTableViewController.o
      ...
  "_OBJC_CLASS_$_WFCUGroupAnnouncement", referenced from:
      objc-class-ref in AppService.o
  "_OBJC_CLASS_$_WFCCNetworkService", referenced from:
      objc-class-ref in WFCLoginViewController.o
      objc-class-ref in AppService.o
      objc-class-ref in WFCMeTableViewController.o
      objc-class-ref in CreateDeviceViewController.o
      objc-class-ref in DeviceInfoViewController.o
      objc-class-ref in WFCDestroyAccountViewController.o
      objc-class-ref in WFCSettingTableViewController.o
      ...
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

期望可以正常打包

**Comment by heavyrain2012** [comment]
请使用 最新xcode版本测试

**Comment by ienjoylife** [comment]
多谢，解决了
