### ISSUE TITLE
iOS 输入手机号 短信 666666，使用社区版服务登录失败

### ISSUE THREAD

**Issue by ienjoylife** [wildfirechat/ios-chat#407]
#### 操作说明
在官网选项 快速开发服务器部署，IM服务下载后解压后运行 wildfirechat.sh脚本 提示成功后，和 应用服务软件 下载 app-0.61.jar 启动成功，使用http://${服务器的IP}/api/version，http://${服务器的IP}:8888/ 都可以正常访问。ios 代码在 github下载成功，使用默认配置可以正常聊天，将配置文件 IM_SERVER_HOST, 改成对应本地服务ip,APP_SERVER_ADDRESS 改成本地服务ip:8888 运行，登录的时候前端会报 login error with code 6, message 验证码或密码错误。 控制台会报：hat.app.shiro.AuthDataSource  : code not exist；有时会成功，但多数情况失败。

**Comment by heavyrain2012** [comment]
超级验证码是五个6，不是六个

**Comment by ienjoylife** [comment]
多谢，解决了
