### ISSUE TITLE
ios欢迎语是乱码

### ISSUE THREAD

**Issue by xielinkin100** [wildfirechat/ios-chat#41]
<img width="372" alt="QQ20190723-013825@2x" src="https://user-images.githubusercontent.com/53071293/61652476-9d20ad80-acea-11e9-99c2-cec00e35a28e.png">

**Comment by shengluoto** [comment]
服务端的配置文件中的欢迎语编码错误,修改下就好

**Comment by heavyrain2012** [comment]
请确保应用服务所在的服务器支持中文
