### ISSUE TITLE
使用官方下载服务布署自己服务器上，ios端调用接口logs/1ygqmws2k/upload 报错

### ISSUE THREAD

**Issue by ienjoylife** [wildfirechat/ios-chat#411]
## 提issue小提示
ios使用官方下载的代码，改为自己的服务器地址后，其他接口正常，上传日志logs/1ygqmws2k/upload  报错，返回如下错误
     code = 4;
    message = "服务器异常";
    result = "<null>";

后端控制台有报：
please ensure that your Secretid is correct.requrestId:005f3b2c-
不知道是否跟这个有关

**Comment by heavyrain2012** [comment]
我demo测试过，demo是可以上传的，想不出来什么情况会报这个错误。实际上所有关于日志上传的代码都是开源的，你们可以debug看一下是哪里出错了
