### ISSUE TITLE
ios专业版瘦身

### ISSUE THREAD

**Issue by lh0072** [wildfirechat/ios-chat#418]
文档提示“视频库为动态库，包含有arm64和x64架构，可以支持真机和模拟器运行。应用的依赖库方式应该是```Embed```.上架时，需要对库进行瘦身，使用```ios-chat/wfchat/removex86.sh```来瘦身。”
但是我在ios-chat/wfchat文件里没有看到removex86.sh这个文件  无法执行操作  请问怎么获取这个removex86.sh文件？

**Comment by heavyrain2012** [comment]
最新的iOS代码打包所有库都是xcframework方式，这种格式的库就不用移除x86架构了

**Comment by heavyrain2012** [comment]
如果你手上的库是framework格式的，可以利用lipo命令来去除x86架构，也可以联系我们更新最新版本的库

**Comment by heavyrain2012** [comment]
关于去除x86架构，可以百度搜索，比如 https://www.baidu.com/s?wd=lipo+%E5%8E%BB%E9%99%A4x86%E6%9E%B6%E6%9E%84&tn=84053098_3_dg&ie=utf-8

**Comment by lh0072** [comment]
哦哦  我不是最新的但也是比较新的代码  库是xcframework 那就不用处理了  感谢
