### ISSUE TITLE
Android发起群内语音会话，iPhone群会话页面顶部不显示主动加入通话的提醒

### ISSUE THREAD

**Issue by niyongsheng** [wildfirechat/ios-chat#420]
Iphone发起群内语音通话，群内的iPhone用户可以看到主动加入通话的提示条，但Android手机发起群组内语音通话时，群内iphone用户不显示主动加入通话的提示条；

**Comment by imndx** [comment]
音视频 SDK 是多人版，还是高级版？

**Comment by imndx** [comment]
Android端```Config.java```里面有个```ENABLE_MULTI_CALL_AUTO_JOIN```选项，默认是```false```，请置为```true```，然后测试下
