### ISSUE TITLE
在本示例项目中没有找到 WFAVEnginekit 的开源框架

### ISSUE THREAD

**Issue by YvanSwen** [wildfirechat/ios-chat#424]
如题。请尽快更新下或者给个下载地址，感谢。

**Comment by heavyrain2012** [comment]
音视频库是闭源的，如果需要源码可以联系我们购买，源码为 https://docs.wildfirechat.cn/price/  中的”Mesh架构音视频源码“

**Comment by heavyrain2012** [comment]
关于音视频的库有2个，一个是WFAVEngineKit，另外一个是WebRTC，在这个目录下 https://github.com/wildfirechat/ios-chat/tree/master/wfuikit/WFChatUIKit/AVEngine
