### ISSUE TITLE
关于蓝牙耳机的使用问题

### ISSUE THREAD

**Issue by guopingzhang** [wildfirechat/ios-chat#425]
操作说明
iOS版本，当用户手机连接蓝牙耳机时加入会议，会议进行中断开蓝牙耳机，会议的声音会从手机听筒出来

表现现象
会议进行中断开蓝牙耳机，会议的声音会从手机听筒出来

预期结果
会议进行中断开蓝牙耳机，我们希望耳机断开后声音从扬声器出来

补充条件
必现，蓝牙耳机，iOS 音视频SDK是2022年12月14号版本

demo对比结果
demo也存在这个问题

**Comment by heavyrain2012** [comment]
断开耳机后，声音可以有2个选择，要么是听筒要么是扬声器，综合起来应该是听筒更合适，因为有些场合如果蓝牙断开突然扬声器也不是太好。请检查蓝牙断开后的状态，如果状态是听筒且确实是听筒的声音，那就没有问题
