### ISSUE TITLE
ios发送包含图片和文字的合并转发消息，桌面端文字显示乱码

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/ios-chat#428]
#### 操作说明
1，ios发送包含图片和文字的合并转发消息；
2，桌面端通过remotePath下载解析后，文字会乱码；

#### 表现现象
APP两端之间显示没问题，最新的PC端demo 也有这样的问题；
![HENGLNK截图_1675397299510](https://user-images.githubusercontent.com/23655609/216511334-dbf27fd4-3856-4be3-af24-62fb44334c4a.jpg)

#### 预期结果
文字正常显示；

#### 补充条件
必现

#### demo对比结果
最新的PC端demo 也有这样的问题；

**Comment by imndx** [comment]
用```vue-pc-chat```的最新代码测试了下，没有复现问题。

请问还有什么信息，或者复现办法吗？

**Comment by guodonghuang** [comment]
> 用`vue-pc-chat`的最新代码测试了下，没有复现问题。
> 
> 请问还有什么信息，或者复现办法吗？
建议用大一点的图片（我用的10M图片），
具体复现步骤：
1，用iOS端，给A发数张图片和中文，
2，多选图片和中文，合并转发给其他人或群组，
3，桌面端打开合并消息，中文就会显示乱码，
素材图片和复现视频会附上；

[10M - 1.zip](https://github.com/wildfirechat/ios-chat/files/10660169/10M.-.1.zip)


https://user-images.githubusercontent.com/23655609/216895522-2e679e7d-d332-4347-8488-d68456d5e4b6.mp4
