### ISSUE TITLE
iOS 手机端A进入后台后，B 手机端给A 发消息，无法收到推送消息

### ISSUE THREAD

**Issue by andi911** [wildfirechat/ios-chat#429]
#### 表现现象
iOS 手机端A进入后台后，B 手机端给A 发消息，无法收到推送消息，打开A 手机端，是能收到消息的

#### 预期结果
A 手机用户 app 进入后台，接收到消息应该像微信一个弹出一个通知

**Comment by heavyrain2012** [comment]
应用在后台后会被系统冻结，这个时候需要走APNS远程推送才能收到通知。请检查我们的推送服务，部署和调试好之后就可以了

**Comment by andi911** [comment]
亲，能甩个链接给我看看么

**Comment by heavyrain2012** [comment]
https://github.com/wildfirechat/push_server
