### ISSUE TITLE
聊天界面里, WFCUChatInputBar和下面的弹出键盘的间隔大小在哪里修改?

### ISSUE THREAD

**Issue by TWY-9238944** [wildfirechat/ios-chat#430]
![WechatIMG10](https://user-images.githubusercontent.com/53074680/218404203-caaf01ae-d3e6-4c13-9bda-58d643788e9f.jpeg)

**Comment by heavyrain2012** [comment]
WFCUMessageListViewController.m中的下面这个方法

- (void)willChangeFrame:(CGRect)newFrame withDuration:(CGFloat)duration keyboardShowing:(BOOL)keyboardShowing
