### ISSUE TITLE
iOS音视频会议，摄像头前后切换，画面会先镜像卡一下，然后再切换过来，demo有次问题；

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/ios-chat#434]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
demo存在该问题
1，iOS端，开启音视频会议
2，进入会议，打开摄像头，正常显示视频画面
3，切换前后摄像头，视频画面先镜像，卡一下，再切换

#### 表现现象
切换前后摄像头，视频画面先镜像，卡一下，再切换

#### 预期结果
切换前后摄像头，视频画面直接切换，不出现镜像画面

#### 补充条件
demo必须

#### demo对比结果
demo必须

**Comment by heavyrain2012** [comment]
这个没有好办法，因为前置摄像头需要旋转一下，这样当和后置摄像头切换时，就需要做旋转
