### ISSUE TITLE
ios断开连接一直无法重连，一直展示未连接，需要切换网络后才能恢复正常

### ISSUE THREAD

**Issue by huawenhe** [wildfirechat/ios-chat#435]

**Comment by heavyrain2012** [comment]
把协议栈日志发给support@wildfirechat.cn , 我们分析一下日志

**Comment by heavyrain2012** [comment]
收到日志了，不过看日志是2023.1.17的日志，请确认日志时间时对的吗？另外请给出一些必要的信息，比如大概什么时候连不上的，连不上持续了多久，什么时候恢复的？

**Comment by huawenhe** [comment]
日志时间没有错是那个时间段的，就是自动断网然后重新自动连接会出现连接不上，一直都是未连接状态，这个时候需要手动切换网络才会重新连接成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 上午10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/ios-chat] ios断开连接一直无法重连，一直展示未连接，需要切换网络后才能恢复正常 (Issue #435)





 
收到日志了，不过看日志是2023.1.17的日志，请确认日志时间时对的吗？另外请给出一些必要的信息，比如大概什么时候连不上的，连不上持续了多久，什么时候恢复的？

**Comment by heavyrain2012** [comment]
从日志里看，有非常多的，这说明要么是服务器有问题，要么网络有问题
```
close connect err:(51, Network is unreachable)
```

**Comment by heavyrain2012** [comment]
另外从日志中看到有非常多的调用sdk的connect，理论上只需要调用一次就行，不要反复地调用

**Comment by huawenhe** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wildfirechat/ios-chat] ios断开连接一直无法重连，一直展示未连接，需要切换网络后才能恢复正常 (Issue #435)





 
另外从日志中看到有非常多的调用sdk的connect，理论上只需要调用一次就行，不要反复地调用
