### ISSUE TITLE
pdf、txt等文件打开是空白页面

### ISSUE THREAD

**Issue by DevXieChao** [wildfirechat/ios-chat#437]
聊天页面-发文件(pdf、txt等)消息，点击消息，跳转页面打开的是空白页
项目中用到这个库 DWKWebView 加载文件 现在有问题
使用loadUrl时，页面无法加载，显示页面空白

**Comment by heavyrain2012** [comment]
如果换个webview，可以加载吗？请验证一下时webview的问题，还是别的原因？
