### ISSUE TITLE
在X-Code14.3中Demo无法正常编译

### ISSUE THREAD

**Issue by supportFor** [wildfirechat/ios-chat#439]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
1、从Github下载此项目Demo
2、使用X-Code14.3打开此项目
3、运行此项目时报错

#### 表现现象
在最新版本X-Code中无法正常运行此项目
报错提示：
file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### 预期结果
请纠正此错误并上传修复文件

#### 补充条件
这个情况是必现的

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by heavyrain2012** [comment]
请用appstore上的最新正式版。beta版本无法支持
