### ISSUE TITLE
创建会话页面，快速点击用户cell进行增加减少用户会闪退

### ISSUE THREAD

**Issue by aiyouBug** [wildfirechat/ios-chat#440]
目前可以通过 注释以下代码在保证功能实现的情况解决该闪退问题
        __weak typeof(self)weakSelf = self;

        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            if (weakSelf.type == Vertical) {
                [weakSelf.selectedUserCollectionView scrollToItemAtIndexPath:insertIndexPath atScrollPosition:UICollectionViewScrollPositionTop animated:YES];
            } else {
                [weakSelf.selectedUserCollectionView scrollToItemAtIndexPath:insertIndexPath atScrollPosition:UICollectionViewScrollPositionLeft animated:YES];
            }
            
        });

**Comment by heavyrain2012** [comment]
已解决，请查看提交 https://github.com/wildfirechat/ios-chat/commit/87ef5331266cea4567bf96488df174fd97778a4e 。谢谢您的提醒
