### ISSUE TITLE
WFChatClient 最新的release版本，崩溃

### ISSUE THREAD

**Issue by LiuQiang11** [wildfirechat/ios-chat#442]
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
0x00000001f6ca4000 + 32876
2
WFChatClient
_ZN9Condition4waitER14BaseScopedLockI5MutexE + 204
3
WFChatClient
_ZN12_GLOBAL__N_120__anr_checker_threadEv + 544
4
WFChatClient
_ZN6Thread13start_routineEPv + 76
5
libsystem_pthread.dylib
_pthread_start + 148

**Comment by LiuQiang11** [comment]
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
0x00000001f1df5000 + 32876
2
WFChatClient
_ZN9Condition4waitER14BaseScopedLockI5MutexE + 204
3
WFChatClient
_ZN12_GLOBAL__N_120__anr_checker_threadEv + 544
4
WFChatClient
_ZN6Thread13start_routineEPv + 76
5
libsystem_pthread.dylib
_pthread_start + 148

**Comment by heavyrain2012** [comment]
从图上的栈信息来看，是在wait状态，看不出明显的崩溃信息来。崩溃是崩溃收集工具抓取的？还是自己debug运行发现的？如果是崩溃工具收集的，请提供崩溃收集工具上的所有信息；如果是debug出现的，请给出崩溃的截图和当时的控制台输出

**Comment by LiuQiang11** [comment]
崩溃信息是bugly收集到的，以下是详细的崩溃信息：

#0 Thread
UncaughtExceptionHandlerSignalExceptionName
Application received signal SIGSEGV
解析原始
0
libsystem_kernel.dylib
0x00000001e1171c84 0x00000001e1171000 + 3196

2
libsystem_kernel.dylib
0x00000001e1179034 0x00000001e1171000 + 32560
3
???
0x000000016bcc0aa8 0x00000001068f1078 + 0
#0 Thread
0
libsystem_kernel.dylib
mach_msg2_trap + 8

2
libsystem_kernel.dylib
thread_get_state + 260
3
???
0x00000001068f1078 + 0
#1 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#2 Thread
0
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
0x0000000201def000 + 32888
2
WFChatClient
_ZN9Condition4waitER14BaseScopedLockI5MutexE + 204
3
WFChatClient
_ZN12_GLOBAL__N_120__anr_checker_threadEv + 544
4
WFChatClient
_ZN6Thread13start_routineEPv + 76
5
libsystem_pthread.dylib
_pthread_start + 148
#3 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#4 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#5 com.apple.uikit.eventfetch-thread
0
libsystem_kernel.dylib
mach_msg2_trap + 8

11
libsystem_pthread.dylib
_pthread_start + 148
#6 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#7 Thread
0
libsystem_kernel.dylib
stat + 8
1
Foundation
0x000000019c738000 + 178820
2
Jump
__cxa_throw + 23276
3
Jump
__cxa_throw + 22988
4
Jump
__cxa_throw + 20072
5
Foundation
0x000000019c738000 + 684180

17
libsystem_pthread.dylib
_pthread_wqthread + 228
#8 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#9 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#10 JavaScriptCore libpas scavenger
0
libsystem_kernel.dylib
__psynch_cvwait + 8

3
libsystem_pthread.dylib
_pthread_start + 148
#11 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#12 com.apple.NSURLConnectionLoader
0
libsystem_kernel.dylib
mach_msg2_trap + 8

9
libsystem_pthread.dylib
_pthread_start + 148
#13 Thread
0
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
0x0000000201def000 + 32888
2
WFChatClient
_ZN9Condition4waitER14BaseScopedLockI5MutexEl + 344
3
WFChatClient
_ZN6Thread19start_routine_afterEPv + 124
4
libsystem_pthread.dylib
_pthread_start + 148
#14 Thread
0
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
0x0000000201def000 + 32888
2
WFChatClient
_ZN9Condition4waitER14BaseScopedLockI5MutexEl + 344
3
WFChatClient
_ZL18__async_log_threadv + 376
4
WFChatClient
_ZN6Thread13start_routineEPv + 76
5
libsystem_pthread.dylib
_pthread_start + 148
#15 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#16 Thread
0
libsystem_kernel.dylib
__workq_kernreturn + 8
1
libsystem_pthread.dylib
_pthread_wqthread + 364
#17 io.jiguang.hxhg.cache
0
libsystem_kernel.dylib
mach_msg2_trap + 8

7
CoreFoundation
CFRunLoopRun + 64
8
Jump
0x0000000104138000 + 17463528
9
Foundation
0x000000019c738000 + 374324
10
libsystem_pthread.dylib
_pthread_start + 148
#18 org.hxhg.jiguang.thread
0
libsystem_kernel.dylib
mach_msg2_trap + 8

8
Foundation
0x000000019c738000 + 270168
9
Jump
0x0000000104138000 + 16982476
10
Foundation
0x000000019c738000 + 374324
11
libsystem_pthread.dylib
_pthread_start + 148
#19 Thread
0
libsystem_kernel.dylib
__semwait_signal + 8

2
libsystem_c.dylib
sleep + 52
3
Jump
__cxa_throw + 4890520
4
libsystem_pthread.dylib
_pthread_start + 148
#20 KSCrash Exception Handler (Secondary)
0
libsystem_kernel.dylib
mach_msg2_trap + 8

3
libsystem_kernel.dylib
mach_msg + 24
4
Jump
__cxa_throw + 4682240
5
libsystem_pthread.dylib
_pthread_start + 148
#21 io.jiguang.hxhg.network
0
libsystem_kernel.dylib
mach_msg2_trap + 8

7
CoreFoundation
CFRunLoopRun + 64
8
Jump
0x0000000104138000 + 17052020
9
Foundation
0x000000019c738000 + 374324
10
libsystem_pthread.dylib
_pthread_start + 148
#22 Thread
0
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
0x0000000201def000 + 32888
2
WFChatClient
_ZN9Condition4waitER14BaseScopedLockI5MutexEl + 344
3
WFChatClient
_ZN12MessageQueue7RunLoop3RunEv + 1280
4
WFChatClient
_ZN12MessageQueue19MessageQueueCreater15__ThreadRunloopEv + 56
5
WFChatClient
_ZN6Thread13start_routineEPv + 76
6
libsystem_pthread.dylib
_pthread_start + 148
#23 mars::stn
0
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
0x0000000201def000 + 32888
2
WFChatClient
_ZN9Condition4waitER14BaseScopedLockI5MutexEl + 344
3
WFChatClient
_ZN12MessageQueue7RunLoop3RunEv + 1280
4
WFChatClient
_ZN12MessageQueue19MessageQueueCreater15__ThreadRunloopEv + 56
5
WFChatClient
_ZN6Thread13start_routineEPv + 76
6
libsystem_pthread.dylib
_pthread_start + 148
#24 mars::stn::lonklink
0
libsystem_kernel.dylib
poll + 8
1
WFChatClient
_ZN10SocketPoll4PollEi + 204
2
WFChatClient
_ZN4mars3stn8LongLink14__RunReadWriteEiRNS0_10ErrCmdTypeERiRNS0_14ConnectProfileE + 2364
3
WFChatClient
_ZN4mars3stn8LongLink5__RunEv + 1736
4
WFChatClient
_ZN6Thread13start_routineEPv + 76
5
libsystem_pthread.dylib
_pthread_start + 148
#25 com.apple.CFSocket.private
0
libsystem_kernel.dylib
__select + 8

2
libsystem_pthread.dylib
_pthread_start + 148

**Comment by heavyrain2012** [comment]
上面的信息格式问题，看得不是很清楚，大概能看出是#0线程崩溃了，而#0线程的调用栈中没有野火的，说明不是崩溃在野火的SDK中
