### ISSUE TITLE
不能只使用主网络问题

### ISSUE THREAD

**Issue by yoffey** [wildfirechat/ios-chat#444]
#### 操作说明
ios从后台切换到前台,且ios端添加了这行代码 ：[[WFCCNetworkService sharedInstance] setBackupAddressStrategy:1];

#### 表现现象
ios还是会发起复合连接

#### 预期结果
应该只使用主网络，不应该发起复合连接
参考这个文档的描述：https://docs.wildfirechat.cn/blogs/%E6%94%BF%E4%BC%81%E5%86%85%E5%A4%96%E5%8F%8C%E7%BD%91%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.html

**Comment by heavyrain2012** [comment]
因为协议栈会有各种各样的缓存，所以设置网络策略只能在应用启动时设置一次，不能在使用过程中修改策略

**Comment by yoffey** [comment]
我们就是在应用启动的时候设置了一次，但是看协议栈日志还是会发起复合链接，是不是设置策略的地方不对？
是在建立长链接前设置，还是在建立长链接后设置？

**Comment by yoffey** [comment]
还有一个事情想确认下，如果t_user_server里面已经有两个长连接地址以后，再把网络策略设置成1，是不是不会生效？
需不需要先卸载重装清除一下本地数据，然后才能保证一直使用主网络？

**Comment by heavyrain2012** [comment]
> 我们就是在应用启动的时候设置了一次，但是看协议栈日志还是会发起复合链接，是不是设置策略的地方不对？
> 是在建立长链接前设置，还是在建立长链接后设置？

需要在connect之前设置，也就是应用一启动就要设置，之后才是设置地址端口等

**Comment by heavyrain2012** [comment]
> 还有一个事情想确认下，如果t_user_server里面已经有两个长连接地址以后，再把网络策略设置成1，是不是不会生效？
> 需不需要先卸载重装清除一下本地数据，然后才能保证一直使用主网络？

社区版IM服务不支持，因为这里面逻辑比较复杂
