### ISSUE TITLE
在浏览聊天记录图片的时候，如果默认打开的是视频文件，往后滑动到图片文件的时候，加载高清图片的进度条不动或者加载完后不展示

### ISSUE THREAD

**Issue by aiyouBug** [wildfirechat/ios-chat#445]
在浏览聊天记录图片的时候，如果默认打开的是视频文件，往后滑动到图片文件的时候，加载高清图片的进度条不动或者加载完后不展示，只有等到划到下张之后再回来才展示。demo同样有该问题
录屏如下：https://wclw.oss-cn-hangzhou.aliyuncs.com/1/2023-05-11/1683816575049-e83198ba-f833-4f77.mp4

**Comment by heavyrain2012** [comment]
请检查提交 https://github.com/wildfirechat/ios-chat/commit/84d9f09171251146d7b552be5d17301a2c8eb61d
