### ISSUE TITLE
链接没有加http，跳转后是空白页面问题定位

### ISSUE THREAD

**Issue by DevXieChao** [wildfirechat/ios-chat#448]
Demo上iOS端：IM聊天窗口发送链接 baidu.com和www.baidu.com 在wkwebview上打不开

https://www.baidu.com 可以打开

baidu.com和www.baidu.com和https://www.baidu.com
Demo上安卓端和mac端 都可以识别出来链接并能打开网页

期望：iOS端也能支持一下

**Comment by heavyrain2012** [comment]
浏览器vc加了判断，如果没有schema头，就加上http的schema。另外判断链接的正则表达式，只能判断以http/ftp/www开头的链接，像www.baidu.com是可以识别出来的，但baidu.com不能识别出来。我们认为这样处理是合适的，如果你们要改，可以修改，正则表达式在 AttributedLabel.m 这个文件中搜索 regulaStr
