### ISSUE TITLE
图片发送

### ISSUE THREAD

**Issue by china23z** [wildfirechat/ios-chat#45]
图片发送可以加个进度吗?

**Comment by heavyrain2012** [comment]
功能库是有发送进度的回调的，UI上加上就可以。我们目前人力比较紧张，你可以自己加上然后给我们提Pull Request。或者等我们以后加也可以。

**Comment by heavyrain2012** [comment]
请参考 https://github.com/wildfirechat/ios-chat/commit/94d940ef854395763f107f773ee2f43bc5333d75
