### ISSUE TITLE
iOS 共享屏幕模糊

### ISSUE THREAD

**Issue by hiiRobert** [wildfirechat/ios-chat#452]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
iOS 在会议中，使用共享屏幕功能

#### 表现现象
iOS 共享屏幕模糊，AppStore上的`野火IM`同样模糊

#### 预期结果
需要清晰些

#### 补充条件
必现（SDK是2023年6月28号的版本）

#### demo对比结果
AppStore上的`野火IM`同样模糊

**Comment by heavyrain2012** [comment]
问题查出来了，是捕获视频时裁剪太少，更新最新代码可以解决
