### ISSUE TITLE
iOS共享过程中切换网络，其他设备显示黑屏

### ISSUE THREAD

**Issue by hiiRobert** [wildfirechat/ios-chat#454]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
进入会议，iOS开始共享屏幕，其他设备正常显示共享内容。然后切换网络（如WiFi到流量），其他设备显示黑屏，看不到任何内容

#### 表现现象
进入会议，iOS开始共享屏幕，其他设备正常显示共享内容。然后切换网络（如WiFi到流量），其他设备显示黑屏，看不到任何内容

#### 预期结果
iOS共享过程中切换网络，其他设备查看共享内容应该正常显示，而不是黑屏

#### 补充条件
必现

#### demo对比结果
App Store上`野火IM`也有此问题

**Comment by heavyrain2012** [comment]
最新音视频高级版已经解决
