### ISSUE TITLE
需要解决的问题

### ISSUE THREAD

**Issue by ceshi8899** [wildfirechat/ios-chat#456]
问题
1、苹果手机修改密码后，返回页面无法使用密码登录，提示“登录失败”，安卓手机正常。
2、苹果手机可直接修改，安卓手机需在对话中发送图片，获取权限后，才能设置头像。
3、苹果手机--我的--账号与安全中，无法修改绑定手机号，输入手机号码点击确认，提示“更新失败”
4、点开好友用户信息，点击有角...，显示设置“取消星标好友”，操作后实际操作为设置星标好友，提示语错误，相反，取消星标好友的提示语为“设置星标好友”，显示错误。
5、苹果手机退出登录，显示可退出账号、销毁账号（需要去掉销毁账号功能）、安卓手机正常
6、删除好友后，联系人列表不显示该用户，对话列表仍显示，可以向对方发送信息，对方也能收到，点击头像查看信息显示可添加对方好友
7、苹果手机在群聊界面，有其他群聊用户在输入或发送消息时，软键盘会自动缩回
8、苹果手机私聊中的视频，无法查看，安卓手机正常，群聊中正常
9苹果手机无法发送文件、安装包，转发正常，安卓手机正常
10、手机、电脑保存群聊，两边通讯录不同步，手机保存的电脑不显示，电脑保存的，手机不显示

**Comment by heavyrain2012** [comment]
问题
1、苹果手机修改密码后，返回页面无法使用密码登录，提示“登录失败”，安卓手机正常。
修改密码有2种方式，一种是输入旧密码修改新密码，另外一种是收取短信验证码修改。这边测试短信验证码修改时用超级密码错误（已经在应用服务提交修改），其他情况没有发现错误，请确认具体测试方法

2、苹果手机可直接修改，安卓手机需在对话中发送图片，获取权限后，才能设置头像。
这个是android的问题，请在android项目中跟进

3、苹果手机--我的--账号与安全中，无法修改绑定手机号，输入手机号码点击确认，提示“更新失败”
目前没有修改手机号码的功能，如果你们需要，可以自己来加这个功能。这个功能需要在应用服务开发功能。

4、点开好友用户信息，点击有角...，显示设置“取消星标好友”，操作后实际操作为设置星标好友，提示语错误，相反，取消星标好友的提示语为“设置星标好友”，显示错误。
这个问题已经修改，请参考ios项目的最新提交

5、苹果手机退出登录，显示可退出账号、销毁账号（需要去掉销毁账号功能）、安卓手机正常
这是因为苹果商店上架要求必须有销毁账户功能，你们可以修改一下，把这个菜单去掉。（如果你们要上架，也是需要这个功能的）

6、删除好友后，联系人列表不显示该用户，对话列表仍显示，可以向对方发送信息，对方也能收到，点击头像查看信息显示可添加对方好友
好友关系和消息功能是独立无关的。如果你们需要删除好友后不显示对话列表，可以修改代码删除成功后同时删除会话信息。如果要不是好友不能发消息，可以在IM服务配置不允许陌生人发送消息或者删除好友成功后把对方拉入黑名单

7、苹果手机在群聊界面，有其他群聊用户在输入或发送消息时，软键盘会自动缩回
已接近，请在ios项目查看最新提交

8、苹果手机私聊中的视频，无法查看，安卓手机正常，群聊中正常
没有复现出来，我们测试方法是，用一个ios手机A给另外一个ios手机B发送视频消息，分别在单聊和群聊各发一条，在手机B上都可以查看这两个视频。请详细描述测试方法。

9、苹果手机无法发送文件、安装包，转发正常，安卓手机正常
请提供这个测试方法

10、手机、电脑保存群聊，两边通讯录不同步，手机保存的电脑不显示，电脑保存的，手机不显示
这边测试正常，请确认2端都网络良好，发送消息也能及时同步。如果这个问题是偶现的，请联系我们工程师
