### ISSUE TITLE
会话表的未读计数和消息表状态为未读的消息数对不上

### ISSUE THREAD

**Issue by yoffey** [wildfirechat/ios-chat#457]
#### 表现现象
偶现，无必现步骤。
本地sqlite数据库中，同一个会话，t_message表的消息状态是未读的消息数，和t_conversation表的未读数量不一致。
截图如下：
![t_message](https://github.com/wildfirechat/ios-chat/assets/22340032/7b1211c2-c60f-4b5a-9188-2ca06957b31c)

![t_conversation](https://github.com/wildfirechat/ios-chat/assets/22340032/73c2fbe9-6e72-4f7e-85eb-9436b8631a98)

#### 预期结果
同一个会话，t_conversation表的未读数和t_message表未读消息数量一致
这种不一致看着像是协议栈逻辑控制出了问题导致的，麻烦帮忙看下是否协议栈的逻辑存在问题

**Comment by heavyrain2012** [comment]
前一段好像修复过这个问题，确认一下协议栈是否是最新版本

**Comment by yoffey** [comment]
协议栈版本是23年4.23号的版本，麻烦帮忙确认下是否在这个时间后有修复这个问题，有的话我们升级协议栈再看下

**Comment by heavyrain2012** [comment]
有修复，请更新最新测试看看
