### ISSUE TITLE
群聊页面的消息已读有bug

### ISSUE THREAD

**Issue by DevXieChao** [wildfirechat/ios-chat#459]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象
A 已读 C  发的消息，1人已读，然后把 A 移出群聊，聊天页面还是 1 人已读

#### 预期结果
 A 被移出群聊，聊天页面应是 0 人已读

#### 补充条件
必现，iOS、Android都存在这个问题

#### demo对比结果
demo也存在此问题

**Comment by heavyrain2012** [comment]
iOS最新版本已经解决，请更新验证
