### ISSUE TITLE
覆盖安装出错

### ISSUE THREAD

**Issue by LuShanshan633** [wildfirechat/ios-chat#46]
[DB2.cc, RecyclableStatement, 33][prepare db error:26 info:file is not a database sql:replace into t_friend(_friend_uid,_state,_update_dt,_alias) values(?,?,?,?)

重新登录也拉不到数据，，卸载了才可以

**Comment by LuShanshan633** [comment]
不打开app，接收消息700条以上，数据库就挂掉了

**Comment by heavyrain2012** [comment]
appstore与debug模式下互相覆盖安装有问题，appstore升级没有问题，这个问题我们会继续跟进。

**Comment by heavyrain2012** [comment]
该问题在最新版本上已经解决，问题关闭
