### ISSUE TITLE
群聊已读未读人数有bug

### ISSUE THREAD

**Issue by DevXieChao** [wildfirechat/ios-chat#460]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象
原先群内已存在沟通消息。后面添加新群成员，虽然新群成员不能看到历史消息，但是历史消息的“已读/未读”人数包含后进群的人员。

#### 预期结果
群内再添加了新群成员，如果设置“允许新成员查看历史消息”
结果：
新群成员能看到历史消息，历史消息的“已读/未读”人数：应当包含 后进群的人员。

群内再添加了新群成员，如果设置“不允许新成员查看历史消息”
结果：
新群成员不能看到历史消息，历史消息的“已读/未读”人数：应当不包含 后进群的人员。

#### 补充条件
必现，iOS、安卓、PC都有这个问题

#### demo对比结果
demo也存在此问题

**Comment by heavyrain2012** [comment]
iOS已经解决
