### ISSUE TITLE
app store的野火客户端安装后打开不了微软word导出的pdf

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/ios-chat#462]
#### 操作说明
用微软word导出pdf
通过网页版发到iOS端

#### 表现现象
iOS会话里点开显示白屏

#### 预期结果
能正常显示pdf

这是会话
![image](https://github.com/wildfirechat/ios-chat/assets/11338629/41d95bba-9027-4522-8d20-ecd063262a4f)
这是用safari打开后下载本地的显示
![image](https://github.com/wildfirechat/ios-chat/assets/11338629/11ade927-473f-4262-8380-9c461a4dc253)
这是野火iOS端内的显示
![image](https://github.com/wildfirechat/ios-chat/assets/11338629/dab22cf1-8f57-4762-8609-03ff802afa99)

**Comment by heavyrain2012** [comment]
可能是链接的编码问题，请把链接发给我测试 一下

**Comment by zenggong965** [comment]
> 可能是链接的编码问题，请把链接发给我测试 一下

@heavyrain2012 这是我用来测试的pdf
[演示pdf.pdf](https://github.com/wildfirechat/ios-chat/files/12384965/pdf.pdf)

**Comment by heavyrain2012** [comment]
查出来了，是web客户端的问题，web客户端发送消息时没有正确设置contentType，请更新最新版本的web sdk
