### ISSUE TITLE
通过bugly上报崩溃 NSInternalInconsistencyException

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/ios-chat#463]
详情请看

https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/1002?pid=2

https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/4?pid=2

**Comment by heavyrain2012** [comment]
fix by https://github.com/wildfirechat/ios-chat/commit/666877da9676d4d71ace4a8f455bc85626503fc1
