### ISSUE TITLE
打不开pptx文件

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/ios-chat#464]
### 操作说明
网页版发送pptx文件给iOS端，或iOS端从会话右下角加号操作栏里发送本机pptx文件到网页端

### 表现现象
iOS端查看此pptx文件显示损坏
同样内容的文件，用power point打开后保存成ppt就没问题

### 预期结果
iOS端要能正常打开pptx文件

[截图和测试文件.zip](https://github.com/wildfirechat/ios-chat/files/12415819/default.zip)

**Comment by heavyrain2012** [comment]
应该是浏览器打开在线文件的问题，我们准备后续调整一下策略，先下载再打开。你们可以这样改一下

**Comment by heavyrain2012** [comment]
我也觉得很奇怪，不知道为什么浏览器就是打不开。关于打开文件的所有源码都是可见的，你们可以自己调调看看

**Comment by imndx** [comment]
这个问题，我知道原因了，还是`content-type`不对，`ppt`和`pptx`的`MIME type`不一样。

FYI：
[Common MIME Types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)
