### ISSUE TITLE
群消息，已读时间戳 精度不准误差大的bug

### ISSUE THREAD

**Issue by DevXieChao** [wildfirechat/ios-chat#466]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象
群聊 A 发消息，B、C间隔5秒依次进群已读，此消息的B、C已读时间戳是一样的，存在误差
存在的问题：已读时间戳误差太大

#### 预期结果
需求：消息阅读状态页面: 阅读状态人员排序需统一，已读的人员排序按照已读时间排序，已读时间早的人，排在前面；
结果：
会话的每个用户的已读时间戳，能精确到秒或毫秒级别

#### 补充条件
必现，iOS、Android都存在这个问题

#### demo对比结果
demo也存在此问题

**Comment by heavyrain2012** [comment]
实际上是没有意义的，因为野火的阅读状态是只记录最后阅读时间，所以除了最后一条消息以外，其他消息的阅读时间都没有意义。建议自然排序，不要关注阅读时间
