### ISSUE TITLE
垃圾

### ISSUE THREAD

**Issue by jacinzhang** [wildfirechat/ios-chat#467]
为啥 Vendor 使用的第三方库，直接把别人源码拖进来？？？

你们是怎么想的，这么垃圾的东西还敢开源出来。

**Comment by heavyrain2012** [comment]
您好， vendor目录放置第三方源码是通用的规则，把开源的源码放到vendor目录是没有问题的。我们项目目前已经支撑了几百个企业实现了自由即时通讯能力的接入，还是有一定的社会价值的。当然我们研发能力一般且任务比较重，难免代码有些不规范，您可以给我们提PR。感谢您对我们的支持和理解！
