### ISSUE TITLE
bugly 上报崩溃 NSInternalInconsistencyException

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/ios-chat#472]
bug详情

https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/1002?pid=2

https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/4?pid=2

**Comment by imndx** [comment]
<img width="1472" alt="image" src="https://github.com/wildfirechat/ios-chat/assets/34434072/6712d3f2-8bc3-4adf-81f9-207fe2ced4b8">

**Comment by zenggong965** [comment]
[![pPIcgFs.png](https://z1.ax1x.com/2023/09/21/pPIcgFs.png)](https://imgse.com/i/pPIcgFs)

**Comment by heavyrain2012** [comment]
这个问题已经修改了，在 WFCUMessageListViewController.m 文件中，去掉了insertItemsAtIndexPaths方法，请更新验证
