### ISSUE TITLE
bugly 上报崩溃 NSInvalidArgumentException

### ISSUE THREAD

**Issue by zenggong965** [wildfirechat/ios-chat#474]
问题详情
https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/4008?pid=2

https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/9002?pid=2

https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/4018?pid=2

https://bugly.qq.com/v2/crash-reporting/crashes/b3438dbe5c/2010?pid=2

**Comment by FelicityCiao** [comment]
附上
![474-1](https://github.com/wildfirechat/ios-chat/assets/5611610/2d5f098f-18d4-42e1-af05-81ac1838e9b0)
![474-2](https://github.com/wildfirechat/ios-chat/assets/5611610/f4a8a754-3441-4e91-b492-27d8b065e291)
![474-3](https://github.com/wildfirechat/ios-chat/assets/5611610/e6ee0ab5-9ea6-45d5-9cfc-36b17fd55fe6)
![474-4](https://github.com/wildfirechat/ios-chat/assets/5611610/73ddd751-de96-4388-aae3-8f929023da0f)
崩溃堆栈截图

**Comment by heavyrain2012** [comment]
这几个崩溃看不出崩溃在哪里，需要根据符号表解出来行号，看着像是上层的崩溃
