### ISSUE TITLE
编辑保存超出字数限制的群公告，会停留在“保存中”状态，实际保存失败，但群内已发布了群公告消息。

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/ios-chat#477]
####操作说明及现象：
群-编辑群公告，
当长度超过一定值（试了下似乎是英文255和中文249）就会停留在“保存中”... 
此时只能手动返回。
查看群公告栏保存失败，但是群内还是发布了消息 
“@ 所有人 xxxx”。

概率：100%

####预期结果：
提示保存失败及正确说明，群内不应该发布显示未保存的群公告。

**Comment by heavyrain2012** [comment]
duplicate https://github.com/wildfirechat/android-chat/issues/825
