### ISSUE TITLE
IM 有时会无法连接到服务器

### ISSUE THREAD

**Issue by zeroskylian** [wildfirechat/ios-chat#479]
从后台到前台有时会出现，未连接到服务器的情况，消息、IM 状态无法刷新。这时需要再次退出到后台，再次进入前台才能连接到服务器。

**Comment by heavyrain2012** [comment]
请把日志发给我们分析一下，协议栈会默认存储最近5天的日志，试试随便找个会话发送文本消息：```*#marslog#``` 这个命令会把日志文件发出来，如果要是不起作用，sdk有个接口获取日志文件路径的接口，可以写代码把这个文件读出来上传或者发送文件

**Comment by zeroskylian** [comment]
调用 *#marslog# 这个指令会直接将日志发送给你么？

**Comment by zeroskylian** [comment]
好的，明白了。不过输入指令，没有效果。之后我这边看下，通过代码把日志拿到发给你们。

**Comment by imndx** [comment]
> 调用 *#marslog# 这个指令会直接将日志发送给你么？

不是的，是发到当前会话。就是你随便找一个人跟他聊天，然后你发送`*#marslog#`这个文本消息，就会把日志文件发到当前这个聊天会话里面，然后，你就可以把这个文件保存下来，通过邮件等方式发给我们。

**Comment by guodonghuang** [comment]
已发邮件（含日志文件）
