### ISSUE TITLE
iOS低版本更新SDK后，仍然无法正常打开

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/ios-chat#480]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
iOS低版本更新SDK后，仍然无法正常打开

#### 表现现象
iOS低版本更新SDK后，仍然无法正常打开

#### 预期结果
iOS低版本更新SDK后，正常使用

#### 补充条件
![HENGLNK截图_1698930754406](https://github.com/wildfirechat/ios-chat/assets/23655609/2547a3eb-a651-4886-8e56-460aaa976834)

![企业微信截图_c9561363-67ea-4ba7-a237-316b2b046c90](https://github.com/wildfirechat/ios-chat/assets/23655609/8bfb334d-0bf8-462f-b98b-254db3d16334)
![企业微信截图_69e4c513-4299-4596-87b9-15da60e68758](https://github.com/wildfirechat/ios-chat/assets/23655609/9058bf08-5455-4fc1-a3a1-326654db159c)

**Comment by heavyrain2012** [comment]
请确认下面几个问题：
1. 野火demo可以直接运行吗？
2. 你们是怎么使用SDK的？

**Comment by zeroskylian** [comment]
1. 我们使用的是打包sdk的方式引用的

2. 在 Xcode 14.2 + 最新的sdk + iOS 12 真机/模拟器可以运行；在 Xcode 15 + 最新的sdk 打的包无法在iOS 真机运行

**Comment by zeroskylian** [comment]
野火demo因为没有真机无法测试，而且Xcode15 无法添加 iOS 12 的模拟器，也无法在模拟器上测试

**Comment by heavyrain2012** [comment]
> 野火demo因为没有真机无法测试，而且Xcode15 无法添加 iOS 12 的模拟器，也无法在模拟器上测试

没有真机无法测试是什么情况？前面不是说 ```在 Xcode 14.2 + 最新的sdk + iOS 12 真机/模拟器可以运行；在 Xcode 15 + 最新的sdk 打的包无法在iOS 真机运行``` 吗？

请想办法用我们的demo代码测试一下，可以修改包名和签名信息等，因为只有用demo测试出来问题，我们才能去解决

**Comment by zeroskylian** [comment]
好的，之前是外部用户反馈的问题，开发这边通过旧版Xcode上传的包客户正常运行起来了，demo真机这边我们尽量处理下
