### ISSUE TITLE
删除好友申请（未添加的好友申请），当有新的好友申请进来后，已删除的申请会重新展示

### ISSUE THREAD

**Issue by aiyouBug** [wildfirechat/ios-chat#481]
删除好友申请（未添加的好友申请），当有新的好友申请进来后，已删除的申请会重新展示，demo同样（如下图 删除好友请求——>再次添加）
具体操作如下如  
![删除前](https://github.com/wildfirechat/ios-chat/assets/20496772/1e218cd8-4312-43e6-8e3b-b2ed7d1b36b2)
![删除后](https://github.com/wildfirechat/ios-chat/assets/20496772/d0bfbc74-1868-4e46-8df0-dfb6b9de51c9)
![再次添加](https://github.com/wildfirechat/ios-chat/assets/20496772/be927a28-a5bb-4cb9-a04a-c4930824fc77)

**Comment by heavyrain2012** [comment]
协议栈的问题，请更新最新SDK验证
