### ISSUE TITLE
iOS端SDK 撤回超长消息时不能立即拿到extraModel.recallRecord

### ISSUE THREAD

**Issue by lizhe001** [wildfirechat/ios-chat#485]
#### 操作说明
在客户端聊天页面，发送超长消息后进行撤回操作。

#### 表现现象
超长文本消息撤回处理后通过WFCCIMService.sharedWFCIM()?.getMessage(msgId)获取消息，extraModel中没有recallRecall字段，间隔时间再次获取能够取到。短文本消息能立即取到recallRecall字段。

#### 预期结果
超长文本能立即返回recallRecall字段

#### 补充条件
必现。版本号：0.2.8.17

#### demo对比结果
demo没问题

**Comment by heavyrain2012** [comment]
最新版本应该已经解决，请更新验证
