### ISSUE TITLE
当手机空间不足，数据库写入会失败，当用户清理出空间后，无法重新恢复读取到数据库聊天信息；

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/ios-chat#486]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象
当手机空间不足，数据库写入会失败，当用户清理出空间后，无法读取到数据库聊天信息；

#### 预期结果
当用户清理出空间后，可以恢复读取本地数据；

**Comment by heavyrain2012** [comment]
最近代码已经解决这个问题，当数据库写失败后，如果检查可用磁盘空间不足，不会再删除数据库
