### ISSUE TITLE
当无网络下退出登录，恢复网络后，app处于登出状态，仍然能收到推送

### ISSUE THREAD

**Issue by guodonghuang** [wildfirechat/ios-chat#487]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
1，关闭网络
2，退出登录
3，恢复网络
4，此时仍然能收到消息推送，包含离线推送

#### 表现现象
当无网络下退出登录，恢复网络后，app处于登出状态，仍然能收到推送，含离线推送

#### 预期结果
退出后收不到推送

#### 补充条件
必现

#### demo对比结果
demo必现（ios端）

**Comment by heavyrain2012** [comment]
退出登录有个参数是disablePush，当这个参数为true时，协议栈会发送一个请求到IM服务停掉推送，然后才会断开链接，这样再有这个用户的消息就不会推送了。

如果断网的话，这个请求就不会发送到IM服务了。如果之后这个用户在别的手机登录或者这个手机登录别的账号，也都不会有问题。

如果要像精确控制，需要在退出登录时检查网络请求，如果处于未连接状态，不允许退出登录，这样确保在退出登录时能够发停掉推送的请求发送的IM服务

**Comment by guodonghuang** [comment]
好的
