### ISSUE TITLE
ios最新版本的本地通知不起作用

### ISSUE THREAD

**Issue by zjh181240** [wildfirechat/ios-chat#488]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
我使用苹果16有弹出本地通知，苹果17没有弹出本地通知

**Comment by heavyrain2012** [comment]
这个问题您可以查一下，应该跟IM SDK没有关系，如果有什么需求我们改的可以把分析结果告诉我们
