### ISSUE TITLE
消息第一次闪屏

### ISSUE THREAD

**Issue by SeongBrave** [wildfirechat/ios-chat#489]
https://github.com/wildfirechat/ios-chat/assets/10784393/737845e5-a06d-479b-b3ef-8b1dd200e2ac

如视频所示，每次重新安装会有明显的闪一下，这个可以修复吗？

**Comment by heavyrain2012** [comment]
原因是客户端先拉回消息生成会话列表，然后再同步设置，设置中包含删除会话的信息，这时候再删除被标记删除的会话，这样在UI上就会先显示所有的历史会话，然后再闪一次去掉之前删除的会话。

因为协议栈同步机制无法修改，所以如果要想避免这种情况只能UI上改，同步设置会在连接状态变成1之前完成，所以方法1，在连接状态变成1时才进入到会话列表，这个时候已经同步完成的，问题是如果数据量比较大会等待较长时间；方法2是在会话列表这里，只有连接状态变成1之后才显示，同样也是不能让用户快速看到会话列表

**Comment by SeongBrave** [comment]
@heavyrain2012  按照您说的这个思路，咱的官方demo 方便可以修复下吗？

**Comment by heavyrain2012** [comment]
上面提到的修复方法都是有代价的，会牺牲展示会话列表的时间，我们这边认为付出的代价换取到的收益（解决闪一下的问题）是不值得的，所以我们这边是不能这样处理的。建议你们可以保持现状，这个闪一下的问题并不严重
