### ISSUE TITLE
使用有线/蓝牙耳机时，在iOS端点击接收与发送语音消息，均为手机扬声器播放

### ISSUE THREAD

**Issue by FelicityCiao** [wildfirechat/ios-chat#490]
#### 操作说明
手机连接有线/蓝牙耳机，
进入野火App，
点击任意会话中的语音消息（接收/发送的均可）

#### 表现现象
声音从手机扬声器播放

#### 预期结果
语音消息的音频从耳机端传输

#### 补充条件
视频源播放正常，音频声音从耳机传出

**Comment by heavyrain2012** [comment]
已经添加处理，检查提交 https://github.com/wildfirechat/ios-chat/commit/6658f5d436ed271c287ca1e7154ed7331c8de9f8
