### ISSUE TITLE
VoIP 的来电推送和通话页面，如何获取用户备注名/昵称呢？

### ISSUE THREAD

**Issue by PaulYan233** [wildfirechat/ios-chat#492]
1. 开启 VoIP 功能， 在 App 杀掉以后，收到语音电话时，VoIP 页面只能显示用户的 ID，没法获取到好友备注 或者 displayName。
2. App 被系统唤醒时，无法执行异步请求。 

这个问题有什么解决办法吗？  

比如：有没有可能在推送消息中加入用户名或备注字段？

**Comment by heavyrain2012** [comment]
1，用demo对比过吗，demo上是什么情况？
2，voip推送应该会拉起应用，在应用被拉起后调用connect之后就可以获取到本地存储的用户信息了
3，IM服务到推送服务的信息中有sender的名字，你们看看是不是可以用
4，“App 被系统唤醒时，无法执行异步请求” 是什么意思？

**Comment by Darwin-666** [comment]
1，demo上是就是这样的情况？
2，connect 还是异步请求吧？无法执行的
3，推送的sender只是id，没有其他信息
4. “无法执行异步请求” 指的是无法通过网络请求获取数据，只能读取本地信息。  （而且如果通话来自群聊，很可能本地也没有这个用户的名称）

**Comment by heavyrain2012** [comment]
2，connect 还是异步请求吧？无法执行的
我的理解是在客户端收到推送时会拉起应用，application:didFinishLaunchingWithOptions: 函数应该被执行，在这个函数里实现用保存的用户id和token进行connect，connect是个同步打开数据库的接口，调用之后就可以读数据库了。这样在voip的推送处理的地方可以直接调用获取用户信息的接口

3，推送的sender只是id，没有其他信息
IM服务到推送服务的信息有发送者的用户名，从推送服务到客户端你们可以看看能不能加上这个信息

**Comment by Darwin-666** [comment]
感谢回复，第2条 connect是个同步打开数据库，这个了解了谢谢。 
但是如果这个用户是群聊里发起的通话，本地数据库没有这个用户信息 那也还是没法显示用户名吧？
