### ISSUE TITLE
野火后台如何设置可以不发送对撤回动作的远程推送消息

### ISSUE THREAD

**Issue by Omgmaple** [wildfirechat/ios-chat#493]
现在有撤回动作，应用会收到对应消息的撤回推送，后台和前端如何禁止这个动作的推送消息，本地和远程推送都要禁止

**Comment by heavyrain2012** [comment]
找到对应的代码改一下就行了，相关代码都是开源的，你可以自己找一下

**Comment by heavyrain2012** [comment]
在本地通知和推送服务，检查如果是撤回消息，不推送就OK了，找到地方判断一下消息类型就行
