### ISSUE TITLE
文本输入框编辑问题

### ISSUE THREAD

**Issue by jianshili** [wildfirechat/ios-chat#495]
文本输入框，当输入超过3行字符后，不论怎么点击、都没法点击选中最后一行文字，也就没法从最后一个文本继续编辑。

https://github.com/wildfirechat/ios-chat/assets/15863530/b7d2b1ea-99c8-48ac-a54a-b01835c65337

**Comment by heavyrain2012** [comment]
已经解决，请更新验证

**Comment by jianshili** [comment]
具体怎么解决啊、我这儿不太方便直接更新、

**Comment by heavyrain2012** [comment]
请检查我们的提交记录
