### ISSUE TITLE
为异步的 api 调用 设置超时时间

### ISSUE THREAD

**Issue by lovivid** [wildfirechat/ios-chat#497]
## 提issue小提示
以修改用户名称为例子
/**
 修改个人信息
 
 @param values 信息
 @param successBlock 成功的回调
 @param errorBlock 失败的回调
 @discuss 性别属性是int类型，修改时需要转为字符串类型
 */
-(void)modifyMyInfo:(NSDictionary<NSNumber */*ModifyMyInfoType*/, NSString *> *)values
            success:(void(^)(void))successBlock
              error:(void(^)(int error_code))errorBlock;

发现 没有网的时候，超时时间过长，大概有1分钟才走 error 回调

#### 操作说明
手机 or 模拟器断网，调用异步API（比如 修改用户名）

#### 表现现象
超时时间过长，大概有1分钟才走 error 回调

#### 预期结果
异步的 api 调用，有办法设置超时时间，或者减小默认的 超时时间

**Comment by heavyrain2012** [comment]
协议栈用的是mars连接库，无法处理超时时间，有个办法是调用api之前先检查一下连接状态，如果不在线直接提示失败
