### ISSUE TITLE
iOS 上无法接收方默认关闭扬声器

### ISSUE THREAD

**Issue by PaulYan233** [wildfirechat/ios-chat#498]
现状：扬声器在viewDidload关闭后（enableSpeaker） 会在WFAVEngineDelegate的didChangeState 回调中设置为打开 

疑问：有没有方法可以默认关闭扬声器 然后 使用方手动打开才打开扬声器

**Comment by heavyrain2012** [comment]
没有明白你的问题，请详细说明问题

**Comment by truextcfans** [comment]
手动设置 [self.currentSession enableSpeaker:NO] 后 self.currentSession.isSpeaker 为NO
但是在WFAVCallSessionDelegate中的 didChangeState 回调中
self.currentSession.isSpeaker 又变为YES了

这样就会出现无法设置扬声器默认关闭这个功能

**Comment by heavyrain2012** [comment]
手动设置 [self.currentSession enableSpeaker:NO] 后 self.currentSession.isSpeaker 为NO

这个设置的时候 call 的state是什么？

但是在WFAVCallSessionDelegate中的 didChangeState 回调中self.currentSession.isSpeaker 又变为YES了
回调的是那个state？

**Comment by truextcfans** [comment]
self.currentSession.isSpeaker = 0,  self.currentSession.state = 2
self.currentSession.isSpeaker = 0,  self.currentSession.state = 3
 self.currentSession.isSpeaker = 1,  self.currentSession.state = 4
不管在  kWFAVEngineStateIncomming,
  还是 kWFAVEngineStateConnecting, 状态下设置[self.currentSession enableSpeaker:NO]
然后在state变成 kWFAVEngineStateConnected时  self.currentSession.isSpeaker 又变为YES 了

**Comment by truextcfans** [comment]
接通过程中 sdk会自动打开扬声器吗？

**Comment by heavyrain2012** [comment]
SDK中不会自动切换扬声器，我们在demo代码中测试过，在WFCUVideoViewController的viewdidload里 [self.currentSession enableSpeaker:NO]，然后在删除掉这个文件里的其他[self.currentSession enableSpeaker:YES]（在didChangeState的方法里去掉开启扬声器的代码），发出视频电话和接收视频电话都可以关闭扬声器了

**Comment by truextcfans** [comment]
我测试过了 不止[self.currentSession enableSpeaker:YES] 我把代码里所有 [self.currentSession enableSpeaker: 相关代码都删除后 
搜索enableSpeaker 只剩下一个 viewdidload里的  [self.currentSession enableSpeaker:NO]
这样 在接收视频后 在didChangeState回调里   self.currentSession.isSpeaker 还是变为YES 了

**Comment by truextcfans** [comment]
![15121718015389_ pic](https://github.com/wildfirechat/ios-chat/assets/15995659/5e35a2be-73ae-4933-9bcf-0086524db947)
如图  搜索侧 只有viewdidload里的一个log代码 和 一个  [self.currentSession enableSpeaker:NO] 代码 
然后log日志里 在didChangeState回调里 self.currentSession.isSpeaker 还是变为YES 了

**Comment by heavyrain2012** [comment]
你用demo，只改地址和开发者账户，确保不修改demo源码运行起来，然后再在demo上修改在拨打视频时关掉speaker，如果能够复现，把你的修改提个PR，我们根据PR来复现这个问题

**Comment by truextcfans** [comment]
demo没有问题 可能是专业版sdk的问题
