### ISSUE TITLE
上传图片和视频时获取不到上传进度

### ISSUE THREAD

**Issue by TWY-9238944** [wildfirechat/ios-chat#499]
调用uploadMedia上传图片时，progress没有返回上传进度，需要做加载动画，所以希望能拿到上传进度

**Comment by heavyrain2012** [comment]
在协议中的实现是，数据分批拷贝到socket中，当总体大小大于50KB且没有全部拷贝完成时，回调上传进度。在不同的平台socket的buffer大小是不一样的，在iOS手机上buffer大小大概是200KB，所以如果测试上传进度，请确保上传的文件较大，可以测试一下，上传2MB的图片

**Comment by heavyrain2012** [comment]
选择图片发送，可能会有压缩和裁剪，可以在上传前打印一下大小的日志，确保文件足够大
