### ISSUE TITLE
ios 模糊搜索 搜索不到

### ISSUE THREAD

**Issue by nbXiaoZhi** [wildfirechat/ios-chat#500]
假如信息内容是“测试15486” 搜索 154 能搜索到信息  打算搜索“5486” 就搜索不到

**Comment by heavyrain2012** [comment]
你用微信搜索一下看看，微信也是这样的，可能我们用了共同的库的原因

**Comment by nbXiaoZhi** [comment]
有什么办法能解决呢？我的是客户提出来的 客户群聊天中发了甲方的电话 客户想搜索时 搜索电话后的4位 它搜不到,能麻烦您能给个方法吗？还是说无法解决

**Comment by heavyrain2012** [comment]
没有办法解决的，微信也是这样的。我跟我们架构师确认了一下，原因是我们和微信的搜索采用的都是FTS搜索，使用了相似的分词原则，只能是开头匹配。如果要是任意匹配，分词表的大小将会增大非常大。综合考虑保持与微信一致是最合理的选择

**Comment by nbXiaoZhi** [comment]
好的 谢谢您！
