### ISSUE TITLE
iOS 文本消息之链接URL

### ISSUE THREAD

**Issue by jianshili** [wildfirechat/ios-chat#501]
问题1：文本消息的判断URL正则有问题，一句话中有多个链接只能识别一个，当点击链接时，却能跳转多次。

问题2: 文本字体如果是系统字体(systemFontOfSize)，遵循attributedLabelDelegate该协议后，点击能准确定位到本文索引。但使用fontWithName:size: 设置字体后，点击文本不能定位到相对位置。
AttributedLabel 类下的- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event方法：CFIndex index = [self characterIndexAtPoint:[touch locationInView:self]];
index 返回类似9223372036854775807这样的值。
详情请见视频操作。

视频1: https://github.com/user-attachments/assets/fcb16ad9-0665-461b-be44-4537c2ab683e

视频2: https://github.com/user-attachments/assets/26d1b36f-4065-4391-8a51-95bc9b36132f

**Comment by heavyrain2012** [comment]
问题一已经解决

**Comment by heavyrain2012** [comment]
问题2也应该已经解决，请用最新代码验证
