### ISSUE TITLE
iOS18 WFCUMessageListViewController页面出现崩溃

### ISSUE THREAD

**Issue by xingtianwuganqi** [wildfirechat/ios-chat#505]
#### 操作说明
iOS18系统上，点击会话列表进入聊天页面出现崩溃闪退
#### 表现现象
iOS18系统上，点击会话列表进入聊天页面出现崩溃闪退，如果聊天页面为空，没有内容，不会崩溃，有聊天内容必崩
崩溃日志：
*** Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:layout:withLayoutAttributes:applyAttributes:], UICollectionView.m:3939
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The collection view's data source returned a supplementary view that is in the reuse queue. Supplementary views must be retrieved by calling dequeueConfiguredReusableSupplementaryViewWithRegistration:forIndexPath: or -dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:. Collection view: <UICollectionView: 0x114c44e00; frame = (0 0; 390 671); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x300b35b00>; backgroundColor = UIExtendedSRGBColorSpace 0.952941 0.952941 0.952941 1; layer = <CALayer: 0x30051bb80>; contentOffset: {0, 0}; contentSize: {390, 3355.65234375}; adjustedContentInset: {0, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x114c37c00>; dataSource: <WFCUMessageListViewController: 0x1066cf000>>; element kind: UICollectionElementKindSectionHeader; index path: (0-0); supplementary view: <UICollectionReusableView: 0x114f4ae00; frame = (0 0; 390 20); hidden = YES; layer = <CALayer: 0x30050ed60>>'
*** First throw call stack:
(0x18bed908c 0x1891db2e4 0x18b2aa15c 0x18e8a4e5c 0x18e8a3ad0 0x18e9ce204 0x18e7d8ca0 0x18e9316f4 0x18e630578 0x18d975664 0x18d9751f0 0x18d9cc29c 0x18d94b0d4 0x18d98e398 0x18e6ceb78 0x18e6cc174 0x18e6cbfe8 0x18e6cbc38 0x18e6ccbac 0x18beac088 0x18beac01c 0x18bea9b6c 0x18bea8d04 0x18bea85b8 0x1d793e1c4 0x18e9fe5f0 0x18eaad10c 0x102db5734 0x1b167bd34)
libc++abi: terminating due to uncaught exception of type NSException

#### 预期结果
预期结果进入聊天页面看到聊天记录

#### 补充条件
iOS18系统上，点击会话列表进入聊天页面出现崩溃闪退，如果聊天页面为空，没有内容，不会崩溃，有聊天内容必崩

#### demo对比结果
运行的旧版本demo，如果新版本WFCUMessageListViewController没有改动，新版本demo预计也会崩溃

**Comment by heavyrain2012** [comment]
看这个提交 https://github.com/wildfirechat/ios-chat/commit/5de12f995edea85551d1b44809ac84d573a92788

**Comment by xingtianwuganqi** [comment]
感谢，问题得到了解决，但又发现在iOS18系统上，聊天页面的相册按钮点击没有反应，无法打开相册

**Comment by xingtianwuganqi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/tree/master?tab=readme-ov-file，ZLPhotoBrowser升级更新了，支持了iOS18，请帮忙看一下

**Comment by heavyrain2012** [comment]
好的，提交了，请更新验证
