### ISSUE TITLE
被封禁 Connection status 的状态变化不对

### ISSUE THREAD

**Issue by truextcfans** [wildfirechat/ios-chat#506]
## 提issue小提示
当前用户正常登陆状态 然后被封禁 Connection status 的状态变化不对
- (void)setCurrentConnectionStatus:(ConnectionStatus)currentConnectionStatus {
    NSLog(@"Connection status changed to (%ld)", (long)currentConnectionStatus);

#### 操作说明
当前用户被封禁

#### 表现现象
Connection变化过程
Connection status changed to (1)
Connection status changed to (-2)

#### 预期结果
Connection status changed to (1)
Connection status changed to (-3)
Connection status changed to (-2)

#### 补充条件
必现

账号被踢的时候 状态是正常的
Connection status changed to (1)
Connection status changed to (-7)
Connection status changed to (-2)

后台是通过野火admin api里面的block-user-status接口 
http://domain:18080/admin/user/update_block_status

**Comment by heavyrain2012** [comment]
请检查这个提交 https://github.com/wildfirechat/ios-chat/commit/b5d07b1b13e6e05cad0933c0d0977e3faa13e8e0

**Comment by truextcfans** [comment]
[self disconnect:YES clearSession:YES]; 这个逻辑注释掉了 会不会有其他问题

还是说 //    return; 这个步骤注释掉就可以了

**Comment by heavyrain2012** [comment]
可以像 https://github.com/wildfirechat/ios-chat/commit/b5d07b1b13e6e05cad0933c0d0977e3faa13e8e0 这个提交的修改。你说的也可以测试一下有没有问题
