### ISSUE TITLE
iOS18 预览文件消息docx/xlsl，加载白屏

### ISSUE THREAD

**Issue by CoderJYZhu** [wildfirechat/ios-chat#507]
#### 操作说明
消息列表也，点击文件消息WFCCFileMessage消息，如果是docx/xlsl的链接，加载白屏。

#### 表现现象
docx/xlsl的链接 加载白屏，PDF、txt等其他类型预览加载正常

#### 预期结果
正常预览

#### 补充条件
iOS18必然出现，其他系统正常
在查资料的时候 看到iOS18 对文件格式的 服务器的 MIME 类型很严格  必须是application/vnd.openxmlformats-officedocument.spreadsheetml.sheet，查看到后台返回的格式是application/octet-stream的

#### demo对比结果
demo正常，后台的野火是旧版本有问题
我们的后台版本：
![WechatIMG1854](https://github.com/user-attachments/assets/e10f5f64-c55f-4d8b-ac7e-2298d8646c18)

**Comment by heavyrain2012** [comment]
2022.8.26以后的版本都解决了这个问题
