### ISSUE TITLE
在搜索场景下，打开聊天页面出现不能定位某条消息的情况

### ISSUE THREAD

**Issue by DevXieChao** [wildfirechat/ios-chat#509]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象
搜索消息，点击任意数据，跳转到聊天页，出现无法定位到这条消息，也没有闪烁提示

#### 预期结果
定位到刚搜索点击的数据，并有闪烁提示

#### 补充条件
偶现

![排查IM无法定位某条消息-01](https://github.com/user-attachments/assets/7f8b15bd-8dd9-462f-b18e-2eae62fd2354)
![排查IM无法定位某条消息-02](https://github.com/user-attachments/assets/cf9d03c7-fda4-4854-887b-5db4c09bf7a4)

排查代码：IM的api获取不到这个消息，获取消息数据modelList，没有此数据

NSArray *messageListOld = [[WFCCIMService sharedWFCIMService] getMessages:self.conversation contentTypes:nil from:self.highlightMessageId+1 count:35 withUser:self.privateChatUser];
猜想：有没有这种可能，highlightMessageId+1，得到的MessageId 不属于当前的User

demo对比结果
demo也存在此问题

**Comment by heavyrain2012** [comment]
请用上面那个提交验证是否解决了此问题

**Comment by DevXieChao** [comment]
解决了这个问题，谢谢
