### ISSUE TITLE
IOS客户端给android客户端发送语音请求，但是android会收到视频请求

### ISSUE THREAD

**Issue by pcmanjack** [wildfirechat/ios-chat#51]
IOS客户端给android客户端发送语音请求，但是android会收到视频请求。android端接受后可以正常通话。但是过一会android的通话界面会消失。但是通话在进行中也无法挂断 只能ios端挂断

**Comment by pcmanjack** [comment]
os打ios没问题
android打ios没问题
android打android偶尔出问题
ios打android要么 一直显示语音 要么一直显示视频（显示的 总是 android 打ios 最后一次使用的方式）

**Comment by imndx** [comment]
Android的问题，已解决，请下载最新Android代码测试
