### ISSUE TITLE
超级群获取消息展示空白

### ISSUE THREAD

**Issue by 13623027741** [wildfirechat/ios-chat#510]
我们是直接使用了你们的WFChatClient SDK，然后自己实现的UI，具体的问题是在关闭app一段时间后，重新打开获取新消息，这时候消息量可能会比较大，可能在上千条以上，在这种情况下调用了获取消息的接口 getMessagesV2，获取到是有这条文本消息，但是这个消息里面没有内容，读取不到对应的文本内容，显示成空白，只有在重新退出进入获取消息后才有文本数据展示，这个问题目前是偶现的，但是出现的几率会比较大，我们目前使用的版本也是最新的

**Comment by heavyrain2012** [comment]
这个原因是从后台返回到前台时，IM服务连接成功，接收到的当前会话的消息会插入到当前的会话中，而超级群组当收到超过15条时，消息会只接受下来一个ID，并在后续的使用中使用getMessagesV2把未下载的内容下载下来。现在直接插入到会话中了，所以就是空白消息了。

我们推荐的解决方法是，当一个会话一次收到超过15条且内容为空时，把会话内已经加载的消息都移除掉，只展示最后15条已经加载的消息。

请检查我们这几天的代码提交，包括client中消息内容添加了一个notLoaded属性，用来标识消息是否下载下来，及会话列表收到消息的处理。如果有问题请回复。
