### ISSUE TITLE
WFCCIMService 新增一个api，支持批量获取用户，有成功、失败的回调

### ISSUE THREAD

**Issue by DevXieChao** [wildfirechat/ios-chat#511]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 表现现象
在pc上添加成员，在iOS会话列表中显示成员昵称为一串数字
场景：假如邀请多个成员，3人以上显示，只显示前3个成员的昵称，现在是前3个昵称，显示成userId了
eg：
“xxx”邀请“a、b、c”等x名成员加入了群聊

会话列表页面收到 加入了群聊的消息，先获取用户信息，在执行刷新UI操作

#### 预期结果
WFCCIMService 新增一个api，支持批量获取用户(大概5个用户)，有成功、失败的回调

#### 补充条件
WFCCIMService 代码截图
![批量获取用户-01](https://github.com/user-attachments/assets/03e1efa4-7a2e-45ac-8999-05893503f51b)
消息列表页面截图
![批量获取用户-02](https://github.com/user-attachments/assets/9bdf6a60-ac4e-47de-80bb-fad6c62c16e9)

#### demo对比结果
demo也存在此问题

**Comment by heavyrain2012** [comment]
getUserInfos方法返回的数据中，包括已经在本地存在的用户信息，还没有从服务器同步的用户信息也会返回一个空的用户信息，只包含用户ID。所以，如果想要判断用户信息是否有效，可以判断一下用户信息的name字段，如果是空那就是本地还没有加载

**Comment by DevXieChao** [comment]
是的，但是我需要返回的数据都是完整，再去更新UI，而不是一个空的用户信息，只包含用户ID，所以需要一个异步getUserInfos的有成功、失败的回调

**Comment by heavyrain2012** [comment]
我们考虑一下

**Comment by heavyrain2012** [comment]
已经添加，请检查 https://github.com/wildfirechat/ios-chat/commit/ba64eb06be41c1a12ca627c18c7f0cf3d7308edd
