### ISSUE TITLE
删除群聊天记录后，会话被删除

### ISSUE THREAD

**Issue by 794341379** [wildfirechat/ios-chat#52]
<img width="663" alt="WechatIMG478" src="https://user-images.githubusercontent.com/13906299/62752290-7360d800-ba99-11e9-96bb-a27140f7946e.png">
在最新的iOS代码中，这个方法，或造成删除群聊天记录后，会话也删除了，从而找不到这个会话

**Comment by heavyrain2012** [comment]
我们近期会修复
