### ISSUE TITLE
updateMessage主动调用没有效果

### ISSUE THREAD

**Issue by xiefangzhenz** [wildfirechat/ios-chat#54]
安卓：<code>ChatManager.Instance().updateMessage(message.messageId,callStartMessageContet)</code>
iOS:    
<code>[[WFCCIMService sharedWFCIMService] updateMessage:message.messageId content:message.content]</code>

当iOS给Android发消息，Android收到消息之后，调用更新方法，状态更新成功，状态为2
当Android给iOS发消息，iOS收到消息之后，调用更新方法，状态为改变，状态仍为0

发消息的方式如下
<code>
 WFCCCallStartMessageContent *content = [[WFCCCallStartMessageContent alloc]init];    

content.audioOnly = isAudioOnly; 

content.callId = [WFCCNetworkService sharedInstance].userId;
        
content.roomId = @"ceshi";
        
content.status = 0;
       
 content.connectTime = 0;
        
content.endTime = 0;
        
content.targetId = self.conversation.target;

[[WFCCIMService sharedWFCIMService]sendMedia:self.conversation content:content expireDuration:0 success:^(long long messageUid, long long timestamp) {
            
 NSLog(@"send message success(%d)", messageUid);
       
 } progress:^(long uploaded, long total) {

       
 } error:^(int error_code) {
             
NSLog(@"send message fail(%d)", error_code);
        
}];
</code>

**Comment by 794341379** [comment]
是更新extra字段里面的内容么？

**Comment by xiefangzhenz** [comment]
@794341379 我理解错了，只是更新本地的数据，只更新一个端，我以为会更新两个端。谢谢了，我关闭问题。

**Comment by jiangweiqing** [comment]
用此方法更新content的extra中的字段可以更新两端的消息吗？
