### ISSUE TITLE
extra字段，在官方demo测试的过程中，只能在第一次赋值的时候，才能成功持久化

### ISSUE THREAD

**Issue by 794341379** [wildfirechat/ios-chat#56]
extra字段，在官方demo测试的过程中，只能在第一次赋值的时候，才能成功持久化，当需要对extra的附加信息进行修改后，却无法持久化修改后的数据，取出的还是第一次持久化内容。

**Comment by heavyrain2012** [comment]
请测试最近代码是否还有问题
