### ISSUE TITLE
IOS端无法删除会发消息 再次进入viewwillappear刷新会话列表的时候又会出现

### ISSUE THREAD

**Issue by YYYYYYYYYYang** [wildfirechat/ios-chat#57]
IOS端无法删除会发消息 再次进入viewwillappear刷新会话列表的时候又会出现

**Comment by ren445232556** [comment]
用最新项目里面的WFChatClient 替换 你现在项目里面的WFChatClient 应该就可以解决问题了

**Comment by YYYYYYYYYYang** [comment]
> 用最新项目里面的WFChatClient 替换 你现在项目里面的WFChatClient 应该就可以解决问题了

OK 谢谢
