### ISSUE TITLE
ios -项目运行的时候，有时候直接崩到这里

### ISSUE THREAD

**Issue by ren445232556** [wildfirechat/ios-chat#58]
length(const char_type* __s)  _NOEXCEPT {return __builtin_strlen(__s);}

这个是c++ 的问题， 能给看看么

**Comment by heavyrain2012** [comment]
能贴出更多的日志吗，这一段看不出来什么问题

**Comment by xztl** [comment]
同样的问题复现

**Comment by heavyrain2012** [comment]
请贴出更多的崩溃日志，另外提供版本信息
