### ISSUE TITLE
能添加Callkit功能吗？

### ISSUE THREAD

**Issue by MonkeySdkCom** [wildfirechat/ios-chat#6]
能添加Callkit功能吗？语音打电话过来就好像打电话一样

**Comment by heavyrain2012** [comment]
我记得是工信部有法律规定国内不允许上callkit功能，我们不能添加这个功能

**Comment by heavyrain2012** [comment]
http://baijiahao.baidu.com/s?id=1600471684499747492&wfr=spider&for=pc
