### ISSUE TITLE
客户端加入聊天室如果超过一定时间没有动作就会被踢掉

### ISSUE THREAD

**Issue by appjar** [wildfirechat/ios-chat#63]
进入聊天室静置约10分钟（没有收发消息），之后再发消息失败，返回error 20，被踢出。
该问题 iOS和安卓都存在。
希望能够处理。谢谢！

**Comment by heavyrain2012** [comment]
服务配置中添加了如下两个配置，可以根据情况进行配置

## 聊天室观众空闲退出时间，单位为毫秒，默认为15分钟，0为永远不退出
chatroom.participant_idle_time 900000

## 用户向聊天室发送消息，自动加入聊天室
chatroom.rejoin_when_active true
