### ISSUE TITLE
单聊推送，无法正常获取

### ISSUE THREAD

**Issue by bigxx** [wildfirechat/ios-chat#65]
单聊时退到后台，推送收到一条后无法继续收到，回到APP回复该对话后，又可继续收到一条推送，必须回复一条消息后，才可继续收到推送

**Comment by heavyrain2012** [comment]
野火协议栈在退到后台后，如果没有任务执行，后台任务只持续3秒钟，这是如果有消息会有本地通知，3秒之后，程序被冻结，连接断开，这是消息应该走apns，请排查推送服务
