### ISSUE TITLE
可否在客户端增加一个清空本地token的方法？

### ISSUE THREAD

**Issue by 794341379** [wildfirechat/ios-chat#66]
现在在开发的过程中，只限制一个APP登录，服务器在每次登录后，清除掉了服务器的session,但是本地的token或者session与服务器的存在差异，链接后会造成秘钥错误，无法正常链接，可否提供一个情况本地token或者sesstion的方法（清除session的disconnect方法调用后，还是存在问题）

**Comment by heavyrain2012** [comment]
请使用最新代码验证
