### ISSUE TITLE
音视屏通话的消息定义的status 与安卓不同，无法清晰区分通话状态

### ISSUE THREAD

**Issue by YLeaves** [wildfirechat/ios-chat#67]
需要及时变更音视屏通话聊天页面cell的样式，WFCCCallStartMessageContent类定义的status与安卓定义的不同，只有结束原因的类型，不能区分出通话中的状态。且iOS端通话中和结束通话会分别接收WFCCCallSignalMessageContent和WFCCCallByeMessageContent这些未定义的类型消息。

**Comment by YLeaves** [comment]
感谢您的回复
&nbsp; &nbsp; &nbsp; 更新安卓代码修改的只是把CallStartMessageContent的status注释改了，逻辑还是用之前的。安卓的变更通话状态，iOS的还是不行。
&nbsp; &nbsp; &nbsp; 看了安卓代码逻辑有VoipMessageViewHolder类 根据CallStartMessageContent的status处理未接通、通话中、挂断通话时长等。但是iOS没有这块逻辑。按安卓逻辑处理后一直拿不到通话中的状态。且有一个疑惑，在iOS中WFCCCallStartMessageContent定义的status是对应WFAVCallEndReason通话结束原因枚举类型。但是安卓处理还是按以前定义的status为1作为通话中状态对应现在的忙线，这块是不是有些含糊。其外发现iOS通话中和结束分别发送的WFCCCallSignalMessageContent和WFCCCallByeMessageContent这两个未定义的类型，但最终还是根据WFCCCallStartMessageContent来显示通话状态，这一块与其他消息刷新逻辑也不一致。
&nbsp; &nbsp; &nbsp; &nbsp; 望闲暇时解答下，谢谢！

**Comment by imndx** [comment]
现在iOS和Android是统一了，```CallStartMessageContent```里面的status表示的是通话结束原因，通话状态不保存在这个消息体里面。

通话状态需要根据```CallSession#CallSate```判断。
Android的代码如下：
``` AVEngineKit.getCurrentSession().getState()```
