### ISSUE TITLE
转让群主功能缺陷

### ISSUE THREAD

**Issue by YLeaves** [wildfirechat/ios-chat#68]
进行群组转让成功后群的所属人会变更，但是群主和转让人的群成员信息中定义的成员类型没有变化。导致在判断成员角色的时候出现问题。

WFCCGroupInfo类的owner（群主）有变更，但是WFCCGroupMember类的type（群成员类型）没有变化

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by heavyrain2012** [comment]
服务器端问题，请用服务器端最新代码编译验证
