### ISSUE TITLE
真机运行symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by yangshupeng** [wildfirechat/ios-chat#69]
模拟器可以运行，真机运行报错
Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_WFCUVideoViewController
Showing Recent Messages
Undefined symbol: _OBJC_CLASS_$_WFCUProfileTableViewController

**Comment by heavyrain2012** [comment]
选真机，分别运行一遍client和kit试试
