### ISSUE TITLE
联系人列表，好友数多的情况下，UI卡顿，CPU占用高

### ISSUE THREAD

**Issue by LukiWen** [wildfirechat/ios-chat#7]
联系人列表，好友数多的情况下，UI卡顿，CPU占用高

**Comment by heavyrain2012** [comment]
好友有多少？是每次都很慢，还是应用启动后第一次比较慢，还是程序安装后第一次启动慢？

**Comment by LukiWen** [comment]
好友数200左右，程序安装后第一次启动慢，CPU占用高，甚至会闪退，之后就不会了

**Comment by heavyrain2012** [comment]
在加载联系人列表时做了优化，会批量获取联系人，没再出现卡顿，请验证该问题。
另外可以考虑像微信一样，第一次登录有个进度条加载界面，可以把所有的信息都取下来再进入应用
