### ISSUE TITLE
WFChatClient.framework在32位的苹果手机上运行奔溃，系统iOS9.3

### ISSUE THREAD

**Issue by xuchuanjian** [wildfirechat/ios-chat#74]
如图，下面是奔溃的一些信息
Thread 0 crashed with ARM Thread State (32-bit):
    r0: 0x2a065f00    r1: 0x00000000      r2: 0x015032f8      r3: 0xfffff967
    r4: 0x01503290    r5: 0x01505570      r6: 0x0150328c      r7: 0x011f5fcc
    r8: 0x38d18000    r9: 0x39be2744     r10: 0x010bd66c     r11: 0x000000da
    ip: 0x1bc88538    sp: 0x011f5fa4      lr: 0x01390567      pc: 0x015b13a2
  cpsr: 0x00000030

0x11f9000 - 0x14dcfff WFChatClient armv7  <700bf8ed8bf0300da6bc21e1d3a67119> /var/containers/Bundle/Application/5298BB1D-377A-49F6-A2F5-C524C0FE1B72XXXXe.app/Frameworks/WFChatClient.framework/WFChatClient

**Comment by heavyrain2012** [comment]
最新的sdk中已经移除对32位机器的支持，从iphone5s起就采用了64位架构，你们测试机是iphone5/iphone5c？
这类机器市场占有率已经非常少了，不建议继续支持

**Comment by heavyrain2012** [comment]
我们不在提供对ios 32位架构的支持。如果有特殊需求请联系我们
