### ISSUE TITLE
聊天和视频等在后台情况下只能收到三秒内得消息推送

### ISSUE THREAD

**Issue by shamworld** [wildfirechat/ios-chat#75]
iOS应该怎么让程序在后台收到推送 在没有结束进程得时候 而不是3秒钟得时间

**Comment by heavyrain2012** [comment]
iOS SDK的逻辑是：退到后台时，如果没有任务在运行，3秒之后主动与服务器断开结束后台运行，这之后的消息应该走APNS。

请调一下推送服务中的苹果推送功能
