### ISSUE TITLE
运行Demo报request timed out

### ISSUE THREAD

**Issue by LuckySuperStar** [wildfirechat/ios-chat#77]
运行Demo报request timed out,在Demo里没有WFChatUIKit.framework这个框架

**Comment by LuckySuperStar** [comment]
> 编译时先运行client，再运行uikit，最后运行chat工程。如果还无法解决问题，请截图

1.新下载的ios的Demo,先运行client，再运行uikit，最后运行chat工程后在uikit报一个错
![A7DAB2210A77D029B80B9EC3013E83D5](https://user-images.githubusercontent.com/20696266/67998252-be524c00-fc92-11e9-9252-175f2cc3924c.jpg)

2在chat里报这些没找到这些框架
![95FFA0200B772542AEF1B182D6D30A9C](https://user-images.githubusercontent.com/20696266/67998268-ca3e0e00-fc92-11e9-8e5a-1dcd0c2c4077.jpg)

3.我把这些框架在client和uikit找到拖入后,最后还是找不到WFChatUIKit这个框架
![247A0047C37840DAEE360F345D39E6E6](https://user-images.githubusercontent.com/20696266/67998319-0c674f80-fc93-11e9-9a8f-43457d9caf76.jpg)

**Comment by heavyrain2012** [comment]
Mac系统和Xcode都需要升级到最新才行

**Comment by LuckySuperStar** [comment]
谢谢您的回答,如果我想集成到项目中,client和uikit和chat三个都得集成到项目中吗

**Comment by heavyrain2012** [comment]
client和uikit是sdk，可以集成到您的项目中。chat是使用sdk的一个demo，集成时可以参考chat的集成方式

**Comment by LuckySuperStar** [comment]
client和uikit是sdk在哪里下载

**Comment by heavyrain2012** [comment]
在ios-chat那个仓库下，client和uikit是sdk，chat是demo应用
