### ISSUE TITLE
需要实现聊天记录迁移的功能。

### ISSUE THREAD

**Issue by liang21c** [wildfirechat/ios-chat#78]
有个需求是要实现聊天记录迁移的功能。
1. 聊天记录数据库文件是存在ios设备上的哪个位置，文件名是什么，要如何获取到？
2. 数据库文件是有加密的，要如何解密和再加密？

**Comment by heavyrain2012** [comment]
我们计划在client增加下述几个接口：
1，获取某个会话的消息条数
2，批量获取某个会话的100条消息
3，批量插入某个会话的100条消息。

这样你们在实现时，可以如下方法实现：
备份时：获取会话列表，获取每个会话的消息数目，循环读取出所有的消息，把消息保存到一个文件中。
恢复时：从文件中读取消息，分批循环写入。

你们可以先开发UI，等待我们添加接口

**Comment by liang21c** [comment]
好的，辛苦了！

**Comment by heavyrain2012** [comment]
http://docs.wildfirechat.cn/blogs/如何实现聊天记录的备份与恢复.html
