### ISSUE TITLE
两台iPhoneXR手机通话，连接失败

### ISSUE THREAD

**Issue by BzHuang** [wildfirechat/ios-chat#79]
device: iPhone XR
iOS Version: [iOS 12.3]
Xcode Version: [Xcode 10.3]
两台iPhoneXR手机通话，如果两台手机都是双卡双待，webrtc就会很卡甚至连接不上，如果把其中一台的一张卡停掉就没有问题。

**Comment by heavyrain2012** [comment]
这个应该是手机的原因，请参考链接

https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=84053098_3_dg&wd=iphoneXR%20%E5%8F%8C%E5%8D%A1%20%E6%96%AD%E6%B5%81&oq=iphoneXR%2520%25E5%258F%258C%25E5%258D%25A1%2520%25E7%25BD%2591%25E7%25BB%259C%25E9%2597%25AE%25E9%25A2%2598&rsv_pq=85223740000a41c8&rsv_t=5ae12riIYBFTH0mDV4T6IU0RwByZYq%2FAMAsBdwIDfRlFAumBpg0LuugflTBlVEGjrMFLQg&rqlang=cn&rsv_enter=1&rsv_dl=tb&rsv_sug3=11&rsv_sug1=5&rsv_sug7=100&rsv_sug2=0&inputT=3054&rsv_sug4=3553
