### ISSUE TITLE
BUG提交，iPhone手机，在息屏的时候，无法被语音或视讯请求唤醒APP

### ISSUE THREAD

**Issue by 467960686** [wildfirechat/ios-chat#8]
iPhone手机，在息屏的时候，其他用户发起了语音/视频请求的时候，iPhone设备无任何反应。

**Comment by heavyrain2012** [comment]
需要集成apns推送，需要在客户端和服务器分别对接，请参考下面文档。
http://docs.wildfirechat.cn/server/push_config.html
http://docs.wildfirechat.cn/ios/push.html

文档比较简单，需要研发人员对apns足够熟悉，并需要调试推送demo服务，请耐心对待

**Comment by 467960686** [comment]
收到 谢谢回复

**Comment by 467960686** [comment]
****
