### ISSUE TITLE
连续发送6张以上gif接送方和发送方gif显示错乱问题

### ISSUE THREAD

**Issue by 626047426** [wildfirechat/ios-chat#81]
连续发送6张以上gif，发送方会出现自己发送的gif展示的跟上一张一样，但是发的不是上一张GIF图，需要返回上一级界面再刷新以下才会好，接收方有时也会出现图乱情况，在多张gif时候，下面是两张截图可以参考，第二张是发送方真实发的，第一张是显示的
![WechatIMG512](https://user-images.githubusercontent.com/32958898/68262739-2338e800-007f-11ea-9d21-c3f1fc622e0e.png)
![WechatIMG513](https://user-images.githubusercontent.com/32958898/68262746-26cc6f00-007f-11ea-9896-7ddcf6cc74fb.png)

**Comment by heavyrain2012** [comment]
已解决，请使用最新代码验证
