### ISSUE TITLE
iOS 无法删除聊天记录

### ISSUE THREAD

**Issue by ChinaJson** [wildfirechat/ios-chat#84]
iOS 无法删除历史聊天记录

**Comment by heavyrain2012** [comment]
请在服务器关掉获取远程消息功能，请查看服务器配置文件

**Comment by ChinaJson** [comment]
[[WFCCIMService sharedWFCIMService] clearMessages:info.conversation];
                
[[WFCCIMService sharedWFCIMService] removeConversation:info.conversation clearMessage:YES];

一个删除会话的聊天记录 一个删除会话
