### ISSUE TITLE
清除群聊天记录，会把群从聊天列表删除

### ISSUE THREAD

**Issue by liang21c** [wildfirechat/ios-chat#88]
调用这个接口 [[WFCCIMService sharedWFCIMService] clearMessages:self.conversation];
来清除群聊天记录，有个问题是，会把群从聊天列表删除。导致用户无法再找到这个群，无法主动发起群聊天。

**Comment by heavyrain2012** [comment]
请使用我们demo对比，我们测试是不会的，测试方法进入到会话设置，点击清空会话，回调用[[WFCCIMService sharedWFCIMService] clearMessages:self.conversation]方法，返回查看会话还是存在。

另外你们代码有没有更新到最新

**Comment by liang21c** [comment]
能知道是在哪个版本更新了这个功能吗
