### ISSUE TITLE
最新的mars会造成app崩溃

### ISSUE THREAD

**Issue by 794341379** [wildfirechat/ios-chat#90]
在使用最新版本的mars，发现会造成APP崩溃，bugly在运行中抓到了异常

<img width="1145" alt="WX20191113-165512@2x" src="https://user-images.githubusercontent.com/13906299/68747865-61617900-0636-11ea-8836-b167c2820224.png">
<img width="1170" alt="WX20191113-165439@2x" src="https://user-images.githubusercontent.com/13906299/68747867-61fa0f80-0636-11ea-8d93-52620bc179fd.png">

**Comment by 794341379** [comment]
新版的mars,又出现崩溃了
<img width="1196" alt="QQ20191120-181144@2x" src="https://user-images.githubusercontent.com/13906299/69229933-5ae87980-0bc1-11ea-86b7-a9e236a4469a.png">

**Comment by BBS-SuperStar** [comment]
请问，您是怎么解决这个问题的？
