### ISSUE TITLE
/**  更新消息内容    @param messageId 消息ID  @param content 消息内容  更新只是内容既没有更新本地的信息 也没有更新服务器的信息

### ISSUE THREAD

**Issue by jiangweiqing** [wildfirechat/ios-chat#92]
/**
 更新消息内容
 
 @param messageId 消息ID
 @param content 消息内容
 */
- (void)updateMessage:(long)messageId
              content:(WFCCMessageContent *)content;
更新消息中的extra字段 调用此方法之后，并不能更新成功

**Comment by heavyrain2012** [comment]
这个函数就是用来更新本地消息内容的，不能更新消息和服务器端消息。

如果您想更新本地消息，可以删除后再插入。目前无法更新服务器端消息，只能撤回。

另外请问你们在什么场景下需要更新服务器端消息

**Comment by jiangweiqing** [comment]
经测试，这个方法连本地消息也不会更新

**Comment by lays90** [comment]
iOS端更新本地存储信息调用
/**
 更新消息内容
 
 @param messageId 消息ID
 @param content 消息内容
 */
- (void)updateMessage:(long)messageId
              content:(WFCCMessageContent *)content;
并不能更新extra字段  希望能尽快修复

**Comment by heavyrain2012** [comment]
extra字段只能更新本地，不能更新到服务器或者其它端。用最新版本测试，更新extra是有作用的，注意如果是自定义下消息，需要在encode/decode中对extra进行处理

**Comment by heavyrain2012** [comment]
问题没有反馈先关闭，如果有问题请reopen或者新提个issue
