### ISSUE TITLE
apns 无法进行推送，app端无法收到推送

### ISSUE THREAD

**Issue by dilenzhu** [wildfirechat/ios-chat#96]
请问我使用1个月前的IM服务端(之前使用客服端和服务端是配套的，可以正常收到apns 推送)，客户端是2个月之前的。现在apns 无法进行推送。请问是必须要将客户端也更新到最新吗？谢谢！

**Comment by heavyrain2012** [comment]
请更新推送服务

**Comment by dilenzhu** [comment]
好的，谢谢！
